### ISSUE TITLE
Purplish border even after using setBorderColor()

### ISSUE THREAD

**Issue by asc42** [hdodenhof/CircleImageView#102]
Somehow, the border is always a purplish one, even though the method setBorderColor is used.
A variety of colours are loaded from colors.xml, and images are populated in a RecyclerView

**Comment by hdodenhof** [comment]
Please provide screenshots and code samples - it's hard to say what's going on here.

**Comment by asc42** [comment]
Sorry for the late reply, but internet here really sucks.

Can't upload screenshots yet, but I'm using a Fragment, which has a RecyclerView, which is populated by an Adapter.
I'm using **setBorderColor()** in the Adapter, but when I run the app on my device, I get a purplish border, instead of the color(s) I wanted.
So, now I've just hardcoded ?attr/colorAccent to get the Accent Color as the border for all images.

**Adapter:**
	public class BoardAdapter extends RecyclerView.Adapter<BoardAdapter.VH> {

		private LayoutInflater inflater;
		List<People> peopleList = Collections.emptyList();
		Context context;

		public BoardAdapter(Context context, List<People> peopleList) {
			inflater = LayoutInflater.from(context);
			this.peopleList = peopleList;
			this.context = context;
		}

		@Override
		public BoardAdapter.VH onCreateViewHolder(ViewGroup parent, int viewType) {
			View view = inflater.inflate(R.layout.board_right, parent, false);

			if (viewType == 2)
				view = inflater.inflate(R.layout.board_left, parent, false);

			return new VH(view);
		}

		@Override
		public void onBindViewHolder(BoardAdapter.VH holder, int position) {
			People people = peopleList.get(position);
			holder.titleSet.setText(people.title);
			holder.nameSet.setText(people.name);
			holder.imageSet.setImageResource(people.image);
	                holder.imageSet.setBorderColor(people.color);
			final String name = people.name;
			final int image = people.image;
			final String title = people.title;
			final String email = people.email;
	                final int color = people.color
			holder.imageSet.setOnClickListener(new View.OnClickListener() {
				@Override
				public void onClick(View v) {
					// Show a dialog
				}
			});
		}

		public int getItemViewType(int position) {
			return position % 2 * 2;
		}

		@Override
		public int getItemCount() {
			return peopleList.size();
		}

		class VH extends RecyclerView.ViewHolder {
			TextView titleSet, nameSet;
			CircleImageView imageSet;

			public VH(View itemView) {
				super(itemView);
				titleSet = (TextView) itemView.findViewById(R.id.boardTitle);
				nameSet = (TextView) itemView.findViewById(R.id.boardName);
				imageSet = (CircleImageView) itemView.findViewById(R.id.boardImage);
			}
		}
	}

**Fragment:**
	public class BoardFragment extends android.support.v4.app.Fragment {

		@Override
		public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {
			View view = inflater.inflate(R.layout.people_layout, container, false);
			RecyclerView recyclerView = (RecyclerView) view.findViewById(R.id.recyclerView);
			BoardAdapter boardAdapter = new BoardAdapter(getActivity(), getFields());
			recyclerView.setAdapter(boardAdapter);
			recyclerView.setLayoutManager(new LinearLayoutManager(getActivity()));
			return view;
		}

		public static List<People> getFields() {
			int[] teamImages = {
				// A few R.drawable.something fields
			};
			String[] teamNames = {
					...
			};
			String[] teamTitles = {
					...
			};
			String[] teamEmails = {
					...
			};
			int[] teamColors = {
				// A few R.color.something fields
			}

			List<People> peopleList = new ArrayList<>();
			for (int i = 0; i < teamImages.length; i++) {
				People board = new People();
				board.image = teamImages[i];
				board.name = teamNames[i];
				board.title = teamTitles[i];
				board.email = teamEmails[i];
				board.color = teamColors[i]
				peopleList.add(board);
			}
			return peopleList;
		}
	}

**People:**
	public class People {

		public int image;
		public int color;
		public String name;
		public String title;
		public String email;
	}

**people_layout.xml:**
	`<RelativeLayout`
		xmlns:android = "http://schemas.android.com/apk/res/android"
		android:layout_width = "match_parent"
		android:layout_height = "match_parent"
		android:orientation = "vertical">

		<android.support.v7.widget.RecyclerView
			android:id = "@+id/recyclerView"
			android:layout_width = "match_parent"
			android:layout_height = "wrap_content" />
	</RelativeLayout>`

**board_left.xml**
board_right.xml is similar, just with a few layout changes
	`<RelativeLayout`
		xmlns:android = "http://schemas.android.com/apk/res/android"
		xmlns:app = "http://schemas.android.com/apk/res-auto"
		android:layout_width = "match_parent"
		android:layout_height = "match_parent"
		android:orientation = "vertical">

		<de.hdodenhof.circleimageview.CircleImageView
			android:id = "@+id/boardImage"
			android:layout_width = "100dip"
			android:layout_height = "100dip"
			android:layout_alignParentEnd = "true"
			android:layout_marginEnd = "30dip"
			android:layout_marginTop = "10dip"
			app:civ_border_width = "2dip" />

		<TextView
			android:id = "@+id/boardName"
			android:layout_width = "250dip"
			android:layout_height = "wrap_content"
			android:layout_alignParentEnd = "true"
			android:layout_marginEnd = "125dip"
			android:layout_marginTop = "35dip"
			android:gravity = "center"
			android:textSize = "20sp"
			android:textStyle = "bold" />

		<TextView
			android:id = "@+id/boardTitle"
			android:layout_width = "250dip"
			android:layout_height = "wrap_content"
			android:layout_alignParentEnd = "true"
			android:layout_marginEnd = "125dip"
			android:layout_marginTop = "60dip"
			android:gravity = "center"
			android:textSize = "17sp" />
	</RelativeLayout>

**PS**: Might have missed out a few lines after copying and pasting, but those lines don't affect the CircleImageView AFAIK.
Any missing stuff/syntax errors are to be ignored, and the correct syntax is to be assumed (I added a few lines after pasting too).
Also, ignore any formatting issues :/

**Comment by hdodenhof** [comment]
I just had a quick look, but ùsing `holder.imageSet.setBorderColorResource(people.color);` should do the trick. `setBorderColor` expects a `@ColorInt` while `setBorderColorResource` expects a `@ColorRes` and that's what you are supplying.

**Comment by asc42** [comment]
Yes that works, sorry for the dumb issue, my bad :)
