### ISSUE TITLE
selectableItemBackground is square shaped instead circle one

### ISSUE THREAD

**Issue by tajchert** [hdodenhof/CircleImageView#103]
`android:background="?android:attr/selectableItemBackground"`
results in square-looking background when CircleImageView is pressed.
a better is `android:background="?selectableItemBackgroundBorderless"` but this on the other hand is "borderless" so it give a bit other behavior.

**Comment by hdodenhof** [comment]
This is because the `View` itself is still square, not much I can do about that. There's a PR for a custom selector (#35) but that's been stale for a while. You can always just create your own `selectableItemBackground` based on the default one which is circle shaped.
