### ISSUE TITLE
setFillColor() not working

### ISSUE THREAD

**Issue by vipulyaara** [hdodenhof/CircleImageView#104]
setFillColor() and setFillColorResource() have no effect at all. Nothing happens when using these.
Either in xml or java.

PS: I have worked it around by making borderWidth 100 when I want to fill a color, so it fills with the color. But would still like to get fillColor working.

**Comment by hdodenhof** [comment]
What are you trying to achieve? `fillColor` is only used as a background for a drawable with transparent areas. If you just want to have a solid color fill the circle you can use a `ColorDrawable` as source for the `CircleImageView`.

**Comment by vipulyaara** [comment]
Filling circleImageView with a solid color like this would fill the whole square aroudn it. Isn't that the problem setFillColor() solves? I just want to color my circle. That's all.

**Comment by hram** [comment]
And I want set image transparent. I was trying to set transparent with setFillColor() but no luck. I think method name is not correct.

**Comment by hdodenhof** [comment]
As I said, `fillColor` is only used as a background for a drawable with transparent areas - I agree that the naming could be better.

To just fill the circle with a solid color do one of the following:
```
<de.hdodenhof.circleimageview.CircleImageView
    android:layout_width="128dp"
    android:layout_height="128dp"
    android:src="@color/foobar"/>
```
or in code:
```
CircleImageView civ = ...
civ.setImageResource(R.color.foobar);
```

**Comment by gushoubang** [comment]
I also find that it have no effect,when I find the color like this

http://stackoverflow.com/questions/9114587/how-can-i-save-colors-in-array-xml-and-get-its-back-to-color-array

CircleImageView civ = ...
civ.setImageResource(colors[i]);

**Comment by hdodenhof** [comment]
@gushoubang `colors[0]` probably isn't a resource - look for `Resources$NotFoundException` in your logcat. Use `civ.setImageDrawable(new ColorDrawable(rainbow[0]));` instead.
