### ISSUE TITLE
Suggestion: Make another CircleImageView extending AppCompatImageView

### ISSUE THREAD

**Issue by hendraanggrian** [hdodenhof/CircleImageView#105]
`android:tint` isn't working in xml, crashes the app. I suppose this is achievable using AppCompatImageView

**Comment by Wicowyn** [comment]
It's work only on Android 5.0 and after. Before 5.0 we get a crash during inflate : 
```
Caused by: java.lang.NullPointerException
at de.hdodenhof.circleimageview.CircleImageView.setColorFilter(CircleImageView.java:249)
at android.widget.ImageView.setColorFilter(ImageView.java:1111)
at android.widget.ImageView.setColorFilter(ImageView.java:1123)
at android.widget.ImageView.<init>(ImageView.java:157)
at de.hdodenhof.circleimageview.CircleImageView.<init>(CircleImageView.java:88)
at de.hdodenhof.circleimageview.CircleImageView.<init>(CircleImageView.java:84)
```
(with v2.0.0 release)

After debuging it appear that  all ```mBitmapPaint, mBorderPaint, mFillPaint, mDrawableRect, mBorderRect, mShaderMatrix``` are null, whereas they are all initialized and not modifiable.

How is this possible ?

**Comment by colinrtwhite** [comment]
+1 Tint isn't applied to images. Tested on Nexus 5, 6.0.1.

**Comment by hdodenhof** [comment]
The NPE is fixed, thanks to @colinrtwhite.

I'm not gonna make CirlcleImageView extend AppCompatImageView and with that depend on the appcompat library though, as that would needlessly bloat this library.

**Comment by colinrtwhite** [comment]
Good point - I didn't think about the bloat. However, does that mean image tint on pre-Lollipop will not work? Also, when do you plan to make the next release? Thanks.

**Comment by hdodenhof** [comment]
`android:tint` won't work but you can achieve a similar result using `setColorFilter()`. There are no plans for the next release yet, as the only change so far is the non-critical NPE-fix.

**Comment by mingchen** [comment]
Could you release include this fix ?

**Comment by jy617lee** [comment]
as above talks, image tint on after-Lollipop should work. However it doesn't work on android-m... tint attribute is included in not only AppCompatImageView but also ImageView. Why is this? Please have an answer.

**Comment by hdodenhof** [comment]
@jy617lee you misread that, tint is not supported at all.
