### ISSUE TITLE
setImageBitmap not working !

### ISSUE THREAD

**Issue by MrAmmar** [hdodenhof/CircleImageView#106]
Hello,
First thank you for the effort you made on this project, it works smoothly and efficiently.
The problem occurs when trying to load an image manually : 

    ImageView testingArea = (ImageView) findViewById(R.id.testingArea);
    CircleImageView profilepic = (CircleImageView) findViewById(R.id.profilepic);

    protected void onActivityResult(int requestCode, int resultCode, Intent data) {
         ...

        testingArea.setImageBitmap(bm); // works fine
        profilepic.setImageBitmap(bm); //doesn't work
    }

Note : the bitmap size was reduced and scaled, so i think the size causes no problem in
this case.

**Comment by hdodenhof** [comment]
There's nothing obvious wrong with your code and what you are trying to do should work. Could you provide a more extensive code sample?

**Comment by dejoules** [comment]
i have the same issues: (it's work on imageview)

CircleImageView myImage = (CircleImageView) findViewById(R.id.profile_image);
Bitmap myBitmap = BitmapFactory.decodeFile(imgFile.getAbsolutePath());
System.out.println(myBitmap);
myImage.setImageBitmap(myBitmap);


I got --> Caused by: java.lang.NullPointerException
on setImageBitmap line

thank you

**Comment by hdodenhof** [comment]
Original issue lacks details for investigation.
@dejoules: your problem is unrelated, please open a separate issue if still relevant.

**Comment by alpaltunel** [comment]
I am seeing the same issue.
url = "http://www.google.com/logo.png";
CircleImageView imgAvatar = (CircleImageView) findViewById(R.id.imgAvatar);
Bitmap bmp = null;
try {
     InputStream in = new URL(url).openStream();
     mIcon11 = BitmapFactory.decodeStream(in);
} catch (Exception e) {
      Log.e("Error", "error" + e.getMessage());
      e.printStackTrace();
}

imgAvatar.setImageBitmap(bmp);

**result:**
java.lang.NullPointerException: Attempt to invoke virtual method 'void de.hdodenhof.circleimageview.CircleImageView.setImageBitmap(android.graphics.Bitmap)' on a null object reference

**Comment by hdodenhof** [comment]
Well, it seems `findViewById(R.id.imgAvatar)` fails and returns null. Make sure your layout actually contains a view with that ID.

**Comment by praveenverma720** [comment]
I also have faced same problem but i solved it.
Actually we are trying to set Image on null object that is (R.id.imageAvatar) here imageAvatar is from Different layout ,So check your proper layout object and id.
Hope you will get result.
