### ISSUE TITLE
Request: avoid creating a new bitmap for each time you set an image

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [hdodenhof/CircleImageView#107]
For large images, it takes double the memory this way...

Isn't there a better way to achieve this?

**Comment by hdodenhof** [comment]
Well, as the whole method is based on using a `BitmapShader` which needs a `Bitmap`, I don't think there's a better way. Passing in a `BitmapDrawable` avoids creating a new `Bitmap` as the original one is reused.

**Comment by AndroidDeveloperLB** [comment]
Since the bitmap is already the input, there shouldn't be a need to create another.

**Comment by hdodenhof** [comment]
Not sure if we are talking about the same thing. As I said: if the input is a `Bitmap` (wrapped inside a `BitmapDrawable`) no other is created.

https://github.com/hdodenhof/CircleImageView/blob/master/circleimageview/src/main/java/de/hdodenhof/circleimageview/CircleImageView.java#L258-L260

**Comment by hdodenhof** [comment]
Forget about `setImageBitmap`, which also directly uses the supplied `Bitmap`.

**Comment by AndroidDeveloperLB** [comment]
Why should I forget about it?

**Comment by hdodenhof** [comment]
Typo, please reread.

**Comment by AndroidDeveloperLB** [comment]
hmmm.... was sure you create a bitmap. maybe i looked at another repository. 
so, is bitmapShader memory efficient? is it working well even on Android 4.3 and below?
I remember that there are some weird issues related to this, that requires you to disable hardware acceleration on the imageView itself.

**Comment by hdodenhof** [comment]
Afaik it is the most efficient way to achieve what this library intends to do (being a generic solution) and it works across all API levels. So far I haven't encountered any issues directly related to `BitmapShader` requiring `LAYER_TYPE_SOFTWARE`.

**Comment by AndroidDeveloperLB** [comment]
ok, i have no idea then why i wrote this. closing...

**Comment by AndroidDeveloperLB** [comment]
OK, I've found a reason for re-openning this issue:
setImageResource and almost every function that doesn't provide a new bitmap - will create a new bitmap.

So, is it possible to avoid this step?

**Comment by hdodenhof** [comment]
Nop. As I said, `BitmapShader` needs a `Bitmap`.

**Comment by AndroidDeveloperLB** [comment]
Is it possible to have this solution, yet make it work for other drawables, so that you wrap an existing drawable and make it rounded:
http://stackoverflow.com/a/35483275/878126

**Comment by hdodenhof** [comment]
Path clipping is expensive and neither hardware accelerated nor anti-aliased.

**Comment by AndroidDeveloperLB** [comment]
Yes, this is the reason I thought about Android 4.3 . 
So you say it's not as efficient as bitmapShader?
Also, is it possible to use BitmapShader within a drawable (that extends BitmapDrawable) instead, so that a normal ImageView would use it, instead of having a view that extends from ImageView (meaning CircleImageView in this case) ?

**Comment by hdodenhof** [comment]
That's actually what Romain Guy (former Android framework engineer) says: http://www.curious-creature.com/2012/12/11/android-recipe-1-image-with-rounded-corners/

Using `BitmapShader` within a `Drawable` would also work and might even be a better way of doing it for a more specific use case. I put all that inside an `ImageView` for compatibility with custom Drawables mostly from image loading libraries.

**Comment by AndroidDeveloperLB** [comment]
hmmm...
so can you please create a RoundedDrawable class that does about the same as the CircleImageView?
Or at least the basic things ? 
If you do, you can put it here:
http://stackoverflow.com/q/35481807/878126
and I can reward you with the bounty :)

**Comment by hdodenhof** [comment]
Closing as the discussion moved to StackOverflow.
