### ISSUE TITLE
Request: allow to avoid image shrinking when adding border

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [hdodenhof/CircleImageView#112]
I've noticed that the larger the border is, the image gets shrunk so that you will always see the middle-edges (middle left, middle right, middle top, middle bottom).

Please allow to avoid this, and instead shrink the image to the size of the imageView itself, while the border is on top of it.

**Comment by hdodenhof** [comment]
Just use `app:civ_border_overlay="true"` for the desired behavior.

**Comment by AndroidDeveloperLB** [comment]
oh, ok, thank you.
