### ISSUE TITLE
Not working in Android 6.0

### ISSUE THREAD

**Issue by ParitoshChaudhary** [hdodenhof/CircleImageView#114]
I am unable to view the circular image in my application in Samsung Galaxy S6 6.0. Its working in all other device but in this one. Please help me in solving this issue. Thanks

**Comment by hdodenhof** [comment]
You need to provide a little more details - exceptions, description of what exactly happens, code samples.

**Comment by ofirmiron** [comment]
I have a Samsung Galaxy S7 Edge running Android 6.0.1 and it is working fine.
