### ISSUE TITLE
Image not display using Glide

### ISSUE THREAD

**Issue by tigercbc** [hdodenhof/CircleImageView#121]
load a new image into circleImageView not display at first time, but ok at second time.
is there any problem by loading image with Glide?
plz help!

**Comment by hdodenhof** [comment]
From the Readme:
> If you use an image loading library like Picasso or Glide, you need to disable their fade animations to avoid messed up images. For Picasso use the `noFade()` option, for Glide use `dontAnimate()`. If you want to keep the fadeIn animation, you have to fetch the image into a `Target` and apply a custom animation yourself when receiving the `Bitmap`.

Also #57.

**Comment by tigercbc** [comment]
@hdodenhof thank you!

**Comment by katepratik** [comment]
#192 

Found a fix to load Image using glide.
```
Glide.with(context)
                .load(imageLink)
                .asBitmap()
                .dontAnimate()
                .placeholder(R.drawable.user)
                .listener(new RequestListener<String, Bitmap>() {
           @Override
            public boolean onException(Exception e, String s, Target<Bitmap> target, boolean b) {
                return false;
            }
            @Override
            public boolean onResourceReady(Bitmap bitmap, String s, Target<Bitmap> target, boolean b, boolean b1) {
                userImage.setImageBitmap(bitmap);
                return false;
            }
        }).preload();
```
Load bitmap after you get it instead of using into(imageview) method of Glide.
Don't forget Magic line inside onResourceReady : **circleImageView.setImageBitmap(bitmap);**

**Comment by lifeisdream** [comment]
Use the folowing code:
`
GlideApp.with(context)
                            .load(url)
                            .placeholder(R.drawable.planet)
                            .dontAnimate()
                            .into(imageView);
`
and still - first time - white image. second time - ok. 
what do I do wrong?

**Comment by lifeisdream** [comment]
Do I need some specific version? 
I use

implementation 'com.github.bumptech.glide:glide:4.7.1'
annotationProcessor 'com.github.bumptech.glide:compiler:4.7.1'
implementation 'de.hdodenhof:circleimageview:2.2.0'

**Comment by lifeisdream** [comment]
Picasso code 
Picasso.get().load(url).noFade().into(imageView);
still produce white image:
![image](https://user-images.githubusercontent.com/1473995/42291120-63589c20-7fd2-11e8-985c-89c237b9b346.png)

**Comment by lifeisdream** [comment]
also tried:
`
GlideApp.with(context)
                            .asBitmap()
                            .load(url)
                            .dontAnimate()
                            .into(new SimpleTarget<Bitmap>() {
                                @Override
                                public void onResourceReady(@NonNull Bitmap resource, @Nullable Transition<? super Bitmap> transition) {
                                    imageView.setImageBitmap(resource);
                                }
                            });
` with no use =(
