### ISSUE TITLE
Animated Vector Drawable Support?

### ISSUE THREAD

**Issue by vhenriques** [hdodenhof/CircleImageView#122]
Does this lib support vector drawables?

http://android-developers.blogspot.in/2016/02/android-support-library-232.html

**Comment by hdodenhof** [comment]
While VectorDrawables should work, I advise against using them with CircleImageView as there are more efficient solutions, e.g. just creating a circle shaped vector. AnimatedVectorDrawables won't work.

**Comment by vhenriques** [comment]
Thanks for the prompt reply
