### ISSUE TITLE
It's not possible to tint the image view

### ISSUE THREAD

**Issue by martin-ohlin** [hdodenhof/CircleImageView#126]
It would be nice if it was possible to tint images. I guess this also means a rewrite to use AppCompatImageView and DrawableCompat to be able to support tint on older platforms.

**Comment by hdodenhof** [comment]
Please see #105 as to why I'm not gonna rewrite this library to inherit from AppCompatImageView. You can achieve image tinting using a color filter:

```
CircleImageView civ = (CircleImageView) findViewById(R.id.foobar);
int color = getResources().getColor(R.color.imagetint);
ColorFilter cf = new PorterDuffColorFilter(color, PorterDuff.Mode.MULTIPLY);
civ.setColorFilter(cf);
```
