### ISSUE TITLE
Image pixelated on older devices

### ISSUE THREAD

**Issue by tarolechaitanya** [hdodenhof/CircleImageView#128]
Hi!!!
Image seems to be pixelated on devices running android < 4.4
Can you please fix it or guide me ...
Thanks

**Comment by tarolechaitanya** [comment]
Update
Image gets pixelated if we reduce size of image.
I have to show profile picture of user in navigation menu.
I have assigned width and height to image but image seems pixelated with lower width and height dimensions

**Comment by hdodenhof** [comment]
It's very unlikely that your issue is caused by this library, please verify the code for loading and resizing the image. If you think `CircleImageView` is the source of your problem, please post the relevant code snippets.

**Comment by tarolechaitanya** [comment]
I am using below xml code to load image
 <com.util.CircleImageView
                    android:layout_width="60dp"
                    android:layout_height="60dp"
                    android:layout_gravity="center"
                    android:layout_marginBottom="8dp"
                    android:src="@drawable/default_pic" />
If I increase width and height to 100dp, image is displayed without any sharp edges but below 100dp, image shows sharp edges and feels pixelated.

and I will get images in different resolution from web service.

Thanks

**Comment by hdodenhof** [comment]
Relevant code snippets would be the ones that actually load the images from the web service into the view.

**Comment by tarolechaitanya** [comment]
Right now, I have not written code for web services.
Initially I am checking with hard coded values.
I am loading images from drawable folder with different resolutions.

**Comment by hdodenhof** [comment]
Any difference if you use the standard `ImageView` instead of `CircleImageView`?

**Comment by hdodenhof** [comment]
Also: make sure to load an image with a reasonable resolution. If the image is scaled down heavily it'll most definitely lead to quality loss.

**Comment by tarolechaitanya** [comment]
not much difference although scaleType shows different results.
Anyways ,thanks for guiding me.
