### ISSUE TITLE
How to add a shadow and a border on circular imageView android?

### ISSUE THREAD

**Issue by KennethLaw** [hdodenhof/CircleImageView#13]
I found a Solutions https://github.com/lopspower/CircularImageView.
but It is Not Working on less than API 11.
Q: How can I use it in my project contain API level 7?

**Comment by LyndonChin** [comment]
I have just submitted a Pull Request, before the author accept it, you could find the source here 
https://github.com/LyndonChin/CircleImageView

**Comment by amiesharmas** [comment]
Hi, this is not working for Android N and above.
Only 1/4th image is visible.

**Comment by amiesharmas** [comment]
I have just submitted a Pull Request, before the author accept it, you could find the source here
https://github.com/LyndonChin/CircleImageView

Hi, this is not working for Android N and above.
Only 1/4th image is visible.
