### ISSUE TITLE
White color in between border and background

### ISSUE THREAD

**Issue by grote** [hdodenhof/CircleImageView#131]
Have a look at the following screenshot:

![device-2016-05-13-123903](https://cloud.githubusercontent.com/assets/244947/15253734/f973efe8-1909-11e6-9616-352b1580d668.png)

For some colors, there's a very small white border. This is there whether I use `setImageDrawable()` with a `ColorDrawable` or use `setFillColor()` on a transparent background.

**Comment by hdodenhof** [comment]
That's strange. Could you provide details (code extracts) about the listitem-layout and the way you set the drawable?

**Comment by grote** [comment]
I came up with a minimal example that should illustrate the problem:

![circleborder](https://cloud.githubusercontent.com/assets/244947/15292687/9ff2fd44-1b5a-11e6-9958-b8b5ab31615b.png)

```xml
<LinearLayout
	xmlns:android="http://schemas.android.com/apk/res/android"
	xmlns:app="http://schemas.android.com/apk/res-auto"
	android:layout_width="match_parent"
	android:layout_height="match_parent">

	<de.hdodenhof.circleimageview.CircleImageView
		android:id="@+id/circleView"
		android:layout_width="48dp"
		android:layout_height="48dp"
		android:layout_gravity="center"
		android:src="@android:color/transparent"
		app:civ_border_color="#000000"
		app:civ_border_width="2dp"
		app:civ_fill_color="#000000"/>

</LinearLayout>
```
Please note that the same problem exists when filling the `CircleImageView` differently:

```xml
<LinearLayout
	xmlns:android="http://schemas.android.com/apk/res/android"
	xmlns:app="http://schemas.android.com/apk/res-auto"
	android:layout_width="match_parent"
	android:layout_height="match_parent">

	<de.hdodenhof.circleimageview.CircleImageView
		android:id="@+id/circleView"
		android:layout_width="48dp"
		android:layout_height="48dp"
		android:layout_gravity="center"
		android:src="@android:color/black"
		app:civ_border_color="#000000"
		app:civ_border_width="2dp"/>

</LinearLayout>
```

**Comment by hdodenhof** [comment]
Thanks, I'm able to reproduce the issue and I'll look into it. I guess it's related to both the border and the drawable being antialiased. As a workaround you could just add `app:civ_border_overlay="true"`

**Comment by grote** [comment]
Thanks! An initial test indicates that adding `app:civ_border_overlay="true"` does indeed solve the problem.

**Comment by hdodenhof** [comment]
Fix will be release as part of 2.1.0.

**Comment by grote** [comment]
Awesome, thanks! Do I understand correctly that with 2.1.0, it will not be necessary to add `app:civ_border_overlay="true"` ?

**Comment by hdodenhof** [comment]
Exactly!
