### ISSUE TITLE
Error:Execution failed for task ':app:transformClassesWithDexForDebug'. > com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: com.android.dex.DexIndexOverflowException: method ID not in [0, 0xffff]: 65536

### ISSUE THREAD

**Issue by ashishonmobile** [hdodenhof/CircleImageView#132]
After including your library I am getting below error while creating signed and build apk.

Please help.

Regards,
Ashish

**Comment by hdodenhof** [comment]
Your app is exceeding the dex method count, please read https://developer.android.com/studio/build/multidex.html.

**Comment by sonnv1368** [comment]
You can find my answer
http://stackoverflow.com/questions/26609734/how-to-enable-multidexing-with-the-new-android-multidex-support-library/38473900#38473900

Step 1: Change build.grade

defaultConfig {
    ...
    // Enabling multidex support.
    multiDexEnabled true
}

dependencies {
    ...
    compile 'com.android.support:multidex:1.0.0'
}

Step 2: Setting on the Application class

public class MyApplication extends Application {
    @Override
    public void onCreate() {
        super.onCreate();
        MultiDex.install(this);
    }
}

Step 3: Change grade.properties

org.gradle.jvmargs=-Xmx2048m -XX:MaxPermSize=512m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8

Thanks.

**Comment by Devi17** [comment]
i am finish to try this step,and the problem can solve.but when i want to run but i have unfortunately myapplication has stoped. please help me

**Comment by v1gnus** [comment]
Pls how to execute the step 3

**Comment by trinadhkoya** [comment]
Hello @v1gnus 
check your gradle.properties file from app level ,you can see some thing like 
# Default value: -Xmx10248m -XX:MaxPermSize=256m
below that place this ,
org.gradle.jvmargs=-Xmx2048m -XX:MaxPermSize=512m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8
if already exists check # symbol before that,if exists remove it ,else leave it

**Comment by mfdur14** [comment]
but after that my application didnt work when download from google playstore to test my apps.
I guess it is regard with google admob codes.
