### ISSUE TITLE
Add Padding between border and the image

### ISSUE THREAD

**Issue by b-runo** [hdodenhof/CircleImageView#133]
How to create a padding between the border and the image?
Like this [image](http://redesigncase.com/wp-content/uploads/2014/12/Front.jpg)

**Comment by Iamtodor** [comment]
It could be useful
+1

**Comment by hdodenhof** [comment]
There is no native support for this, but you should be able to achieve it by subclassing `CircleImageView` and overriding `onDraw` with some custom behavior while still calling `super.onDraw()`. An easier way would probably be wrapping the `CircleImageView` in a `FrameLayout` which draws the border and has some padding.

**Comment by b-runo** [comment]
I know I'm already asking a lot but have a sample code :sweat_smile:.

**Comment by hdodenhof** [comment]
In your layout:
```
<FrameLayout
    android:layout_width="wrap_content"
    android:layout_height="wrap_content"
    android:padding="4dp"
    android:background="@drawable/circle_background">

    <de.hdodenhof.circleimageview.CircleImageView
        android:layout_width="96dp"
        android:layout_height="96dp"
        android:src="@drawable/foobar"/>

</FrameLayout>
```

And drawable/circle_background.xml:
```
<?xml version="1.0" encoding="utf-8"?>
<shape
    xmlns:android="http://schemas.android.com/apk/res/android"
    android:shape="oval">

    <stroke
        android:width="1dp"
        android:color="#FFFFFF"/>

</shape>
```

**Comment by samitparadedocs** [comment]
Great work. 
Thank you.

**Comment by b-runo** [comment]
Thanks.
