### ISSUE TITLE
xml onClick does not work on some platform versions

### ISSUE THREAD

**Issue by alex-caelus** [hdodenhof/CircleImageView#134]
It's fixed in support library when using the AppCompat's inflater (see https://code.google.com/p/android/issues/detail?id=174871). The fix is to extend ImageView from the support library instead.

Also a workaround is to set the onClick listener programmatically instead.

Just an FYI.

**Comment by hdodenhof** [comment]
Thanks for the heads-up! Extending AppCompatImageView is not really an option as that would make CircleImageView depend on the appcompat library and that would needlessly bloat this library.

I'll close this as it's an upstream bug - should be fixed in M.
