### ISSUE TITLE
When using glide CircleImageView not show pictures.

### ISSUE THREAD

**Issue by tianshaokai** [hdodenhof/CircleImageView#135]
eg: Glide.with(context)
                    .load(url)
                    .override(100, 100)
                    .placeholder(R.drawable.default_touxiang)
                    .error(R.drawable.default_touxiang)
                    .fitCenter()
                    .into(imageView);

**Comment by hdodenhof** [comment]
This has been answered multiple times and is part of the readme. Have a look at #121.

**Comment by katepratik** [comment]
#192 

Found a fix to load Image using glide.
```
Glide.with(context)
                .load(imageLink)
                .asBitmap()
                .dontAnimate()
                .placeholder(R.drawable.user)
                .listener(new RequestListener<String, Bitmap>() {
           @Override
            public boolean onException(Exception e, String s, Target<Bitmap> target, boolean b) {
                return false;
            }
            @Override
            public boolean onResourceReady(Bitmap bitmap, String s, Target<Bitmap> target, boolean b, boolean b1) {
                userImage.setImageBitmap(bitmap);
                return false;
            }
        }).preload();
```
Load bitmap after you get it instead of using into(imageview) method of Glide.
Don't forget Magic line inside onResourceReady : **circleImageView.setImageBitmap(bitmap);**
