### ISSUE TITLE
Vector support with AppCompatImageView

### ISSUE THREAD

**Issue by kaizie** [hdodenhof/CircleImageView#138]
I am trying to load a vector drawable (loading with app:srcCompat="@drawable/xxx") in a phone with API 18 (4.3) and I am getting Resources$NotFoundException. It works for phones with higher API levels (kitkat onwards).

So I have tried just by copy/pasting the CircleImageView.java class and extend from **AppCompatImageView** instead of the normal **ImageView** and it works just fine with no further changes (I have tried with quite a few test phones in my office).

You know your library more in depth and you know if this may give you a headache somewhere... but as far as i see, it should be ok.

Any thoughts?

Btw, thanks for this great library!

**Comment by lawloretienne** [comment]
+1

**Comment by hdodenhof** [comment]
First and foremost I advise against using VectorDrawables with CircleImageView as that is very inefficient. You should modify your vectors to be in a circular shape and use them with a regular ImageView instead.

If you still want to go down that road, creating a custom class extending `AppCompatImageView` should work. Even easier would be using `CircleImageView` as is and set a `Drawable` created by `VectorDrawableCompat.create()`.

**Comment by kaizie** [comment]
Oh, it is a pity to hear that.
Anyway what i actually need to make rounded is a bitmap, but in an intermediate state i display a vector... so i can just call setDisableCircularTransformation() to avoid performance problems and i am good to go :)

Will you anyway extend from AppCompatImageView? Just to know if i have to do it myself or wait for you to update it.

Thanks for your help!

**Comment by hdodenhof** [comment]
That's right. Just make sure to call `setDisableCircularTransformation()` before setting the VectorDrawable to avoid any unnecessary work.

I won't extend from AppCompatImageView as that would make CircleImageView depend on the appcompat library which would increase the footprint of this library quite a bit. And instead of forking I'd still suggest using `VectorDrawableCompat.create()` to load your vector drawables.

**Comment by kaizie** [comment]
Oh right..., i didnt think of the support library dependency.
Ok, i'll do that. Lots of thanks for everything!

**Comment by hdodenhof** [comment]
fyi: I just released v2.1.0 with support for disabling the circular transformation.

**Comment by gowrav** [comment]
@hdodenhof , can you give an example on how to use VectorDrawableCompat.create() to load vector drawables

**Comment by TomerBu** [comment]
@gowrav 
an example: 

`        VectorDrawableCompat drawableCompat = VectorDrawableCompat.create(getResources(), R.drawable.ic_menu_camera, null);
        ImageView iv = new ImageView(getApplicationContext());
        iv.setImageDrawable(drawableCompat);`
