### ISSUE TITLE
when using glide and later set programmatically doesnt show.

### ISSUE THREAD

**Issue by gustavomc** [hdodenhof/CircleImageView#141]
when using glide and it enters in the error part, it loads image correctly, but latter when i try to set imagedrawable programatically image doesnt show, it keeps showing the error image i provided in error of glide.

**Comment by twlk-jzy** [comment]
I also so

**Comment by hdodenhof** [comment]
I don't quite get what's going on here, please provide code samples of what you are doing. Also be aware that you need to disable Glide's animation, more details in the readme.

**Comment by gustavomc** [comment]
i have a CircleImageView

`private CircleImageView mProfliePicture;`

which initialize in onCreate method of my MainActivity

`this.mProfliePicture = (CircleImageView) findViewById(R.id.imagePerson);`

then load an image also in onCreate method of my MainActivity

`GlideUrl glideUrl = new GlideUrl("url"
                .addHeader("Accept", "/")
                .addHeader("Authorization", "Bearer " + MiOficinaApplication.getAccesToken())
                .build());
        Glide.with(this)
                .load(glideUrl)
                .asBitmap()
                .centerCrop()
                .dontAnimate()
                .error(R.drawable.ic_perfildistribuidora_profilepicture)
                .into(this.mProfliePicture);`

then it loads R.drawable.ic_perfildistribuidora_profilepicture because glide url throw an error

` .error(R.drawable.ic_perfildistribuidora_profilepicture)`

everything is ok.

also i have a custom method to set a bitmap image in my CircleImageView

`File filePicture = (File) data.getExtras().get(URI);
Bitmap myBitmap = loadImage(filePicture.getAbsolutePath());
this.mProfliePicture.setImageBitmap(myBitmap);`

when i try to use it, it doesn't work, it keeps showing the error image

**Comment by hdodenhof** [comment]
Alright, that should actually work. Does it work properly when you replace `CircleImageView` with a standard `ImageView`?

**Comment by gustavomc** [comment]
i solved it,
i just put

'Glide.clear(this.mProfliePicture);'

and then assign other resource to my CircleImageView

'this.mProfliePicture.setImageBitmap(myBitmap);'
