### ISSUE TITLE
Set a background color to an image with transparencies

### ISSUE THREAD

**Issue by bryant1410** [hdodenhof/CircleImageView#143]
I see that `setFillColor` is now deprecated. We have been using it to set a color inside the circle to an image which has transparencies. So how can we achieve this now without using the fill color?

**Comment by hdodenhof** [comment]
I actually haven't decided yet and I'm open for ideas. The problem with `setFillColor` is that it seems to really confuse people. I might just end up adding something like `setCircleBackgroundColor`, which  should be more clear.

**Comment by bryant1410** [comment]
Oh, good to know. That name looks good to me.

**Comment by shuv12** [comment]
any solution for this issue?

**Comment by Denny966** [comment]
Any progress on this?

**Comment by shahimclt** [comment]
yup. waiting for this.

**Comment by hdodenhof** [comment]
You can still use `setFillColor` for the time being.

**Comment by rpinto18** [comment]
@hdodenhof 

Solved background color, with help of #64 

```
ColorDrawable  color = new ColorDrawable(randomAndroidColor); // or ContextCompat.getColor(context,R.color.blue)
Drawable image =  ContextCompat.getDrawable(context,R.drawable.transparente);// image transparent
LayerDrawable ld = new LayerDrawable(new Drawable[]{image,color});
imageView.setImageDrawable(ld);
```

**Comment by hdodenhof** [comment]
Version 2.2.0 with `circleBackgroundColor` attribute as replacement for `fillColor` has been released.

**Comment by MohamedISoliman** [comment]
How to use in xml
`      app:civ_circle_background_color="@color/white"
`
