### ISSUE TITLE
the method of placeholder() comes form Glide conflicts with CircleImageView

### ISSUE THREAD

**Issue by gmfbilu** [hdodenhof/CircleImageView#144]
when i use "Glide.with(this).load(url).into(mProfileImage)" it is all ok,but when i add the method of "placeholder(R.drawable.error)"  into my code, the mProfileImage is alwaws display the image with R.drawable.error instead of the image from url.``

**Comment by hdodenhof** [comment]
If you want to use "placeholder()" you have to load the image into a custom target and update the ImageView manually, have a look at https://github.com/hdodenhof/CircleImageView/issues/57#issuecomment-103478100 for how to do that. This is a known limitation when combining this library with Glide.

**Comment by gmfbilu** [comment]
thanks , i got it!
