### ISSUE TITLE
Glide doesn't work at CircleImageView in the first time!

### ISSUE THREAD

**Issue by chi5hao** [hdodenhof/CircleImageView#145]
as title say~,
but if I open a new Activity, and back, It works~  that is weird~

**Comment by thphuc** [comment]
@chi5hao Did you solve this issue?

**Comment by hdodenhof** [comment]
@thphuc: from the README:

> If you use an image loading library like Picasso or Glide, you need to disable their fade animations to avoid messed up images. For Picasso use the noFade() option, for Glide use dontAnimate(). If you want to keep the fadeIn animation, you have to fetch the image into a Target and apply a custom animation yourself when receiving the Bitmap.

Also #57.

**Comment by thphuc** [comment]
Thanks @hdodenhof

**Comment by xuze1992** [comment]
Thanks @hdodenhof

**Comment by katepratik** [comment]
#192 

Found a fix to load Image using glide.
```
Glide.with(context)
                .load(imageLink)
                .asBitmap()
                .dontAnimate()
                .placeholder(R.drawable.user)
                .listener(new RequestListener<String, Bitmap>() {
           @Override
            public boolean onException(Exception e, String s, Target<Bitmap> target, boolean b) {
                return false;
            }
            @Override
            public boolean onResourceReady(Bitmap bitmap, String s, Target<Bitmap> target, boolean b, boolean b1) {
                userImage.setImageBitmap(bitmap);
                return false;
            }
        }).preload();
```
Load bitmap after you get it instead of using into(imageview) method of Glide.
Don't forget Magic line inside onResourceReady : **circleImageView.setImageBitmap(bitmap);**

**Comment by ZackLee** [comment]
Thanks @hdodenhof
