### ISSUE TITLE
java.lang.IllegalArgumentException: width and height must be > 0

### ISSUE THREAD

**Issue by MIkeeJY** [hdodenhof/CircleImageView#150]
```
java.lang.IllegalArgumentException: width and height must be > 0
    at android.graphics.Bitmap.createBitmap(Bitmap.java:810)
    at android.graphics.Bitmap.createBitmap(Bitmap.java:789)
    at android.graphics.Bitmap.createBitmap(Bitmap.java:756)
    at com.xx.view.MyCircleView.getBitmapFromDrawable(MyCircleView.java:325)
    at com.xx.view.MyCircleView.initializeBitmap(MyCircleView.java:342)
    at com.xx.view.MyCircleView.setImageDrawable(MyCircleView.java:273)
    at com.nostra13.universalimageloader.core.imageaware.ImageViewAware.setImageDrawableInto(ImageViewAware.java:118)
    at com.nostra13.universalimageloader.core.imageaware.ViewAware.setImageDrawable(ViewAware.java:150)
    at com.nostra13.universalimageloader.core.display.RoundedBitmapDisplayer.display(RoundedBitmapDisplayer.java:61)
    at com.nostra13.universalimageloader.core.ImageLoader.displayImage(ImageLoader.java:282)
    at com.nostra13.universalimageloader.core.ImageLoader.displayImage(ImageLoader.java:209)
    at com.nostra13.universalimageloader.core.ImageLoader.displayImage(ImageLoader.java:410)
    at com.nostra13.universalimageloader.core.ImageLoader.displayImage(ImageLoader.java:385)
```

```
            if (drawable instanceof ColorDrawable) {
                bitmap = Bitmap.createBitmap(COLORDRAWABLE_DIMENSION, COLORDRAWABLE_DIMENSION, BITMAP_CONFIG);
            } else {
                bitmap = Bitmap.createBitmap(drawable.getIntrinsicWidth(), drawable.getIntrinsicHeight(), BITMAP_CONFIG);
            }
```

java.lang.IllegalArgumentException: width and height must be > 0
This code got the exception when I used imageloader..

**Comment by MIkeeJY** [comment]
.showImageOnLoading(R.drawable.icon_default)
                    .showImageForEmptyUri(R.drawable.icon_default)
                    .showImageOnFail(R.drawable.icon_default)
                    .resetViewBeforeLoading(false)
                    .imageScaleType(ImageScaleType.EXACTLY_STRETCHED)
                    .bitmapConfig(Bitmap.Config.RGB_565).build();


imageloader  default  icon "R.drawable.icon_default"   is  .9.png,but not always show this exception...

**Comment by MIkeeJY** [comment]
I guess this might cause by NinePatchDrawable which occurs this error...

**Comment by MIkeeJY** [comment]
So I found the solution:     
   try {
            Bitmap bitmap = null;

            if (drawable instanceof ColorDrawable) {
                bitmap = Bitmap.createBitmap(COLORDRAWABLE_DIMENSION, COLORDRAWABLE_DIMENSION, BITMAP_CONFIG);
            } else if (drawable instanceof NinePatchDrawable) {
                bitmap = Bitmap
                        .createBitmap(
                                drawable.getIntrinsicWidth(),
                                drawable.getIntrinsicHeight(),
                                drawable.getOpacity() != PixelFormat.OPAQUE ? Bitmap.Config.ARGB_8888
                                        : Bitmap.Config.RGB_565);
                Canvas canvas = new Canvas(bitmap);
                drawable.setBounds(0, 0, drawable.getIntrinsicWidth(),
                        drawable.getIntrinsicHeight());
                drawable.draw(canvas);

            } else {
                bitmap = Bitmap.createBitmap(drawable.getIntrinsicWidth(), drawable.getIntrinsicHeight(), BITMAP_CONFIG);
            }

            Canvas canvas = new Canvas(bitmap);
            drawable.setBounds(0, 0, canvas.getWidth(), canvas.getHeight());
            drawable.draw(canvas);
            return bitmap;
        } catch (Exception e) {
            e.printStackTrace();
            return null;
        }

**Comment by MIkeeJY** [comment]
maybe this way is the best solution...

      viewHolder.iv_user_head.post(new Runnable() {
            @Override
            public void run() {

            }
        });

**Comment by r9software** [comment]
I have the same issue @MIkeeJY  happening on
View view = LayoutInflater.from ( parent.getContext ( ) )
																.inflate ( R.layout.recycler_view_home_team_item, parent, false );
Where home_team_item has Circle views with drawable shape files.

**Comment by MIkeeJY** [comment]
@r9software At last,I use glide not imageloader...

**Comment by pineshmenat** [comment]
<activity android:name=".controllers.activities.MainActivity"
            android:windowSoftInputMode="adjustPan" >
        </activity>


Just add this to manifest file, This error occurs because view shrinks on click of EditText if you have in your layout due to popup keyboard opens up
