### ISSUE TITLE
Image not visible - Google Play for Games avatar

### ISSUE THREAD

**Issue by mobeela** [hdodenhof/CircleImageView#151]
I am trying to show Google Play for Games player avatar in circle image view. Unfortunately, the image is not shown when I try to use this library (path is Uri).

I used both, Picasso and ImageManager (Google API) - same result.

Any advices?

**Comment by hdodenhof** [comment]
From the Readme:
> If you use an image loading library like Picasso or Glide, you need to disable their fade animations to avoid messed up images. For Picasso use the `noFade()` option, for Glide use `dontAnimate()`. If you want to keep the fadeIn animation, you have to fetch the image into a `Target` and apply a custom animation yourself when receiving the `Bitmap`.

I haven't used `ImageManager` but it's probably a similar issue. You should be able to use `loadImage (ImageManager.OnImageLoadedListener listener, Uri uri)` and set the drawable manually in the listeners `onImageLoaded (Uri uri, Drawable drawable)`.

**Comment by mobeela** [comment]
Thank you for your answer. It worked perfect. Didn't check the alternative methods to load the drawable.
