### ISSUE TITLE
Selector bounded to a circle

### ISSUE THREAD

**Issue by lawloretienne** [hdodenhof/CircleImageView#153]
If I try to add this attribute
`android:foreground="?android:attr/selectableItemBackground"`
to a `CircleImageView` then when I click on the view the ripple is bounded to a square instead of a circle.  How can you change that behavior?

**Comment by hdodenhof** [comment]
You need to create your own selector drawable to mask that ripple effect.
Something like this (untested):

```
<de.hdodenhof.circleimageview.CircleImageView
    android:layout_width="128dp"
    android:layout_height="128dp"
    android:src="@drawable/foobar"
    android:foreground="@drawable/my_selector"
    android:clickable="true"/>
```

drawable-v21/my_selector.xml:
```
<?xml version="1.0" encoding="utf-8"?>
<ripple xmlns:android="http://schemas.android.com/apk/res/android"
        android:color="?attr/colorControlHighlight">
    <item android:id="@android:id/mask">
        <shape android:shape="oval">
            <solid android:color="#ffffff"/>
        </shape>
    </item>
</ripple>
```

drawable/my_selector.xml:
```
<?xml version="1.0" encoding="utf-8"?>
<selector xmlns:android="http://schemas.android.com/apk/res/android">
    <item android:drawable="@drawable/circle" android:state_pressed="true"/>
    <item android:drawable="@android:color/transparent"/>
</selector>
```

drawable/circle.xml:
```
<?xml version="1.0" encoding="utf-8"?>
<shape xmlns:android="http://schemas.android.com/apk/res/android"
       android:shape="oval">
    <solid android:color="?attr/colorControlHighlight"/>
</shape>
```

**Comment by raiarainne** [comment]
Thank you for great Great solution.
It is very helpful for me.
Best Regards.

**Comment by idedalusse** [comment]
Hi, I have a problem with the following message
java.lang.ClassCastException: androidx.constraintlayout.widget.ConstraintLayout cannot be cast to androidx.core.widget.NestedScrollView

i am in androidx
