### ISSUE TITLE
ImageView border not appearing in design view.

### ISSUE THREAD

**Issue by fermatijoe** [hdodenhof/CircleImageView#154]
Hello. I wanted to report that the view's border is not visible if previewed in the design tab of Android Studio 2.2. The view works fine in devices.

**Comment by hdodenhof** [comment]
It actually works for me in AS 2.2. Can you provide more details and try with the sample project?

**Comment by fermatijoe** [comment]
Don't really know what to add. The preview works (it shows the image) but the circle around it is not visible. If I launch the app without chaning any code it is visible.

[screen](http://imgur.com/a/bi4v0)

[source code](https://github.com/fermatijoe/shows2/blob/master/app/src/main/res/layout/fragment_detail_person.xml#L73)

Right now I set it white since I like it more.

**Comment by siaLp** [comment]
i can not set border for my image in this component when i used it in navigation drawer

**Comment by hdodenhof** [comment]
I haven't had any issue like that with any version of Android Studio. Upgrading AS to the latest version and cleaning the project should solve problems like this. Closing this as there's no issue with the library itself.
