### ISSUE TITLE
About setImageBitmap()  black is displayed 

### ISSUE THREAD

**Issue by wkchen66** [hdodenhof/CircleImageView#159]
about setImageBitmap()  black is displayed outside the circle

bitmap from glide target

**Comment by wkchen66** [comment]
Glide.with(getApplication())
                        .load(smallUrl)
                        .asBitmap()
                        .placeholder(R.drawable.ic_default_head)
                        .diskCacheStrategy(DiskCacheStrategy.ALL)//缓存
                        .into(new SimpleTarget<Bitmap>(width, height) {
                            @Override
                            public void onResourceReady(Bitmap bitmap, GlideAnimation anim) {
                                 mCivMarker.setImageDrawable(markerBitmap);
 }

**Comment by davidgerka** [comment]
@wkchen66 hello,I also appear this kind of situation, do you have a solution,Thanks

**Comment by SametAlbayrak** [comment]
Also me too have this problem, the solution isn't found yet?

**Comment by hdodenhof** [comment]
Duplicate of #127.
