### ISSUE TITLE
Android Studio Preview Error Message

### ISSUE THREAD

**Issue by bennettl** [hdodenhof/CircleImageView#161]
Running Android studio 2.2.1, every time i update the XML layout i see this error message pop up.
![screen shot 2016-10-23 at 2 30 41 pm](https://cloud.githubusercontent.com/assets/1672224/19629609/68344646-992d-11e6-890b-3d6b8e6b9983.png)

**Comment by JigneshPatel-STL** [comment]
@hdodenhof any plan for this?

**Comment by hdodenhof** [comment]
That's most likely a configuration issue with your projects, this library works fine in the layout preview. Please double check and also try out if you have the same issues with the sample app.
