### ISSUE TITLE
Make a drawable Border (gradient, for example)

### ISSUE THREAD

**Issue by renanbandeira** [hdodenhof/CircleImageView#162]
Hi,

I'm thinking about using your lib, but I want to create a CircleImageView with a gradient border. Is this possible? AFAIK, the border_color property from CircleImageView just accepts colors, not drawables.

Thanks

**Comment by hdodenhof** [comment]
This is currently not possible and there are no plans to support anything else than colors for the border as that seems to be a very rare edge case.
