### ISSUE TITLE
Support VectorDrawable not supported yet?

### ISSUE THREAD

**Issue by ramonrabello** [hdodenhof/CircleImageView#166]
I tried to use a vector drawable (with support enabled) using the following code:

` <de.hdodenhof.circleimageview.CircleImageView
                android:id="@+id/profile_image"
                android:layout_width="150dp"
                android:layout_height="150dp"
                app:srcCompat="@drawable/ic_vector_drawable" />`

But the background becomes totally white. Do vector drawables are not supported yet?

**Comment by hdodenhof** [comment]
Please have a look at #122 and #138 for the state of vector drawable support.

**Comment by ramonrabello** [comment]
Thanks for the quick reply @hdodenhof . I'll follow your sugestions!
