### ISSUE TITLE
 Resources$NotFoundException.

### ISSUE THREAD

**Issue by h8452763** [hdodenhof/CircleImageView#168]
I am trying to load a vector drawable (loading with app:srcCompat="@mipmap/xxx") and I am getting Resources$NotFoundException.

**Comment by xliu11** [comment]
http://www.jianshu.com/p/313912ff2f37 @h8452763

**Comment by h8452763** [comment]
thanks

**Comment by hdodenhof** [comment]
Please have a look at #122 and #138 for the state of vector drawable support.
