### ISSUE TITLE
Glide .placeholder() the animation does not work

### ISSUE THREAD

**Issue by ant-ia** [hdodenhof/CircleImageView#170]
Hi,
I have a CircleImageView

`image  = (CircleImageView) findViewById(R.id.imager);`

when i try to load an image, the placeHolder animation not wok.
(I have already tested with `ImageView` and it works perfectly)

`            Glide.with(this)
                    .load(picture)
                    .asBitmap()
                    .placeholder(R.drawable.progress_animation)
                    .centerCrop()
                    .into(image);
`

What do you advise me to do for this problem?
Thanks.

**Comment by hdodenhof** [comment]
There are several issues discussing this topic, the solution from https://github.com/hdodenhof/CircleImageView/issues/57#issuecomment-103478100 should work for you.

**Comment by ant-ia** [comment]
The solutions that you posted, do not work for me. I think that the problem is not the same. The load is the placeholder, both the image is successful. It is successful the replace. What does not work, it is that I can not see the animation of the placeholder while loading the image.

**Comment by ant-ia** [comment]
Exactly, I solved the problem by doing as you said. It works perfectly.
**Thanks for the support.**

**Comment by hdodenhof** [comment]
Sweet, happy to help!
