### ISSUE TITLE
Cannot set elevation

### ISSUE THREAD

**Issue by subediaayush** [hdodenhof/CircleImageView#174]
No shadow is seen when setting elevation with the view. Is there an workaround?

**Comment by hdodenhof** [comment]
For elevation to work a `View` has to provide a `ViewOutlineProvider`. Until there is built-in support you could do something like that:
```
CircleImageView civ = [..]
civ.setOutlineProvider(new CircleImageViewOutlineProvider(civ));

...

public class CircleImageViewOutlineProvider extends ViewOutlineProvider {

    private CircleImageView mCiv;

    public CircleImageViewOutlineProvider(CircleImageView civ) {
        mCiv = civ;
    }

    @Override
    public void getOutline(View view, Outline outline) {
        Rect bounds = calculateBounds();
        outline.setRoundRect(bounds, bounds.width() / 2);
    }

    private Rect calculateBounds() {
        int availableWidth = mCiv.getWidth() - mCiv.getPaddingLeft() - mCiv.getPaddingRight();
        int availableHeight = mCiv.getHeight() - mCiv.getPaddingTop() - mCiv.getPaddingBottom();

        int sideLength = Math.min(availableWidth, availableHeight);

        int left = mCiv.getPaddingLeft() + (int) ((availableWidth - sideLength) / 2f);
        int top = mCiv.getPaddingTop() + (int) ((availableHeight - sideLength) / 2f);

        return new Rect(left, top, left + sideLength, top + sideLength);
    }
}
```

**Comment by subediaayush** [comment]
By until there is built in support, do you mean android does not provide custom outline for custom views?

**Comment by hdodenhof** [comment]
Android cannot provide the outline for custom views as only the view itself knows about the correct shape -
 using `setOutlineProvider` is the way to define that shape.

What I meant was that the above snippet might at some point be built into `CircleImageView`.

**Comment by subediaayush** [comment]
Thanks for the input. I will try out your suggestion

**Comment by vit001** [comment]
Thanks for the code snippet, but for me this doesn't work. The shadow gets fully obscured by the circular image...

**Comment by hdodenhof** [comment]
@vit001: the calculation is correct. I'm working on moving it into the library - look at the `feature/outline-provider`. Adding `android:elevation` to the sample app layout there works as expected.

**Comment by hdodenhof** [comment]
I'll keep this issue open until the `ViewOutlineProvider` support has been merged into `master`.

**Comment by hdodenhof** [comment]
Version 2.2.0 with support for elevation has been released.
