### ISSUE TITLE
Imageview cannot show in circle shape

### ISSUE THREAD

**Issue by clementf2b** [hdodenhof/CircleImageView#175]
```
        <de.hdodenhof.circleimageview.CircleImageView
            android:id="@+id/profile_picture"
            android:layout_width="100dp"
            android:layout_height="100dp"
            android:layout_marginBottom="25dp"
            android:layout_marginLeft="20dp"
            android:layout_marginTop="25dp"
            android:background="@mipmap/app_icon"
            android:elevation="6dp" />
```
   

             compile 'de.hdodenhof:circleimageview:2.1.0'

![screen shot 2017-02-04 at 10 34 41 am](https://cloud.githubusercontent.com/assets/9070390/22614955/8d738392-eac5-11e6-8f0f-06fcc59eaea5.png)

I don't know why the imageview become a square image. Any solution for me? Thank you.

**Comment by hardikwingify** [comment]
You should set app icon to ImageView as source rather than setting as a background
