### ISSUE TITLE
Very very slow and laggy

### ISSUE THREAD

**Issue by r0b1n1sl4m** [hdodenhof/CircleImageView#176]
Works fine as expected but very very slow while using inside material tabs fragment.

**Comment by hdodenhof** [comment]
Is this related to #177?

**Comment by r0b1n1sl4m** [comment]
yes This issue should be solve by putting images inside drawable-hdpi or equ folder

**Comment by hdodenhof** [comment]
Alright, I'll close this then. Thanks!

**Comment by jasoncheng911** [comment]
@r0b1n1sl4m So, what is your problem solved?

**Comment by r0b1n1sl4m** [comment]
yes "should be solve by putting images inside drawable-hdpi or equ folder" this solved my problem :)

**Comment by dimitrileite** [comment]
This issue is solved if CircleImageView extends android.support.v7.widget.AppCompatImageView instead of Image.
