### ISSUE TITLE
Memory leaks while using CircleImageView with FragmentPagerAdapter

### ISSUE THREAD

**Issue by r0b1n1sl4m** [hdodenhof/CircleImageView#177]
I'm using FragmentPagerAdapter in my android project and everything works pretty fine. In the profile page I want to show circle image using CircleImageView library. ViewPager works fine while using normal image but when I'm using CircleImageView code then every time I slide pager it increase memory consumption. I tried it on a phone which have 3 gb of ram and within few slide it's getting out of memory. Someone please help me how to fix that. I want to use the library but not with memory issue. Here is my codes below.
more: http://stackoverflow.com/questions/42097292/memory-leaks-while-using-circleimageview-with-fragmentpageradapter

**Comment by hdodenhof** [comment]
Closing this, SO thread has details about the root issue and a solution.
