### ISSUE TITLE
Caused by: java.lang.IllegalArgumentException: ScaleType CENTER_INSIDE not supported.

### ISSUE THREAD

**Issue by iman2420** [hdodenhof/CircleImageView#178]
When i use `android:scaleType="centerInside"` my app will crash!!! Why?

                `<de.hdodenhof.circleimageview.CircleImageView
                android:id="@+id/action1"
                android:layout_width="60dp"
                android:layout_height="60dp"
                android:layout_marginRight="10dp"
                android:scaleType="centerInside"
                android:paddingRight="10dp"
                android:src="@mipmap/ic_conversation"
                app:civ_border_color="@android:color/white"
                app:civ_border_width="1dp" />`

**Caused by: java.lang.IllegalArgumentException: ScaleType CENTER_INSIDE not supported.**

**Comment by yunmenggyy** [comment]
can you track the source code to solve it ?

**Comment by binaryKarmic** [comment]
Its already mentioned.

> Limitations
The ScaleType is always CENTER_CROP and you'll get an exception if you try to change it. This is (currently) by design as it's perfectly fine for profile images.

**Comment by hdodenhof** [comment]
The exception message should be self-explanatory. Limited ScaleType support is by design - look at #164 for how to enable it in a custom build of this library.
