### ISSUE TITLE
ListView not showing image from URL on initial list load but only when items are scrolled of and on the screen

### ISSUE THREAD

**Issue by theeasylearn** [hdodenhof/CircleImageView#180]
we have used this library in customlistview loading Image from URL but problem is ListView not showing image from URL on initial list load but only when items are scrolled of and on the screen. 

we have figure out that this issue can be solved if you replace ImageView with NetworkImageView in CircleImageView.java.

please update code do reply on ankit3385@gmail.com

**Comment by hdodenhof** [comment]
`NetworkImageView` is not part of the Android framework so that's not a general solution I'm going to apply. I guess your issue is related to view recycling but you need to provide code extracts for proper analysis.
