### ISSUE TITLE
add CircleImageView programmatically

### ISSUE THREAD

**Issue by clementf2b** [hdodenhof/CircleImageView#186]
How can I create the white border and the circleimageview programmatically? Thank you.

                 <de.hdodenhof.circleimageview.CircleImageView
                    android:id="@+id/product_color_1"
                    android:layout_width="38dp"
                    android:layout_height="38dp"
                    android:layout_margin="5dp"
                    android:src="@color/gradient_end"
                    app:civ_border_color="@color/profile_edit_bg"
                    app:civ_border_width="1dp"/>

I would like to create the CircleImageView programmatically.
The following is the code that I tried

                        de.hdodenhof.circleimageview.CircleImageView iv = new de.hdodenhof.circleimageview.CircleImageView(getApplicationContext());
                        LinearLayout colorLayout = (LinearLayout)findViewById(R.id.product_add_color_layout);
                        // Set an image for ImageView
                        RelativeLayout.LayoutParams buttonParam = new RelativeLayout.LayoutParams(
                                100,
                                100);
                        iv.setLayoutParams(buttonParam);
                        iv.setBackgroundResource(R.mipmap.app_icon);
                        iv.setPadding(5,5,5,5);
                        iv.setBackgroundColor(Color.parseColor(product_data_one.getColor().get(i)));
                        iv.setBorderColor(0xE0E0E0);
                        iv.setBorderWidth(10);
                        colorLayout.addView(iv);

**Comment by hdodenhof** [comment]
You have to use `setImageResource` instead of `setBackgroundResource`. Also the parameter for `setBorderColor` should be `Color.parseColor("#E0E0E0")`.

**Comment by clementf2b** [comment]
If I want to directly insert a color instead of setting a image, how can I do it? Thanks

**Comment by hdodenhof** [comment]
`setImageResource(R.color.foobar)` or `setImageDrawable(new ColorDrawable(Color.parseColor("#ABCDEF")))`.

**Comment by clementf2b** [comment]
ok Thanks
