### ISSUE TITLE
Default Image not display When app run on mobile following codes are used

### ISSUE THREAD

**Issue by rahulwadhai** [hdodenhof/CircleImageView#189]
<?xml version="1.0" encoding="utf-8"?>
<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:background="@color/colorWhite"
    android:orientation="vertical">

    <com.habron.habronretail.view.RevealBackgroundView
        android:id="@+id/vRevealBackground"
        android:layout_width="match_parent"
        android:layout_height="match_parent" />

    <android.support.design.widget.CoordinatorLayout
        android:id="@+id/content"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:layout_alignParentLeft="true"
        android:layout_alignParentStart="true"
        android:layout_alignParentTop="true"
        android:orientation="vertical">

        <android.support.v4.view.ViewPager
            android:id="@+id/pager"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            app:layout_behavior="@string/appbar_scrolling_view_behavior" />

        <android.support.design.widget.AppBarLayout
            android:id="@+id/appBarLayout"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:background="@android:color/transparent"
            android:theme="@style/ThemeOverlay.AppCompat.Dark.ActionBar">

            
            
            
            

            <android.support.design.widget.CollapsingToolbarLayout
                android:id="@+id/collapsing_toolbar"
                android:layout_width="match_parent"
                android:layout_height="match_parent"
                app:contentScrim="?attr/colorPrimary"
                app:layout_scrollFlags="scroll|exitUntilCollapsed">

                
                
                
                
                
                
                

                <LinearLayout
                    android:id="@+id/vUserProfileRoot"
                    android:layout_width="match_parent"
                    android:layout_height="wrap_content"
                    android:background="?attr/colorPrimary"
                    android:clipChildren="false"
                    android:clipToPadding="false"
                    android:orientation="vertical"
                    android:paddingBottom="10dp"
                    android:paddingLeft="24dp"
                    android:paddingRight="24dp"
                    android:paddingTop="64dp"
                    app:layout_collapseMode="parallax">

                    <LinearLayout
                        android:layout_width="match_parent"
                        android:layout_height="wrap_content"
                        android:clipChildren="false">

                        <RelativeLayout
                            android:layout_width="88dp"
                            android:layout_height="88dp">

                            <de.hdodenhof.circleimageview.CircleImageView
                                android:id="@+id/circularImageView_Id"
                                android:layout_width="88dp"
                                android:layout_height="88dp"
                                android:layout_gravity="center_horizontal"
                                android:layout_margin="10dp"
                                android:src="@drawable/ic_no_image"
                                app:civ_border_color="@android:color/white"
                                app:civ_border_width="2dp"
                                app:finalHeight="@dimen/image_final_width"
                                app:finalYPosition="2dp"
                                app:layout_behavior="com.example.test.utils.AvatarImageBehavior"
                                app:startHeight="2dp"
                                app:startToolbarPosition="2dp"
                                app:startXPosition="2dp" />

                        </RelativeLayout>

                        <LinearLayout
                            android:id="@+id/vUserDetails"
                            android:layout_width="wrap_content"
                            android:layout_height="wrap_content"
                            android:layout_weight="1"
                            android:orientation="vertical">

                            <TextView
                                android:id="@+id/textViewUserfullname_id"
                                android:layout_width="match_parent"
                                android:layout_height="wrap_content"
                                android:text="John Smith"
                                android:textColor="#ffffff"
                                android:textSize="24sp" />

                            <TextView
                                android:id="@+id/textViewEmail_id"
                                android:layout_width="match_parent"
                                android:layout_height="wrap_content"
                                android:text="\@jsmith"
                                android:textColor="#bbbbbb"
                                android:textSize="12sp" />

                            <TextView
                                android:id="@+id/textViewCompanyName_id"
                                android:layout_width="match_parent"
                                android:layout_height="wrap_content"
                                android:text="Mobile development passionate."
                                android:textColor="#ffffff"
                                android:textSize="12sp" />

                            <Button
                                android:id="@+id/btnFollow"
                                android:layout_width="match_parent"
                                android:layout_height="24dp"
                                android:layout_marginRight="24dp"
                                android:layout_marginTop="8dp"
                                android:text="following"
                                android:textColor="#ffffff"
                                android:textSize="12sp"
                                android:visibility="gone" />

                        </LinearLayout>
                    </LinearLayout>

                    <LinearLayout
                        android:id="@+id/vUserStats"
                        android:layout_width="match_parent"
                        android:layout_height="wrap_content"
                        android:layout_marginLeft="16dp"
                        android:layout_marginRight="16dp"
                        android:layout_marginTop="5dp">

                        <LinearLayout
                            android:layout_width="wrap_content"
                            android:layout_height="wrap_content"
                            android:layout_weight="1"
                            android:gravity="center"
                            android:orientation="vertical">

                            <TextView
                                android:id="@+id/textViewMenuCount_id"
                                android:layout_width="wrap_content"
                                android:layout_height="wrap_content"
                                android:text="0"
                                android:textColor="#ffffff"
                                android:textSize="20sp" />

                            <TextView
                                android:layout_width="wrap_content"
                                android:layout_height="wrap_content"
                                android:text="Menus"
                                android:textColor="#ffffff"
                                android:textSize="12sp" />
                        </LinearLayout>

                        <LinearLayout
                            android:layout_width="wrap_content"
                            android:layout_height="wrap_content"
                            android:layout_weight="1"
                            android:gravity="center"
                            android:orientation="vertical">

                            <TextView
                                android:id="@+id/textViewInHouseAppCount_id"
                                android:layout_width="wrap_content"
                                android:layout_height="wrap_content"
                                android:text="0"
                                android:textColor="#ffffff"
                                android:textSize="20sp" />

                            <TextView
                                android:layout_width="wrap_content"
                                android:layout_height="wrap_content"
                                android:text="InHouseApp"
                                android:textColor="#ffffff"
                                android:textSize="12sp" />
                        </LinearLayout>

                        <LinearLayout
                            android:layout_width="wrap_content"
                            android:layout_height="wrap_content"
                            android:layout_weight="1"
                            android:gravity="center"
                            android:orientation="vertical">

                            <TextView
                                android:id="@+id/textViewCustomerAppCount_id"
                                android:layout_width="wrap_content"
                                android:layout_height="wrap_content"
                                android:text="0"
                                android:textColor="#ffffff"
                                android:textSize="20sp" />

                            <TextView
                                android:layout_width="wrap_content"
                                android:layout_height="wrap_content"
                                android:text="CustomerApp"
                                android:textColor="#ffffff"
                                android:textSize="12sp" />
                        </LinearLayout>
                    </LinearLayout>

                </LinearLayout>

                <android.support.v7.widget.Toolbar
                    android:id="@+id/toolbar"
                    android:layout_width="match_parent"
                    android:layout_height="?attr/actionBarSize"
                    android:background="@color/colorOlive">

                    <RelativeLayout
                        android:layout_width="match_parent"
                        android:layout_height="wrap_content">

                        <TextView
                            android:id="@+id/textView29"
                            android:layout_width="wrap_content"
                            android:layout_height="wrap_content"
                            android:gravity="center_horizontal"
                            android:text="@string/action_my_profile"
                            android:textColor="@color/colorWhite"
                            android:textSize="16sp"
                            android:textStyle="bold" />

                    </RelativeLayout>

                    <android.support.v7.widget.SwitchCompat
                        android:id="@+id/switchCompatCheckConnection_Id"
                        android:layout_width="100dp"
                        android:layout_height="wrap_content"
                        android:layout_gravity="end"
                        android:layout_marginEnd="10dp"
                        android:layout_marginRight="10dp"
                        android:scaleX="1.2"
                        android:scaleY="1.2"
                        android:switchMinWidth="70dp"
                        android:textOff="@string/text_switch_button_local"
                        android:textOn="@string/text_switch_button_internet"
                        android:theme="@style/SwitchCompat"
                        android:thumbTextPadding="25dp"
                        app:showText="true" />

                </android.support.v7.widget.Toolbar>

            </android.support.design.widget.CollapsingToolbarLayout>

            <FrameLayout
                android:layout_width="match_parent"
                android:layout_height="40dp"
                android:layout_marginTop="10dp">

                <android.support.design.widget.TabLayout
                    android:id="@+id/tabLayout_UserProfileTabs_id"
                    android:layout_width="match_parent"
                    android:layout_height="40dp"
                    android:background="#ffffff"
                    app:tabGravity="fill"
                    app:tabIndicatorColor="@color/colorOlive"
                    app:tabIndicatorHeight="4dp"
                    app:tabMode="fixed" />

            </FrameLayout>

        </android.support.design.widget.AppBarLayout>

        <android.support.design.widget.FloatingActionButton
            android:id="@+id/floatingButtontakepic_Id"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_alignParentBottom="true"
            android:layout_alignParentRight="true"
            android:layout_gravity="bottom|right"
            android:layout_marginBottom="@dimen/btn_fab_margins"
            android:layout_marginRight="@dimen/btn_fab_margins"
            android:src="@drawable/ic_instagram_white"
            app:borderWidth="0dp"
            app:elevation="6dp"
            app:pressedTranslationZ="12dp" />
    </android.support.design.widget.CoordinatorLayout>
</RelativeLayout>

**Comment by rahulwadhai** [comment]
I got it Solved

**Comment by iamshadmirza** [comment]
How?
same problem here.
I can see the image in preview pane but on Android device.
