### ISSUE TITLE
Not compatible with Glide 

### ISSUE THREAD

**Issue by katepratik** [hdodenhof/CircleImageView#192]
Hey!

The lib has some issue if we use glide to load the image into the circle imageview of yours. Please come up with a temp quick fix and solve in your next update.

**Comment by hdodenhof** [comment]
Please have a look at the README for limitations of this library as well as existing issues regarding Glide. If your problem is not covered add more details about what you are trying to do and what the actual issue is. Closing this for now as I assume we're talking about some known limitation.

**Comment by cumtsx** [comment]
Hi,may you tell me the reason of the limitation:"Using a TransitionDrawable with CircleImageView doesn't work properly and leads to messed up images."?Thanks a lot.

**Comment by wonsuc** [comment]
Exactly, this library is not compatible with Glide's this method. I don't know if it's because of "crossFade()" option of Glide.

```
@Override
public Target<GlideDrawable> into(ImageView view) {
    return super.into(view);
}
```

**Comment by katepratik** [comment]
Found a fix to load Image using glide. @hdodenhof please share it in your instruction for others.

`Glide.with(context)
                .load(imageLink)
                .asBitmap()
                .dontAnimate()
                .placeholder(R.drawable.user).listener(new RequestListener<String, Bitmap>() {
            @Override
            public boolean onException(Exception e, String s, Target<Bitmap> target, boolean b) {
                return false;
            }

            @Override
            public boolean onResourceReady(Bitmap bitmap, String s, Target<Bitmap> target, boolean b, boolean b1) {
                **circleImageView.setImageBitmap(bitmap);**
                return false;
            }
        }).preload();`

**Comment by katepratik** [comment]
Found a fix to load Image using glide. @hdodenhof please share it in your instruction for others.

`Glide.with(context)
                .load(imageLink)
                .asBitmap()
                .dontAnimate()
                .placeholder(R.drawable.user)
                .listener(new RequestListener<String, Bitmap>() {
            @Override
            public boolean onException(Exception e, String s, Target<Bitmap> target, boolean b) {
                return false;
            }
            @Override
            public boolean onResourceReady(Bitmap bitmap, String s, Target<Bitmap> target, boolean b, boolean b1) {
                userImage.setImageBitmap(bitmap);
                return false;
            }
        }).preload();`

Load bitmap after you get it instead of using into(imageview) method of Glide.
Don't forget Magic line inside onResourceReady : **circleImageView.setImageBitmap(bitmap);**

**Comment by hdodenhof** [comment]
@katepratik: this exact case is part of the "Limitations" section of the Readme, which I referred you to. It is also explained in all the issues you linked. Please don't spam all issues related to Glide with this.

**Comment by katepratik** [comment]
@hdodenhof I just have given a solution to your so called "Limitations" with Glide!

**Comment by hdodenhof** [comment]
The solution is also part of that section: "[..] for Glide use dontAnimate(). If you want to keep the fadeIn animation, you have to fetch the image into a Target and apply a custom animation yourself when receiving the Bitmap". I will not add a copy-and-paste template though.
