### ISSUE TITLE
OnClickListener don't work

### ISSUE THREAD

**Issue by Joerli** [hdodenhof/CircleImageView#196]
Hi;
I need the onclick event but it is not working.

Is there any way to implement?

I tried the code below.

`CircleImageView img  = (CircleImageView) findViewById(R.id.img);`
`img.setClickable(true);`
`img.setOnClickListener( new Button.OnClickListener() {`
`           @Override`
`            public void onClick(View v) {`
`                Toast.makeText( ACPrincipal.this,`
`                        "The favorite list would appear on clicking this icon".`
`                        Toast.LENGTH_LONG).show();`
`            }`
`        });`

Thanks

**Comment by AEfremov** [comment]
Remove img.setClickable(true);

**Comment by mojakker** [comment]
Still not working ! any suggestion ?

**Comment by Joerli** [comment]
Yes, it worked. Thank you very much
