### ISSUE TITLE
Laggy or Crash in drawerlayout

### ISSUE THREAD

**Issue by youyuge34** [hdodenhof/CircleImageView#198]
```
<android.support.design.widget.NavigationView
            android:id="@+id/nav_view"
            android:layout_width="260dp"
            android:layout_height="match_parent"
            android:layout_gravity="start"
            app:headerLayout="@layout/nav_header"
            app:menu="@menu/nav_menu" />
```

And i put the CircleImageView  in the @layout/nav_header as below

```
<de.hdodenhof.circleimageview.CircleImageView
        android:id="@+id/image"
        android:layout_width="70dp"
        android:layout_height="70dp"
        android:layout_centerInParent="true"
        android:src="@drawable/icon_image" />
```

When the resource image is 1000*1000 in pixels and 500KB in size, the drawerlayout becomes quite unstable when opening.

In nexus5 virtual device (api 23)and some real devices(api 18),it becomes quite laggy and slow.

Even running in MEIZU MX3 device(api 21),it cannot show the picture correctly,just black.After some seconds,it will be killed by system because its high memory size cost.

At last , i replaced the drawable resource with a picture which is 200 * 200 in pixels and 20KB in size,the drawerlayout works pretty well.

I saw someone else has reported the issue, but he didn't tell the details.So i hope such info may help u to solve the problem.

ps:thanks a lot for updating CircleImageView poject!

**Comment by MattS8** [comment]
That's more of a general problem with how you're loading the image (most likely). In this case you should be scaling the picture wayyy down (as you sort of did when you replaced the drawable with a smaller one).

Take a look at [this article](https://developer.android.com/topic/performance/graphics/load-bitmap.html).

**Comment by hdodenhof** [comment]
This is not a problem with this library but a wrong approach handling large bitmaps as has been pointed out.
