### ISSUE TITLE
using programmatically

### ISSUE THREAD

**Issue by ahsanzia341** [hdodenhof/CircleImageView#203]
I am using circle image view like this, but it is showing me a square image.
        circleImageView.setBackgroundResource(R.drawable.images);
        mSpec.setIndicator("",circleImageView.getBackground());

**Comment by hdodenhof** [comment]
You need to use `setImageResource` instead of `setBackgroundResource`.

**Comment by ahsanzia341** [comment]
Still the same :(
circleImageView.setImageResource(R.drawable.images);
        mSpec.setIndicator("",circleImageView.getDrawable());

**Comment by ahsanzia341** [comment]
ok its done. :)
