### ISSUE TITLE
getWidth() and getHeight() don't work sometimes

### ISSUE THREAD

**Issue by shxhzhxx** [hdodenhof/CircleImageView#205]
i already set layout_width and layout_height to be 80dp in xml.
and view.getWidth() return 0 at runtime.
i'm sure the view has been measured and drew before i called these method.

**Comment by hdodenhof** [comment]
This library doesn't interfere with view measurement, it itself actually uses `getWidth()` and `getHeight()` to draw the circle. You might still be be trying to access the dimensions to early.
