### ISSUE TITLE
Null Object Reference (SOLVED)

### ISSUE THREAD

**Issue by aabhasr1** [hdodenhof/CircleImageView#207]
TURNS OUT M AN IDIOT
when i use Circle Image View it returns null and hence the app crashes
Here is the code.
M using a Recycler view and want to set CircleImageView inside the card.

` public class ContactViewHolder extends RecyclerView.ViewHolder {
        public TextView contact_name;
        public CircleImageView contact_picture;

        public ContactViewHolder(View view) {
            super(view);
            contact_name = (TextView) view.findViewById(R.id.Contact_Name);
            contact_picture = (CircleImageView) view.findViewById(R.id.Contact_Picture);
            if(contact_picture==null){
                Log.i("Contact Pic Var =  ", "NULL");
            }
        }

    }`

`public void onBindViewHolder(ContactViewHolder holder, int position) {
        ContactList c = ContactsList.get(position);
        holder.contact_name.setText(c.getContact_name());
        holder.contact_picture.setImageDrawable(c.getContact_pic());`

and xml file
`<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:layout_width="match_parent"
    android:layout_height="80dp"
    android:orientation="horizontal"
    android:padding="@dimen/cardview_compat_inset_shadow">

    <android.support.v7.widget.CardView
        android:id="@+id/Contact_Card"
        android:layout_width="match_parent"
        android:layout_height="80dp">

        <LinearLayout
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:orientation="horizontal"
            android:weightSum="1">

            

            <de.hdodenhof.circleimageview.CircleImageView
                android:id="@+id/circleView"
                android:layout_width="80dp"
                android:layout_height="match_parent"
                android:layout_below="@+id/Contact_Picture"
                android:layout_centerHorizontal="true"
                android:layout_marginTop="10dp"
                android:layout_marginBottom="10dp"
                android:src="@mipmap/ic_launcher_example" />

            <TextView
                android:id="@+id/Contact_Name"
                android:layout_width="match_parent"
                android:layout_height="match_parent"
                android:layout_marginLeft="30dp"
                android:layout_weight="0.96"
                android:gravity="center_vertical"
                android:text="Contact Name"
                android:textAlignment="viewStart"
                android:textSize="18sp"
                android:textStyle="bold" />
        </LinearLayout>
    </android.support.v7.widget.CardView>
</LinearLayout>`

**Comment by shahriarmahmud** [comment]
how it solved. I face same problem

**Comment by aabhasr1** [comment]
I tried converting the ImageView (Contact_Picture) into CirclemageView (as you can see the ID reference in the java code)
