### ISSUE TITLE
VectorDrawableCompat with app:srcCompat not working

### ISSUE THREAD

**Issue by Burtan** [hdodenhof/CircleImageView#208]
Hi,
as described in the title, when using pre-Lollipop VectorDrawables with VectorDrawableCompat, you have to use app:srcCompat on normal ImageViews. This does not work using CircleImageView.

**Comment by FarbodSalamat-Zadeh** [comment]
This has been mentioned several times (#206, #188, #167, #122, #138, etc), but someone has created a pull-request for it here - see #199.

**Comment by hdodenhof** [comment]
What I said [here](https://github.com/hdodenhof/CircleImageView/issues/138#issuecomment-228567232) still stands: using a `VectorDrawable` with `CircleImageView` is just not a good idea, so there won't be official support for doing it.

**Comment by Burtan** [comment]
Thanks for the fast responses. Maybe put this into the documentation or leave the issue open. I just checked the open issues not the closed, sorry.

**Comment by hdodenhof** [comment]
No worries. An update to the README is actually overdue, I'll keep this topic in mind.

**Comment by hdodenhof** [comment]
README has been updated.
