### ISSUE TITLE
Error inflating class

### ISSUE THREAD

**Issue by GabrielLidenor** [hdodenhof/CircleImageView#210]
> android.view.InflateException: Binary XML file line #8: Error inflating class de.hdodenhof.circleimageview.CircleImageView

**Comment by hdodenhof** [comment]
This is impossible to solve without a full stack trace.

**Comment by iocrasher** [comment]
remove or change scaleType to CENTER_CROP

**Comment by amoetaz** [comment]
That error happens with me it might not work with others but in my case I removed src attribute and set it programmatically  and the error has been gone

**Comment by schixor88** [comment]
I got the problem while running on a 7 inch tab, but I had no any issues while running in medium sized phones. The problem was due to the src attribute

 

> <de.hdodenhof.circleimageview.CircleImageView
>                 <strike>android:src="@mipmap/prabhupay_xerchant"</strike>
>                 android:layout_width="50sp"
>                 android:layout_height="50sp"
>                 android:layout_centerHorizontal="true"
>                 android:id="@+id/image_view1"
>                 />

then it worked fine!

**Comment by muzamirus** [comment]
i changed from **android:src="@drawable/profile_pic"** to  **android:src="@mipmap/profile_pic"**
after removing my **profile_pic** from drawable to mipmap and it worked for me
