### ISSUE TITLE
Error in adjustViewBounds with true value

### ISSUE THREAD

**Issue by eugenio-caicedo** [hdodenhof/CircleImageView#211]
I have in the xml file the following:

`android:adjustViewBounds="false"`

But when I change the value to true I get that the property is not supported. How can I solve this?

**Comment by eugenio-caicedo** [comment]
@hdodenhof

**Comment by hdodenhof** [comment]
You can't solve that as it is a known limitation as stated in the [README](https://github.com/hdodenhof/CircleImageView#limitations).

**Comment by eugenio-caicedo** [comment]
@hdodenhof Umm, I understand. I had not read the limitations of the library before. Thanks for your help. Have you thought of this support for future versions?

**Comment by hdodenhof** [comment]
After some more research I decided against support for other scale types (which would be required for supporting adjustViewBounds) for now.

While I doubt this it still an issue for you (sorry for the late reply), feel free to post more details so we can find a workaround if it actually still is.
