### ISSUE TITLE
AppCompatImageView

### ISSUE THREAD

**Issue by FernandoFranco** [hdodenhof/CircleImageView#214]
Why not extends a AppCompatImageView?

**Comment by PhilipSA** [comment]
Yes it really should can't use it in my projects otherwise

**Comment by hdodenhof** [comment]
What feature of `AppCompatImageView` are you missing?

**Comment by PhilipSA** [comment]
Setting the tint and backgroundTint in older Android versions also being able to use the Compat XML-tags.

**Comment by sofakingforever** [comment]
Yea, using the app:srcCompat is pretty crucial for me as well.

@hdodenhof 
I also so that someone made a pull request for that. Any chance of merging and upload a new version?

**Comment by hdodenhof** [comment]
IMO the major argument against extending `AppCompatImageView`, which is having to include a dependency on the support library, still clearly outweighs the benefit of it. The only theoretical benefits would be (a) support for `VectorDrawable` using `srcCompat` and (b) support for tint attributes, with (a) being [not being a good idea](https://github.com/hdodenhof/CircleImageView/issues/138#issuecomment-228567232) and (b) not being supported out of the box (i.e. more changes would have to be made). Also (b) can be already achieved using a `ColorFilter`.

I'm still open for arguments but I'm closing this for now based on the outlined reasoning.
