### ISSUE TITLE
How to Set Image from URL

### ISSUE THREAD

**Issue by madhavkate** [hdodenhof/CircleImageView#222]
How to Set Image from URL.. Please Tell Me

**Comment by hdodenhof** [comment]
Please head over to StackOverflow for general questions like that. Picasso works perfectly fine if used with the `noFade()` option, there must be some other issue with your setup.

**Comment by rochapablo** [comment]
Here's a nice example:
https://stackoverflow.com/questions/30664254/using-picasso-library-with-a-circle-image-view

And here's how to install Picasso:
http://square.github.io/picasso
