### ISSUE TITLE
Picasso Placeholder drawable Pixelizing

### ISSUE THREAD

**Issue by hamdiburakdilek** [hdodenhof/CircleImageView#225]
When we set static xml drawable on layout or Placeholder on class  to CircleImageView. The image is showing like  pixelized.

**Comment by hdodenhof** [comment]
Is this still an issue @hamdiburakdilek? Sorry for getting back to you this late.

**Comment by leocorder** [comment]
#250 Similar problem here

**Comment by hdodenhof** [comment]
Stale. Please re-open if still an issue.
