### ISSUE TITLE
Padding between image and the imageview boarder

### ISSUE THREAD

**Issue by mike-maina** [hdodenhof/CircleImageView#226]
How do i add a gap between the image and the boarder

**Comment by 498971746** [comment]
Set padding int the parent view

**Comment by hdodenhof** [comment]
There's no built in support for this, but #133 contains a workaround that might work for you.

**Comment by mike-maina** [comment]
thank you

**Comment by AnujDutt2701** [comment]
This would be very useful if implemented.

**Comment by hdodenhof** [comment]
I won't implement this directly as I'd like to keep this whole thing as simple to use as possible and part of that is keeping the number of options limited. I recommend using that workaround - you could also create a custom `ViewGroup` that completely wraps the magic.
