### ISSUE TITLE
Error occured while building gradle

### ISSUE THREAD

**Issue by jibinkmathew94** [hdodenhof/CircleImageView#230]
I downloaded the project from GitHub and tried to run it in the android studio but I was not able to run it in studio as I got this error while building. 

Information:Gradle tasks [:circleimageview:generateDebugSources, :circleimageview:mockableAndroidJar, :circleimageview:prepareDebugUnitTestDependencies, :circleimageview:generateDebugAndroidTestSources, :sample:generateDebugSources, :sample:mockableAndroidJar, :sample:prepareDebugUnitTestDependencies, :sample:generateDebugAndroidTestSources]

Error:Execution failed for task ':circleimageview:processDebugResources'.
> com.android.ide.common.process.ProcessException: Failed to execute aapt\

Also all the resource R is being underlined.

**Comment by hdodenhof** [comment]
Are you trying to build the sample app? Works for me without any issues, please retry after doing a "Clean Project". If it still fails, please provide more details about your setup / a full stack trace.

**Comment by sd1998** [comment]
This issue has been solver previously the value of targetSdkVersion and that of compileSdkVersion were different hence the gradle build was resulting in an error  but now the values have been made equal hence the build should complete successfully
