### ISSUE TITLE
CircleImageView not working in AppWidgetProvider

### ISSUE THREAD

**Issue by MysteryDash** [hdodenhof/CircleImageView#231]
Hello,
I made the following layout : 

        <LinearLayout
            android:orientation="horizontal"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content">
            <de.hdodenhof.circleimageview.CircleImageView
                android:id="@+id/Picture"
                android:src="@drawable/MyPicture"
                android:layout_width="32dp"
                android:layout_height="32dp"
                android:scaleType="centerCrop"
                app:civ_border_width="2px"
                app:civ_border_color="#000000" />
            <TextView
                android:id="@+id/Username"
                android:text="Connecting..."
                android:textColor="#f56900"
                android:textAppearance="?android:attr/textAppearanceMedium"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:maxLines="1000000" />
        </LinearLayout>

When using it in a regular Activity or AppCompatActivity, I have absolutely no problem, however, when I try to use it in my AppWidgetProvider it just doesn't work.

Here are the logs : 
![log](https://user-images.githubusercontent.com/4283036/30783005-ba98589c-a13c-11e7-9759-ff4c21366087.png)

The simulator and my phone (while in an Activity) are able to display this whislt the Widget only gives me  "Couldn't add widget" : 
![working_simulator](https://user-images.githubusercontent.com/4283036/30783013-d2d69752-a13c-11e7-9af9-bbfa61ac8d3d.png)

Thank you.

**Comment by MysteryDash** [comment]
My bad, it seems that this issue comes from the RemoteViews not allowing an appwidget to use other widgets than those provided by the framework.
In the end I am drawing the Bitmap myself before displaying it.
Sorry for the inconvenience.

**Comment by iraj-wisilica** [comment]
@MysteryDash Can you post your code for fixing this issue? I am struck in the same. Thanks.
