### ISSUE TITLE
CircleImageView is square

### ISSUE THREAD

**Issue by EdwardtoGitHub** [hdodenhof/CircleImageView#232]
=.=I have solved it

**Comment by doersweb** [comment]
How ? CENTER_INSIDE doesn't seem to work with this

**Comment by hdodenhof** [comment]
Make sure you are using `android:src` / `setImage*()` and not `android:background` / `setBackground*()`.

**Comment by engr-erum** [comment]
src is working fine but  civ.setImageResource(resource); its not working when setting image dynamically from drawable folder , image is not proper circular

**Comment by hdodenhof** [comment]
There is (shouldn't be) any difference between using `setImageResource` and `src`. Please open a new issue with more details if that still is a problem @engr-erum.
