### ISSUE TITLE
Circle Background Color and Border Color not Working

### ISSUE THREAD

**Issue by StuStirling** [hdodenhof/CircleImageView#238]
I have the following layout:

```
<de.hdodenhof.circleimageview.CircleImageView
        android:id="@+id/civ_cap_profile"
        android:layout_width="0dp"
        android:layout_height="0dp"
        app:civ_border_color="@color/colorPrimary"
        app:civ_border_width="2dp"
        app:civ_circle_background_color="@color/white"
        app:layout_constraintBottom_toBottomOf="parent"
        app:layout_constraintDimensionRatio="1:1"
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintStart_toStartOf="parent"
        app:layout_constraintTop_toTopOf="parent"/>
```

But the view, when there is no image inside has no background color or border color.

**Comment by hdodenhof** [comment]
That's actually by design - if no image is set, nothing is drawn. To work around that you could just supply a color as "image" using `android:src="@color/white"`.

**Comment by StuStirling** [comment]
Ok thanks. I'm not sure but it may be good if this was added to the README?

**Comment by champrocks3190** [comment]
android:src="@color/white" even that don't work as background when there is no I'm age loaded .

**Comment by champrocks3190** [comment]
i don't understand what is the user of civ_fill_color if its not showing when image is not loaded after image loaded its gonna hide by it self . the attribute has no use ?
