### ISSUE TITLE
Is it possible to add boarder dynamically

### ISSUE THREAD

**Issue by prasoonpv** [hdodenhof/CircleImageView#241]
Hi is it possible to add boarder dynamically.

**Comment by BestAndroidProgrammer** [comment]
Hi. how can I add border dynamicly. Please put simple example

**Comment by AdrianMetzner** [comment]
You can use `setBorderColor(@ColorInt` int borderColor)` to define a color and `setBorderWidth(int borderWidth)` for the desired dynamic border width (in pixel)

**Comment by hdodenhof** [comment]
Nothing to add here.
