### ISSUE TITLE
Oom

### ISSUE THREAD

**Issue by MriDeas** [hdodenhof/CircleImageView#243]
if the bitmap is too big and the follow method is used directly, oom will happend:

 Bitmap.createBitmap(drawable.getIntrinsicWidth(), drawable.getIntrinsicHeight()..

**Comment by Cge001** [comment]
yes ,i happend the same to you @MriDeas .
always happen.
do you solve it ?

**Comment by hdodenhof** [comment]
Solution is to scale the image before supplying it to image view as advised in [this article](https://developer.android.com/topic/performance/graphics/load-bitmap.html).
