### ISSUE TITLE
For some images CircleImageView showing black background

### ISSUE THREAD

**Issue by abhaydatta** [hdodenhof/CircleImageView#246]
I have some images which are fetching from server and display to circleImageView but some black background comes with the image when it set inside CircleIamgeView

**Comment by voquanghoa** [comment]
I'm facing this issue too. Below is the screenshot

![Image of Yaktocat](https://snag.gy/OU9r32.jpg)

https://snag.gy/OU9r32.jpg

**Comment by luckerbai** [comment]
Me Too

**Comment by hdodenhof** [comment]
`com.jackandphantom.circularimageview.CircleImage` is not this library.
