### ISSUE TITLE
cutting edges 

### ISSUE THREAD

**Issue by TaniiSR** [hdodenhof/CircleImageView#247]
not showing whole image cut the edges adjust by itself

**Comment by rajeshfsp** [comment]
Hi, 
how to solve the cutting edges using this library. I used svg icon(vector drawable)

**Comment by TaniiSR** [comment]
I didn't get your point please explain i think i change the library

**Comment by hdodenhof** [comment]
I'm not sure what this is about. Please re-open with more details if still an issue.

**Comment by rajeshfsp** [comment]
Hi hdodenhof,
I'm using your library, I couldn't set scaleType except as 'cropCenter'. here I used svg icon, I'm facing this issue. please check this link.

 https://imgur.com/ToK02Jq

**Comment by hdodenhof** [comment]
Using vector images with this library is a bad idea and not supported as it is quite inefficient. You should instead just create circle shaped vector. Also `scaleType` is fixed to `CENTER_CROP` and cannot be changed as stated in the README.
