### ISSUE TITLE
ImageView with cornor radius only

### ISSUE THREAD

**Issue by isaiamuthan** [hdodenhof/CircleImageView#249]
Hi 

With the use of this library we cant able to achieve the corner radius images.
For that we have to use some other library

If it is possible means kindly included that also in the next version.

Corner radius dynamically and from xml too 

that means which side we need we have to apply for that.

Thanks in advance

**Comment by hdodenhof** [comment]
This is library is specifically for creating circles, hence I won't add corner radius options. But there are other great libraries out there offering just that.
