### ISSUE TITLE
Drawable with low definition

### ISSUE THREAD

**Issue by leocorder** [hdodenhof/CircleImageView#250]
When setting android:src attribute using a xml drawable (vector) on the CircleImageView, the image is showing with low definition, as if it had been stretched. It seems that CircleImageView is using vector attributes android:height and android:width set in the xml (usually set to 24dp by the Android Studio) instead of the height and width of the View.

**Comment by hdodenhof** [comment]
Using a `VectorDrawable` with this library is advised against and not supported as it is quite inefficient. You should instead just create circle shaped vector.
