### ISSUE TITLE
Very poor performance with Picasso & RecyclerView

### ISSUE THREAD

**Issue by maxbeech** [hdodenhof/CircleImageView#254]
Great custom ImageView!

However if using this on a list of circles whose images are loaded with Picasso, scrolling performance is very poor until all the images have loaded.

A fix would be hugely appreciated!

Cheers!

**Comment by leesandy** [comment]
Thank you to give permission for me

**Comment by hdodenhof** [comment]
I suspect you are not scaling down the images properly. Please have a look at #198 for a similar issue and an approach on how to fix it. Please reopen if the issue remains.
