### ISSUE TITLE
click in view angle border，it respond.

### ISSUE THREAD

**Issue by xianyo** [hdodenhof/CircleImageView#261]
my view 
           <de.hdodenhof.circleimageview.CircleImageView
            android:clickable="true"
            android:id="@+id/index_main_btn"
            android:background="@drawable/index_button_selector"
            android:layout_centerInParent="true"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"/>

when i click in the view angle border, it respond. 
how to not respond in angle border??

**Comment by hdodenhof** [comment]
https://github.com/hdodenhof/CircleImageView/pull/194 would probably fix this - unfortunately I haven't had time to properly look at it yet.
