### ISSUE TITLE
Cannot resolve symbol CircleImageView

### ISSUE THREAD

**Issue by dale15** [hdodenhof/CircleImageView#263]
Hi sir.

I recently updated my android studio to 3.1.1 and may build tools to 27.0.3 now when i sync my gradle CircleImageView V2.2.0 is not working.

Appreciate the help.

**Comment by dale15** [comment]
Hi sir. i resolve the error by using the version 2.1.0

**Comment by rushdroid** [comment]
Hello @hdodenhof, I am facing the same issue. Using 2.2.0 it's showing the can't resolve symbol with AS 3.1.2.

can you please help me to resolve this issue ?

**Comment by hdodenhof** [comment]
@rushdroid please double check your setup and add more details if the problem persists. There's nothing I can do with so little information.

**Comment by hdodenhof** [comment]
Closing this as there's not enough information for debugging and it's most likely a local issue unrelated to this library.

**Comment by rushdroid** [comment]
Hi, @hdodenhof Sorry for the late reply. It's working now correctly.

Thanks 
Rushabh
