### ISSUE TITLE
A workaround to add elevation to CircleImageView and make it more button like

### ISSUE THREAD

**Issue by fredliao123** [hdodenhof/CircleImageView#270]
So I need to make the CirleImageView to be more like a button. And I want this view to show some custom or maybe online image. So FloatActionButton won't be a solution.

[I referenced to this issue](https://github.com/hdodenhof/CircleImageView/issues/153#issuecomment-249692049) and come up with a solution:

So to have a elevation, we must have a background, this is my background
```
<?xml version="1.0" encoding="utf-8"?>
<shape
    xmlns:android="http://schemas.android.com/apk/res/android"
    android:shape="oval">
    <solid android:color="@color/white"/>
</shape>
```
The background color can't be `@android:color/transparent`, it will make elevation disappear.
Then set this background to CircleImageView. and set an elevation. But I soon find out that the elevation is partially cut off like this
![wrong_cllip](https://user-images.githubusercontent.com/7876575/40151260-2b89c6e2-59c2-11e8-8ddb-2618982db907.png)

I think that's because the shadow reached the boarder of view
So I added a Layout to wrap around CircleImageView and make it slightly larger than CircleImageView. 
So the code looks like this
```
 <FrameLayout
    android:layout_width="@dimen/logo_wrapper_size"
    android:layout_height="@dimen/logo_wrapper_size"
    android:layout_marginEnd="@dimen/large_margin"
    app:layout_constraintEnd_toEndOf="parent">

    <de.hdodenhof.circleimageview.CircleImageView
      android:id="@+id/logo"
      android:layout_width="@dimen/logo_size"
      android:layout_height="@dimen/logo_size"
      android:layout_gravity="center"
      android:background="@drawable/circle_background"
      android:elevation="@dimen/standard_margin"
      android:foreground="@drawable/round_selector"
      android:onClick='@{() -> clickListener.onItemActionClick(itemViewModel, "")}'
      android:src="@drawable/placeholder_bitmap" />
</FrameLayout>
```

```
<dimen name="logo_wrapper_size">78dp</dimen>
<dimen name="logo_size">54dp</dimen>
```

And this makes CircleImageView have a nice shadow like a FAB. It's even better when I added a ripple animation using this [workaround](https://github.com/hdodenhof/CircleImageView/issues/153#issuecomment-249692049)

![device-2018-05-17-111412](https://user-images.githubusercontent.com/7876575/40151473-86f4a8e8-59c3-11e8-8f95-18bc2c82b345.png)

**Comment by hdodenhof** [comment]
Nice work! Since version 2.2.0 `CircleImageView` actually comes with native support for elevation, hence it shouldn't be required to add a circle shaped background anymore.

**Comment by fredliao123** [comment]
Thank you. I tried version 2.2.0. It does have elevation now. Kudos! A wrapper is still needed or the elevation will be cut off on the edge.

**Comment by hdodenhof** [comment]
> A wrapper is still needed or the elevation will be cut off on the edge.

Correct, that's actually also these case for a regular `ImageView`. I'll close this for now as it's not really an issue with the library that needs to be worked on.
