### ISSUE TITLE
CircleImageView not woking with Picasso placeholder

### ISSUE THREAD

**Issue by Unoken** [hdodenhof/CircleImageView#273]
```
CircularProgressDrawable drawable = new CircularProgressDrawable(context);
drawable.setStrokeWidth(5f);
drawable.setCenterRadius(30f);
drawable.start();
Picasso.with(getContext())
.load(logo)
.fit()
.centerInside()
.placeholder(drawable)
.into(((LogoViewHolder) holder).mCIVAvatar);
```

I tried with simple imageView, it work, but not with CircleImageView.

**Comment by hdodenhof** [comment]
Unfortunately dynamic drawables like `CircularProgressDrawable` are not supported. If you decide to go with a static drawable, please notice the [Limitations section in the README](https://github.com/hdodenhof/CircleImageView#limitations) regarding Picassos fade animation.
