### ISSUE TITLE
OutOfMemory Exception

### ISSUE THREAD

**Issue by mnnyang** [hdodenhof/CircleImageView#275]
Frequent interface switching leads to memory overflows.

**Comment by hdodenhof** [comment]
How are you loading your images? Please make sure to follow [this Android Developers guide](https://developer.android.com/topic/performance/graphics/load-bitmap) to load `Bitmap`s efficiently.

**Comment by shubham10divakar** [comment]
use glide with drawables and custom transformations.This worked perfectly for me.
Glide.with(this).load(R.drawable.raspberrypi2).bitmapTransform(new CircleTransform(this)).into(raspberry);
raspberrypi2 is the image inside drawable folder.
CircleTransform is the java file that does the circular image tranformation.
It works like a charm.
