### ISSUE TITLE
Set drawable doesn't fully fit the circle

### ISSUE THREAD

**Issue by slavaantonenko** [hdodenhof/CircleImageView#278]
Hello,
I have a weird situation. When I'm using `circleImg.setImageResource(R.drawable.image)` and set also a border the following happens:

<img width="100" alt="screen shot 2018-07-08 at 12 13 39" src="https://user-images.githubusercontent.com/20560040/42418436-0cd8091a-82a9-11e8-9fbc-a1ca67d51843.png">

A gap is being created between the border line and the image itself.
Does anyone know what can cause this?

Note: I tried also to use `circleImg.setImageDrawable(getResources().getDrawable(R.drawable.image))` but got same result.

Thanks in advance!

**Comment by Merseyside** [comment]
Any changes? I got the same problem, circle doesn't fill in the bottom part!
