### ISSUE TITLE
Gif is not loading to the CircleImageView

### ISSUE THREAD

**Issue by varunam** [hdodenhof/CircleImageView#281]
Using Glide library to load Gif to imageview.

**Comment by hdodenhof** [comment]
Unfortunately animated drawables are not supported at this time.

**Comment by chrisbarth01** [comment]
Hello @hdodenhof is there any hope of GIFs being supported? This as I believe would make this library even more outstanding.

**Comment by hdodenhof** [comment]
I added some information about GIF support in https://github.com/hdodenhof/CircleImageView/issues/415.

**Comment by chrisbarth01** [comment]
Great! That worked. So, we won't have to use the other dependency anymore?
