### ISSUE TITLE
Crashing when use vector to set background to CircleImageView

### ISSUE THREAD

**Issue by mjalijani** [hdodenhof/CircleImageView#283]
When i'm using vector as background of CircleImageView my app getting crash on android preLolipop 
here my layout Code : 
```
 <ImageView
                        android:padding="@dimen/_10sdp"
                        android:layout_width="@dimen/_60sdp"
                        android:layout_height="@dimen/_60sdp"
                        app:srcCompat="@drawable/ic_shopping_bag"
                        android:background="@drawable/circle_bg"
                        android:elevation="@dimen/_20sdp"
                        android:outlineProvider="paddedBounds"
                        tools:targetApi="lollipop" />
```

v24/circle_bg.xml : 

```
<?xml version="1.0" encoding="utf-8"?>
<shape
    xmlns:android="http://schemas.android.com/apk/res/android"

    android:shape="oval">
    <solid android:color="#FFFFFF"/>

    <stroke
        android:width="1dp"
        android:color="#FFFFFF"/>

</shape>
```

 use circle_bg because i'm want to make elevation visible for my view.

**Comment by hdodenhof** [comment]
To achieve elevation you don't need a custom background or set the `outlineProvider` property. The latest version (2.2.0) comes with native support for circular elevation - just set the `elevation` property.

**Comment by mjalijani** [comment]
now i'm delete it , but getting this error 

> 08-08 11:34:53.762 1708-1708/com.daya.smartcity E/dalvikvm: Could not find class 'android.support.v4.widget.DrawerLayout$1', referenced from method android.support.v4.widget.DrawerLayout.<init>
> 08-08 11:34:53.766 1708-1708/com.daya.smartcity E/dalvikvm: Could not find class 'android.view.WindowInsets', referenced from method android.support.v4.widget.DrawerLayout.onDraw
> 08-08 11:34:53.766 1708-1708/com.daya.smartcity E/dalvikvm: Could not find class 'android.view.WindowInsets', referenced from method android.support.v4.widget.DrawerLayout.onMeasure
> 08-08 11:34:53.766 1708-1708/com.daya.smartcity E/dalvikvm: Could not find class 'android.view.WindowInsets', referenced from method android.support.v4.widget.DrawerLayout.onMeasure
> 08-08 11:34:54.002 1708-1708/com.daya.smartcity E/dalvikvm: Could not find class 'android.graphics.drawable.RippleDrawable', referenced from method android.support.v7.widget.AppCompatImageHelper.hasOverlappingRendering
> 08-08 11:34:54.022 1708-1708/com.daya.smartcity E/AndroidRuntime: FATAL EXCEPTION: main
>     java.lang.RuntimeException: Unable to start activity ComponentInfo{com.daya.smartcity/com.daya.smartcity.view.activity.MainActivity}: android.view.InflateException: Binary XML file line #32: Error inflating class com.daya.smartcity.view.widgets.MButton
>         at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2180)
>         at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2230)
>         at android.app.ActivityThread.access$600(ActivityThread.java:141)
>         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1234)
>         at android.os.Handler.dispatchMessage(Handler.java:99)
>         at android.os.Looper.loop(Looper.java:137)
>         at android.app.ActivityThread.main(ActivityThread.java:5041)
>         at java.lang.reflect.Method.invokeNative(Native Method)
>         at java.lang.reflect.Method.invoke(Method.java:511)
>         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
>         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560)
>         at dalvik.system.NativeStart.main(Native Method)
>      Caused by: android.view.InflateException: Binary XML file line #32: Error inflating class com.daya.smartcity.view.widgets.MButton
>         at android.view.LayoutInflater.createView(LayoutInflater.java:613)
>         at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:687)
>         at android.view.LayoutInflater.rInflate(LayoutInflater.java:746)
>         at android.view.LayoutInflater.rInflate(LayoutInflater.java:749)
>         at android.view.LayoutInflater.inflate(LayoutInflater.java:489)
>         at android.view.LayoutInflater.inflate(LayoutInflater.java:396)
>         at android.view.LayoutInflater.inflate(LayoutInflater.java:352)
>         at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:287)
>         at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:139)
>         at com.daya.smartcity.view.activity.MainActivity.onCreate(MainActivity.java:33)
>         at android.app.Activity.performCreate(Activity.java:5104)
>         at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1080)
>         at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2144)
>         at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2230) 
>         at android.app.ActivityThread.access$600(ActivityThread.java:141) 
>         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1234) 
>         at android.os.Handler.dispatchMessage(Handler.java:99) 
>         at android.os.Looper.loop(Looper.java:137) 
>         at android.app.ActivityThread.main(ActivityThread.java:5041) 
>         at java.lang.reflect.Method.invokeNative(Native Method) 
>         at java.lang.reflect.Method.invoke(Method.java:511) 
>         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793) 
>         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560) 
>         at dalvik.system.NativeStart.main(Native Method) 
>      Caused by: java.lang.reflect.InvocationTargetException
>         at java.lang.reflect.Constructor.constructNative(Native Method)
>         at java.lang.reflect.Constructor.newInstance(Constructor.java:417)
>         at android.view.LayoutInflater.createView(LayoutInflater.java:587)
>         at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:687) 
>         at android.view.LayoutInflater.rInflate(LayoutInflater.java:746) 
>         at android.view.LayoutInflater.rInflate(LayoutInflater.java:749) 
>         at android.view.LayoutInflater.inflate(LayoutInflater.java:489) 
>         at android.view.LayoutInflater.inflate(LayoutInflater.java:396) 
>         at android.view.LayoutInflater.inflate(LayoutInflater.java:352) 
>         at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:287) 
>         at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:139) 
>         at com.daya.smartcity.view.activity.MainActivity.onCreate(MainActivity.java:33) 
>         at android.app.Activity.performCreate(Activity.java:5104) 
>         at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1080) 
>         at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2144) 
>         at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2230) 
>         at android.app.ActivityThread.access$600(ActivityThread.java:141) 
>         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1234) 
>         at android.os.Handler.dispatchMessage(Handler.java:99) 
>         at android.os.Looper.loop(Looper.java:137) 
>         at android.app.ActivityThread.main(ActivityThread.java:5041) 
>         at java.lang.reflect.Method.invokeNative(Native Method) 
>         at java.lang.reflect.Method.invoke(Method.java:511) 
>         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793) 
>         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560) 
>         at dalvik.system.NativeStart.main(Native Method) 
>      Caused by: android.content.res.Resources$NotFoundException: Resource is not a Drawable (color or path): TypedValue{t=0x1/d=0x7f070090 a=-1 r=0x7f070090}
>         at android.content.res.Resources.loadDrawable(Resources.java:1927)
>         at android.content.res.TypedArray.getDrawable(TypedArray.java:601)
>         at android.view.View.<init>(View.java:3330)
>         at android.widget.TextView.<init>(TextView.java:583)
>         at android.widget.Button.<init>(Button.java:107)
>         at android.support.v7.widget.AppCompatButton.<init>(AppCompatButton.java:70)
>         at android.support.v7.widget.AppCompatButton.<init>(AppCompatButton.java:66)
>         at com.daya.smartcity.view.widgets.MButton.<init>(MButton.java:17)
>         at java.lang.reflect.Constructor.constructNative(Native Method) 
>         at java.lang.reflect.Constructor.newInstance(Constructor.java:417) 
>         at android.view.LayoutInflater.createView(LayoutInflater.java:587) 
>         at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:687) 
>         at android.view.LayoutInflater.rInflate(LayoutInflater.java:746) 
>         at android.view.LayoutInflater.rInflate(LayoutInflater.java:749) 
>         at android.view.LayoutInflater.inflate(LayoutInflater.java:489) 
>         at android.view.LayoutInflater.inflate(LayoutInflater.java:396) 
>         at android.view.LayoutInflater.inflate(LayoutInflater.java:352) 
>         at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:287) 
>         at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:139) 
>         at com.daya.smartcity.view.activity.MainActivity.onCreate(MainActivity.java:33) 
>         at android.app.Activity.performCreate(Activity.java:5104) 
>         at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1080) 
>         at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2144) 
>         at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2230) 
>         at android.app.ActivityThread.access$600(ActivityThread.java:141) 
>         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1234) 
>         at android.os.Handler.dispatchMessage(Handler.java:99) 
>         at android.os.Looper.loop(Looper.java:137) 
>         at android.app.ActivityThread.main(ActivityThread.java:5041) 
>         at java.lang.reflect.Method.invokeNative(Native Method) 
>         at java.lang.reflect.Method.invoke(Method.java:511) 
>         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793) 
>         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560) 
>         at dalvik.system.NativeStart.main(Native Method) 

here my whole layout source : 
```
<?xml version="1.0" encoding="utf-8"?>
<android.support.v4.widget.DrawerLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:orientation="vertical"
    android:background="@color/white"
    android:id="@+id/drawer_layout"
    tools:context=".view.activity.MainActivity">

    <LinearLayout
        android:orientation="vertical"
        android:layout_width="match_parent"
        android:layout_height="match_parent">

        <LinearLayout
            android:gravity="right"
            android:background="@drawable/background"
            android:layout_width="match_parent"
            android:layout_height="@dimen/_100sdp">

                <ImageView
                    android:id="@+id/img_showNavigation"
                    android:layout_margin="@dimen/_10sdp"
                    android:padding="@dimen/_10sdp"
                    android:layout_width="@dimen/_50sdp"
                    android:layout_height="@dimen/_50sdp"
                    app:srcCompat="@drawable/ic_menu"/>

        </LinearLayout>
        <com.daya.smartcity.view.widgets.MButton
            android:drawableRight="@drawable/ic_add"
            android:paddingRight="@dimen/_10sdp"
            android:layout_gravity="center"
            android:gravity="center"
            android:background="@drawable/txt_bg"
            android:layout_width="@dimen/_150sdp"
            android:layout_height="wrap_content"
            android:elevation="@dimen/_3sdp"
            style="@style/Base.Widget.AppCompat.Button.Borderless"
            android:text="15,000,000 ریال اعتبار"
            tools:targetApi="lollipop" />

        <LinearLayout
            android:layout_marginTop="@dimen/_10sdp"
            android:weightSum="1"
            android:orientation="vertical"
            android:layout_width="match_parent"
            android:layout_height="match_parent">

            <LinearLayout
                android:layout_weight="0.33"
                android:weightSum="1"
                android:orientation="horizontal"
                android:layout_width="match_parent"
                android:layout_height="match_parent">
                <LinearLayout
                    android:id="@+id/lyt_food_reserve"
                    android:layout_weight="0.33"
                    android:orientation="vertical"
                    android:gravity="center"
                    android:layout_width="match_parent"
                    android:layout_height="match_parent"
                    tools:ignore="NestedWeights">

                    <de.hdodenhof.circleimageview.CircleImageView
                        android:padding="@dimen/_10sdp"
                        android:layout_width="@dimen/_60sdp"
                        android:layout_height="@dimen/_60sdp"
                        app:srcCompat="@drawable/ic_shopping_bag"
                        android:elevation="@dimen/_20sdp"
                        android:outlineProvider="paddedBounds"
                        tools:targetApi="lollipop" />

                    <com.daya.smartcity.view.widgets.TxtView
                        android:textSize="@dimen/_12sdp"
                        android:layout_width="wrap_content"
                        android:layout_height="wrap_content"
                        android:text="سفارش غذا"/>
                </LinearLayout>

                <LinearLayout
                    android:layout_weight="0.34"
                    android:orientation="vertical"
                    android:gravity="center"
                    android:layout_width="match_parent"
                    android:layout_height="match_parent"
                    tools:ignore="NestedWeights">

                    <de.hdodenhof.circleimageview.CircleImageView
                        android:padding="@dimen/_10sdp"
                        android:layout_width="@dimen/_60sdp"
                        android:layout_height="@dimen/_60sdp"
                        app:srcCompat="@drawable/ic_shopping_bag"
                        
                        android:elevation="@dimen/_20sdp"
                        android:outlineProvider="paddedBounds"
                        tools:targetApi="lollipop" />

                    <com.daya.smartcity.view.widgets.TxtView
                        android:textSize="@dimen/_12sdp"
                        android:layout_width="wrap_content"
                        android:layout_height="wrap_content"
                        android:text="خرید شارژ"/>
                </LinearLayout>

                <LinearLayout
                    android:layout_weight="0.33"
                    android:orientation="vertical"
                    android:gravity="center"
                    android:layout_width="match_parent"
                    android:layout_height="match_parent"
                    tools:ignore="NestedWeights">

                    <de.hdodenhof.circleimageview.CircleImageView
                        android:padding="@dimen/_10sdp"
                        android:layout_width="@dimen/_60sdp"
                        android:layout_height="@dimen/_60sdp"
                        app:srcCompat="@drawable/ic_shopping_bag"
                        android:elevation="@dimen/_20sdp"
                        android:outlineProvider="paddedBounds"
                        tools:targetApi="lollipop" />

                    <com.daya.smartcity.view.widgets.TxtView
                        android:textSize="@dimen/_12sdp"
                        android:layout_width="wrap_content"
                        android:layout_height="wrap_content"
                        android:text="خرید شارژ"/>
                </LinearLayout>

            </LinearLayout>
            

        </LinearLayout>
    </LinearLayout>

    <LinearLayout
        android:id="@+id/lay_navigation"
        android:layout_width="@dimen/_250sdp"
        android:layout_height="match_parent"
        android:orientation="vertical"
        android:background="#fff"
        android:layout_gravity="end">

        <include layout="@layout/navigation_layout" />

    </LinearLayout>
</android.support.v4.widget.DrawerLayout>
```

**Comment by hdodenhof** [comment]
That crash has nothing to do with this library.
Relevant stack trace excerpt:
```
     Caused by: android.content.res.Resources$NotFoundException: Resource is not a Drawable (color or path): TypedValue{t=0x1/d=0x7f070090 a=-1 r=0x7f070090}
        at android.content.res.Resources.loadDrawable(Resources.java:1927)
        at android.content.res.TypedArray.getDrawable(TypedArray.java:601)
        at android.view.View.<init>(View.java:3330)
        at android.widget.TextView.<init>(TextView.java:583)
        at android.widget.Button.<init>(Button.java:107)
        at android.support.v7.widget.AppCompatButton.<init>(AppCompatButton.java:70)
        at android.support.v7.widget.AppCompatButton.<init>(AppCompatButton.java:66)
        at com.daya.smartcity.view.widgets.MButton.<init>(MButton.java:17)
        at [...]
```
