### ISSUE TITLE
Image Border Gap 1 dp

### ISSUE THREAD

**Issue by iamsahilarora** [hdodenhof/CircleImageView#286]
Hello can any one help i need gap between image and border can i do like this 
![screen shot 2018-08-14 at 4 42 12 pm](https://user-images.githubusercontent.com/15409411/44089828-ce0d7454-9fe5-11e8-9248-9b5f3b89ef3b.png)

**Comment by hdodenhof** [comment]
Please have a look at #133, esp. [this comment](https://github.com/hdodenhof/CircleImageView/issues/133#issuecomment-227259968).
