### ISSUE TITLE
Failed to resolve:de.hdodenhof:circleimageview:2.2.3

### ISSUE THREAD

**Issue by phineetee** [hdodenhof/CircleImageView#290]
Please any help

**Comment by npaul2173** [comment]
same thing with me... please someone help out
it is showing


**__**Unable to resolve dependency for ':app@debugAndroidTest/compileClasspath': Could not resolve de.hdodenhof:circleimageview:2.2.0._**_**

**Comment by hdodenhof** [comment]
Latest version is 2.2.0 which is [available on maven central](https://search.maven.org/search?q=a:circleimageview) - if that can't be resolved, there's some issue with your local setup. Try to clear caches.
