### ISSUE TITLE
Gif loading

### ISSUE THREAD

**Issue by james04gr** [hdodenhof/CircleImageView#293]
I think you should create a gif loading implementation. I have tried it with Glide 4.8.0 and it doesnt work...!!!

**Comment by hdodenhof** [comment]
For circle cropping GIFs you could use Glides inbuilt circle crop transformation. You'd loose some feature like adding a border and proper support for elevation but if that's okay for you, that would be the way to go. There won't be any native support for GIFs as part of this library.
