### ISSUE TITLE
Picasso/Elevation Compatibility Issue

### ISSUE THREAD

**Issue by pbenike** [hdodenhof/CircleImageView#294]
I've noticed that while elevation and compatibility with Picasso are both supported individually, using Picasso to load an image into an elevated CircleImageView is causing the shadow to be lost.

Sample Views (@drawable/control_circular_view is an oval shape with a white background):

    <View
        android:id="@+id/controlCircularVIew"
        android:layout_width="40dp"
        android:layout_height="40dp"
        android:elevation="8dp"
        android:background="@drawable/control_circular_view" />

    <de.hdodenhof.circleimageview.CircleImageView
        android:id="@+id/picassoIcon"
        android:layout_width="40dp"
        android:layout_height="40dp"
        android:elevation="8dp"

        android:src="@drawable/default_icon"
        app:civ_border_color="@color/white"
        app:civ_border_width="1dp" />

Picasso call:

`Picasso.with(context).load(url).error(R.drawable.default_icon).noFade().into(picassoIcon)
`

Before Picasso is called, both views appear with identical sizes and shadows. After Picasso loads the URL into the CircleImageView, its shadow is lost while the control view's shadow remains.

**Comment by pbenike** [comment]
One workaround is to define `.placeholder(R.drawable.default_icon)` . If you define the placeholder to be the same drawable as the default image, then the shadow remains.

I'll close since this, defining a placeholder in Picasso image is a good practice, even though I'd argue that ideally this shouldn't be necessary. But beggars can't be choosers.

**Comment by hdodenhof** [comment]
That's interesting. I'll try to look into it!

**Comment by iamrocklobster** [comment]
The same happens using Glide. And the workaround works for both.
