### ISSUE TITLE
use Glide + CircleImageView happen OOM

### ISSUE THREAD

**Issue by Clearlove2015** [hdodenhof/CircleImageView#296]
![image](https://user-images.githubusercontent.com/11958766/46126588-73c8f980-c260-11e8-93c7-8596d06d0a65.png)

**Comment by hdodenhof** [comment]
You probably need to scale the image before passing it to `CircleImageView`. Please have a look at [existing issue to this topic](https://github.com/hdodenhof/CircleImageView/issues?utf8=✓&q=is%3Aissue+is%3Aclosed+OOM).

**Comment by Clearlove2015** [comment]
Thank you very match.
