### ISSUE TITLE
SetImageDrawable not working when using Iconify plugin

### ISSUE THREAD

**Issue by TotoBido** [hdodenhof/CircleImageView#299]
Working on an Adapter with a Cardview to show thumbnails and icons using _Iconify_ (https://github.com/JoanZapata/android-iconify). Tried to change the squared thumbnail I had with ImageView to a circular one with CircleImageView but the icons created are no longer seen. 
I'm obliged to use "SetImageDrawable" with the other nugget

`holder.Thumbnail.SetImageDrawable(new IconDrawable(_Context, icon).WithColorRes(Android.Resource.Color.Black))`
I suppose the icon is added but you can't see anything

**Comment by hdodenhof** [comment]
Is there anything related to this in the logs?

**Comment by hdodenhof** [comment]
Most likely outdated by now.
