### ISSUE TITLE
Problem About Using CircleImageView in Maven Porject

### ISSUE THREAD

**Issue by miaolingzi** [hdodenhof/CircleImageView#30]
when I use CicleImageView in my maven project by dependencing Maven Repository，my projectc can`t find CircleImageView。But I find that your maven repository （version 1.2.1） has a values.xml file in res/values  directory instand of a attrs.xml file in res/values   directory which is in your github project。when I use attrs.xml replace values.xml，my maven project run success。Please insure your values.xml file in your maven repository  。

**Comment by hdodenhof** [comment]
All values from attrs.xml are merged into values.xml as part of the Android build process - that's the expected behaviour. Please provide more details about your setup for troubleshooting.
