### ISSUE TITLE
why get bitmap from ColorDrawable,with & height assigned 2 ?

### ISSUE THREAD

**Issue by yungelee** [hdodenhof/CircleImageView#301]
bitmap = Bitmap.createBitmap(COLORDRAWABLE_DIMENSION, COLORDRAWABLE_DIMENSION, BITMAP_CONFIG);

**Comment by hdodenhof** [comment]
ColorDrawables don't have an intrinsic size, hence we need to set an arbitrary size when creating the bitmap. A size of 1 doesn't work on some API levens (see #23), that's why it's 2.
