### ISSUE TITLE
App crashes on tablet

### ISSUE THREAD

**Issue by Benarab** [hdodenhof/CircleImageView#302]
Hi.

I have some issues, when i put your CircleImageView in my app it crashes on my tablet (but works fine on phone). Can u spot what gives the problem? Here is my xml for the image view:

<de.hdodenhof.circleimageview.CircleImageView
                    android:layout_width="70dp"
                    android:layout_height="70dp"
                    android:layout_gravity="center"
                    android:layout_marginTop="40dp"
                    android:src="@drawable/formaal"
                    app:civ_border_color="@color/Primær"
                    app:civ_border_width="1dp" />

**Comment by hdodenhof** [comment]
It's impossible to figure this out without more details, please add at least the stack trace of the crash.

**Comment by hdodenhof** [comment]
I guess this is outdated by now. Please reopen with more details if still an issue.
