### ISSUE TITLE
OOM

### ISSUE THREAD

**Issue by mzdxztm** [hdodenhof/CircleImageView#303]
就加了三个CircleImageView对象,内存比我其他全部对象加起来占用的内存还要大。

**Comment by hdodenhof** [comment]
Please have a look at [existing issue regarding OOMs](https://github.com/hdodenhof/CircleImageView/issues?utf8=%E2%9C%93&q=OOM), there should be plenty of tips. in case that doesn't help, feel free to reopen the issue with more details and in English - I don't understand Chinese.
