### ISSUE TITLE
can set extension gif?

### ISSUE THREAD

**Issue by harloom** [hdodenhof/CircleImageView#304]
I am  set glide asGif(). cannot play gif?

**Comment by hdodenhof** [comment]
Unfortunately GIF files are not supported. See my reply in #293:
> For circle cropping GIFs you could use Glides inbuilt circle crop transformation. You'd loose some feature like adding a border and proper support for elevation but if that's okay for you, that would be the way to go. There won't be any native support for GIFs as part of this library.
