### ISSUE TITLE
Help: It causes the app to crash in LOLLIPOP (Version 2.2.0)

### ISSUE THREAD

**Issue by MuhammadElsayed96** [hdodenhof/CircleImageView#308]
Error inflating class de.hdodenhof.circleimageview.CircleImageView
It works just fine in the later Android versions.
Can anyone help?

**Comment by drakkan** [comment]
can you paste the stacktrace please?

**Comment by hdodenhof** [comment]
As @drakkan said, this needs more details. Please reopen and attach the stack trace if still relevant.
