### ISSUE TITLE
how to compat with androidx ?

### ISSUE THREAD

**Issue by chat491231702** [hdodenhof/CircleImageView#310]
import android.support.annotation.ColorInt;
import android.support.annotation.ColorRes;
import android.support.annotation.DrawableRes;
import android.support.annotation.RequiresApi;

are not exists any more

instead with

import androidx.annotation.ColorInt;
import androidx.annotation.ColorRes;
import androidx.annotation.DrawableRes;
import androidx.annotation.RequiresApi;

**Comment by rosariopfernandes** [comment]
There's already an open PR to fix that (see #295). Maybe we should wait for it to be merged. Can we please have your attention on this matter @hdodenhof ?

**Comment by hdodenhof** [comment]
PR is merged, I still need to prepare a new release though. Will keep this open until that's done.

**Comment by hdodenhof** [comment]
A new version (v3.0.0) including this change has just been released.
