### ISSUE TITLE
Not working in android 9

### ISSUE THREAD

**Issue by pordel** [hdodenhof/CircleImageView#312]
Not working in android 9

![photo_2019-01-23_09-25-12](https://user-images.githubusercontent.com/25703829/51586014-d2da0a80-1ef0-11e9-9329-85d5b5a630e5.jpg)

**Comment by hdodenhof** [comment]
Well, in general it works on Android 9 - you can use the sample app to confirm that. So most likely it's an issue with your code. If you post your layout and relevant code extract, I might be able to help.

**Comment by rishabhdugar** [comment]
Try this https://stackoverflow.com/questions/53139689/picasso-image-loading-issue-with-android-9-0-pie

**Comment by hdodenhof** [comment]
Closing as this is unlikely to be issue with the library. Please reopen with more details in case this is still relevant.
