### ISSUE TITLE
Bitmap Image is changing orientation for some pics

### ISSUE THREAD

**Issue by RockinSam** [hdodenhof/CircleImageView#316]

**Comment by hdodenhof** [comment]
Sounds like an issue with EXIF orientation. You could either read and apply the orientation yourself using `androidx.exifinterface` or use an image loader like Glide or Picasso to handle that for you. I'd recommend doing the latter.

**Comment by febeks** [comment]
I am having the same problem. Are you planning on fixing it anytime soon?

**Comment by hdodenhof** [comment]
This is not a problem with the library. You need to take EXIF orientation into account when loading an image. StackOverflow should have answers on how to do that.

**Comment by RockinSam** [comment]
Use uri of image to maintain orientation. Bitmap might change the
orientation. If you still want to use bitmap change EXIF orientation

**Comment by febeks** [comment]
I have used this [rotate method](https://gist.github.com/tomogoma/788e3b775dd611c9226f8e17781a0f0c)

**Comment by RockinSam** [comment]
Yes that is what EXIF is.

**Comment by hdodenhof** [comment]
Original issue seems to be solved.
