### ISSUE TITLE
Does not load the image from the internal memory of the phone using the glide when the size of the view is 70 dp, but with a size of 100 dp it loads and displays normally

### ISSUE THREAD

**Issue by wkazak** [hdodenhof/CircleImageView#317]
It does not load the image from the internal memory of the phone using the glide when the size of the view is 70 dp, but with a size of 100 dp it loads and displays normally. Other images (for example, from the network) load normally and at a size of 70 dp.

**Comment by hdodenhof** [comment]
Can you provide a minimal sample app to reproduce this issue?

**Comment by wkazak** [comment]
I get Uri local image from the phone through the intent and try to install it using the glide in your view.
`civEditProfile.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {
                Intent intent = new Intent(Intent.ACTION_PICK);
                intent.setType("image/*");
                startActivityForResult(intent, 1);
            }
        });

@Override
    protected void onActivityResult(int requestCode, int resultCode, Intent data) {
        super.onActivityResult(requestCode, resultCode, data);
        if (resultCode == RESULT_OK) {
            Uri urlOfImage = data.getData();
            Glide.with(this).load(urlOfImage).into(civEditProfile);
            Log.e("LOl", String.valueOf(urlOfImage));
            urlOfPhoto = String.valueOf(urlOfImage);
        }
    }`
XML Activity
`<android.support.constraint.ConstraintLayout
                android:layout_width="match_parent"
                android:layout_height="wrap_content">

                <de.hdodenhof.circleimageview.CircleImageView
                    android:id="@+id/civEditProfile"
                    android:layout_width="150dp"
                    android:layout_height="150dp"
                    android:layout_marginEnd="8dp"
                    android:layout_marginStart="8dp"
                    android:layout_marginTop="16dp"
                    android:src="@drawable/default_avatar"
                    app:civ_border_color="@color/white"
                    app:civ_border_width="3dp"
                    app:civ_circle_background_color="@color/white"
                    app:layout_constraintEnd_toEndOf="@+id/textView56"
                    app:layout_constraintStart_toStartOf="@+id/textView56"
                    app:layout_constraintTop_toTopOf="parent" />
</android.support.constraint.ConstraintLayout>`

**Comment by hdodenhof** [comment]
Unfortunately I'm not able to reproduce that behaviour - works for me if I use the code you posted, no matter the size of the `CircleImageView`. Does this only happen with specific images or on specific devices? Can you reproduce the issue if you add your code to the sample app?

**Comment by hdodenhof** [comment]
Closing as stale. Please reopen if this is still an issue.
