### ISSUE TITLE
A question about this library

### ISSUE THREAD

**Issue by VahidGarousi** [hdodenhof/CircleImageView#318]
Is this library compatible with Kotlin?
As you can see, the photo is not circular
![1](https://user-images.githubusercontent.com/19606714/52552633-25bf2780-2df6-11e9-9684-d31c5d3fb177.JPG)

**Comment by hdodenhof** [comment]
Yes, it's compatible with both Java and Kotlin. Does this also happen on a device?

**Comment by VahidGarousi** [comment]
Yes, I encountered an error several times, but it works right now. Thank
you for this library!


n Mon, Feb 11, 2019, 13:10 Henning Dodenhof <notifications@github.com>
wrote:
