### ISSUE TITLE
Background with 'civ_fill_background' is not showing unless image with 'src' attribute is set

### ISSUE THREAD

**Issue by mecoFarid** [hdodenhof/CircleImageView#322]
I've actually looked through all related issues. Unfortunately, couldn't find any solution. All related issues tagged as closed, but I still can't get it working. Using the latest version.

> Code to reproduce.

_Background is not visible:_

```
<de.hdodenhof.circleimageview.CircleImageView
            android:layout_width="100dp"
            android:layout_height="100dp"
            android:layout_gravity="center_horizontal"
            android:layout_marginTop="@dimen/dimension_32dp"
            app:civ_fill_color="#D0D0D0"/>
```

Adding `src` attribute; 

_Background is now visible:_

```
<de.hdodenhof.circleimageview.CircleImageView
            android:layout_width="100dp"
            android:layout_height="100dp"
            android:layout_gravity="center_horizontal"
            android:layout_marginTop="@dimen/dimension_32dp"
            app:civ_fill_color="#D0D0D0"
            android:src="@drawable/bg_account_menu_item"/>
```

**Comment by hdodenhof** [comment]
Have you seen [my comment on #238](https://github.com/hdodenhof/CircleImageView/issues/238#issuecomment-339145961)? The purpose of `civ_fill_color` (deprecated) and `civ_circle_background_color` is to provide background for images with transparency, hence it's only drawn when an image is set. What's your use case?

**Comment by mecoFarid** [comment]
I was trying to use it as a placeholder until an image is loaded. Well, since it won’t show unless an image is set then I’ll just use an oval drawable to imitate palceholder. So, I think this is settled :)

**Comment by hdodenhof** [comment]
Great. You could also just use a `ColorDrawable` instead of an oval drawable.
