### ISSUE TITLE
Dotted Border

### ISSUE THREAD

**Issue by musab-r** [hdodenhof/CircleImageView#323]
How can i implement the dotted border with it.

**Comment by hdodenhof** [comment]
This is not supported out-of-the-box but it's quite easy to do. You just need to modify the source of `CircleImageView` and add a `DashPathEffect` to `mBorderPaint` in `setup()` - something like that:
```
mBorderPaint.setPathEffect(new DashPathEffect(new float[]{ 10f, 10f }, 0f));
```

**Comment by somoine** [comment]
how to do it?


> This is not supported out-of-the-box but it's quite easy to do. You just need to modify the source of `CircleImageView` and add a `DashPathEffect` to `mBorderPaint` in `setup()` - something like that:
> 
> ```
> mBorderPaint.setPathEffect(new DashPathEffect(new float[]{ 10f, 10f }, 0f));
> ```
