### ISSUE TITLE
Proguard Errors

### ISSUE THREAD

**Issue by Asendo316** [hdodenhof/CircleImageView#324]
Warning: de.hdodenhof.circleimageview.CircleImageView: can't find referenced class androidx.annotation.ColorInt

Warning: de.hdodenhof.circleimageview.CircleImageView: can't find referenced class androidx.annotation.ColorInt

Warning: de.hdodenhof.circleimageview.CircleImageView: can't find referenced class androidx.annotation.DrawableRes

Warning: de.hdodenhof.circleimageview.CircleImageView$OutlineProvider: can't find referenced class androidx.annotation.RequiresApi

**Comment by hdodenhof** [comment]
These warnings are not a problem. You can safely add `-dontwarn` options for these to your ProGuard configuration.

**Comment by KalScv** [comment]
am using this, resolved the above error 
-dontwarn androidx.annotation.**
