### ISSUE TITLE
Not working as expected

### ISSUE THREAD

**Issue by jatin664** [hdodenhof/CircleImageView#327]
It does not change my image from normal into round form.
I am unable to get what cause this issue.
I m using it with linear layout and also tried with other layout as well.
Please help
`<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent">

    <de.hdodenhof.circleimageview.CircleImageView
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:src="@drawable/empty_cart"
        app:layout_constraintBottom_toBottomOf="parent"
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintHorizontal_bias="0.5"
        app:layout_constraintStart_toStartOf="parent"
        app:layout_constraintTop_toTopOf="parent" />

</LinearLayout>`

`<LinearLayout android:layout_width="match_parent"
    android:layout_height="wrap_content"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:layout_marginTop="4dp"
    android:layout_marginBottom="2dp"
    android:orientation="horizontal"
    android:weightSum="5"
    xmlns:android="http://schemas.android.com/apk/res/android">

    <LinearLayout
        android:layout_width="0dp"
        android:layout_height="wrap_content"
        android:layout_margin="8dp"
        android:layout_weight="1"
        android:gravity="center"
        android:orientation="vertical">

        <de.hdodenhof.circleimageview.CircleImageView
            android:layout_width="50dp"
            android:layout_height="50dp"
            android:background="@color/shimmer_bg"
             />

        <TextView
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_marginTop="8dp"
            android:layout_marginBottom="8dp"
            android:gravity="center"
            android:text="Ctg 1"
            android:background="@color/shimmer_bg"
            android:textColor="@color/shimmer_bg" />

    </LinearLayout>

    <LinearLayout
        android:layout_width="0dp"
        android:layout_height="wrap_content"
        android:layout_margin="8dp"
        android:layout_weight="1"
        android:gravity="center"
        android:orientation="vertical">

        <de.hdodenhof.circleimageview.CircleImageView
            android:layout_width="50dp"
            android:layout_height="50dp"
            android:background="@color/shimmer_bg" />

        <TextView
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_marginTop="8dp"
            android:layout_marginBottom="8dp"
            android:gravity="center"
            android:text="Ctg 2"
            android:background="@color/shimmer_bg"
            android:textColor="@color/shimmer_bg" />

    </LinearLayout>

    <LinearLayout
        android:layout_width="0dp"
        android:layout_height="wrap_content"
        android:layout_margin="8dp"
        android:layout_weight="1"
        android:gravity="center"
        android:orientation="vertical">

        <de.hdodenhof.circleimageview.CircleImageView
            android:layout_width="50dp"
            android:layout_height="50dp"
            android:background="@color/shimmer_bg"
            />

        <TextView
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_marginTop="8dp"
            android:layout_marginBottom="8dp"
            android:gravity="center"
            android:text="Ctg 1"
            android:background="@color/shimmer_bg"
            android:textColor="@color/shimmer_bg" />

    </LinearLayout>

    <LinearLayout
        android:layout_width="0dp"
        android:layout_height="wrap_content"
        android:layout_margin="8dp"
        android:layout_weight="1"
        android:gravity="center"
        android:orientation="vertical">

        <de.hdodenhof.circleimageview.CircleImageView
            android:layout_width="50dp"
            android:layout_height="50dp"
            android:background="@color/shimmer_bg" />

        <TextView
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_marginTop="8dp"
            android:layout_marginBottom="8dp"
            android:gravity="center"
            android:text="Ctg 1"
            android:background="@color/shimmer_bg"
            android:textColor="@color/shimmer_bg" />

    </LinearLayout>

    <LinearLayout
        android:layout_width="0dp"
        android:layout_height="wrap_content"
        android:layout_margin="8dp"
        android:layout_weight="1"
        android:gravity="center"
        android:orientation="vertical">

        <de.hdodenhof.circleimageview.CircleImageView
            android:layout_width="50dp"
            android:layout_height="50dp"
            android:background="@color/shimmer_bg" />

        <TextView
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_marginTop="8dp"
            android:layout_marginBottom="8dp"
            android:gravity="center"
            android:text="Ctg 1"
            android:background="@color/shimmer_bg"
            android:textColor="@color/shimmer_bg" />

    </LinearLayout>

</LinearLayout>
`

**Comment by reeshabhkumarranjan** [comment]
I am having the same issue. Image appears as a rectangle. This is my code: https://pastebin.com/s85xdTne This is what it looks like: http://i.imgur.com/TDERbxU.png

**Comment by hdodenhof** [comment]
Please have a look at #320, maybe you ran into the same issue. Also a background drawable will not be cropped to a circle, only the main drawable (set using `android:src` or `setImage[..]`).

**Comment by reeshabhkumarranjan** [comment]
Working now! I had set both `android:background` as well as `android:src` to the drawable.

**Comment by deathcoimgxxx** [comment]
same issue but did not solve by your trick.. suggest something

**Comment by Surya23111998** [comment]
just try Build -> Make Project and it will work fine

**Comment by Kasun123456** [comment]
> just try Build -> Make Project and it will work fine

Thank you.. I had same problem and this one is best option. Build -> Make Project . This is the answer.

**Comment by jadoonhamza810** [comment]
> just try Build -> Make Project and it will work fine

same problem and this option solved it
