### ISSUE TITLE
Black Image, Api 21 

### ISSUE THREAD

**Issue by amansharma-dev** [hdodenhof/CircleImageView#329]
![issue1 1](https://user-images.githubusercontent.com/35025462/55756075-51653380-5a6e-11e9-9874-e67bb8a7804c.png)
![issue1](https://user-images.githubusercontent.com/35025462/55756076-51fdca00-5a6e-11e9-80fe-1637553cea46.png)

**Comment by hdodenhof** [comment]
Duplicate of #31.
