### ISSUE TITLE
Selector on CircleImageView 

### ISSUE THREAD

**Issue by dwivedi** [hdodenhof/CircleImageView#331]
I need to display a check sign on long press on CircleImageView.
How to do this ![]()![Circular imageview on Recyclerview ](https://ibb.co/CB49JcB)

**Comment by MonikaJethani** [comment]
@dwivedi Is this done? Should I look into it, to help you?

**Comment by dwivedi** [comment]
Yes,
Override on setSelected(Boolean flag) of Image view and alter some code
snippet on onDraw method.

Please provide your valuable suggestions on same.
Should I share you my code?

Regards
Ashish

**Comment by hdodenhof** [comment]
I doubt that this is still relevant, but you could have a look at https://github.com/hdodenhof/CircleImageView/issues/153#issuecomment-249692049 and adapt that method to display a checkmark.
