### ISSUE TITLE
version 3.0.0 does not have app:civ_fill_color

### ISSUE THREAD

**Issue by hafiz013** [hdodenhof/CircleImageView#334]
latest version 3.0.0 already remove that function?

**Comment by Sniper1219** [comment]
mute the thread

‫في الجمعة، 17 مايو 2019 في 7:06 ص تمت كتابة ما يلي بواسطة ‪hafiz013‬‏ <‪
notifications@github.com‬‏>:‬

**Comment by hafiz013** [comment]
?????? Sorry i can't understand

**Comment by msoula** [comment]
app:civ_fill_color has been replaced with app:civ_circle_background_color

**Comment by hdodenhof** [comment]
Probably outdated but still: @msoula is right.
