### ISSUE TITLE
My circleImageView is not displaying the src when i run my app 

### ISSUE THREAD

**Issue by franquicidad** [hdodenhof/CircleImageView#341]
Hello i am having the problem is that my app doesnt display the src when i run it on android Studio emulator. The image i upload to src its imported with batch drawable so all version are present for all devices .By the way i migrated to androidx. i think there is no more info to provide.

```
<de.hdodenhof.circleimageview.CircleImageView
                android:id="@+id/circleImageView3"
                android:layout_width="140dp"
                android:layout_height="120dp"
                android:layout_marginTop="-66dp"
                android:src="@drawable/descarga"
                android:elevation="3dp"
                app:layout_constraintBottom_toBottomOf="parent"
                app:layout_constraintEnd_toEndOf="parent"
                app:layout_constraintStart_toStartOf="parent"
                app:layout_constraintTop_toTopOf="parent"
                app:layout_constraintVertical_bias="0.23000002" />
```

![image](https://user-images.githubusercontent.com/28768991/63809922-211d1500-c8e9-11e9-9328-02c860d24fb2.png)

i added elevation to it so that maybe the image was behind the picture but as you see the circle becomes transparent.

**Comment by hdodenhof** [comment]
Is there any log output? Also what kind of drawable is `@drawable/descarga`?

**Comment by hdodenhof** [comment]
Hm, that should actually work. A couple more questions:

- you said it doesn't work on an emulator - does it work on a real device?
- does an image show up when you replace `CircleImageView` with a regular `ImageView`?
- does it work when you use another drawable as `src`?

**Comment by AMK9978** [comment]
I had the same issue, on emulator and real device,
Just add your src image in this field:

![Screenshot from 2019-09-04 15-03-25](https://user-images.githubusercontent.com/35371206/64248006-54812480-cf25-11e9-9b67-23c3c4571cf0.png)

and in your xml code you're gonna have this line of code:
`
                    android:src="@drawable/ic_person_outline_black_24dp"`
hope this works :)

**Comment by hdodenhof** [comment]
I'm closing this as stale for now. In case the issue persists, feel free to reopen with the requested details.

**Comment by yogendrakbkumar** [comment]
![CircleImageView is not showing Circle Image](https://user-images.githubusercontent.com/73631232/97733471-e242aa80-1afd-11eb-9f51-cf12ba35a4a0.png)
![Dependency synced successfully](https://user-images.githubusercontent.com/73631232/97733477-e4a50480-1afd-11eb-9270-0ea77f453466.png)

Circle image view is not showing circle image, it is throwing a square/rectangle. Unable to get where mistaken. Before this time, it was working fine. Can't find where I left the hole, please help, if possible.
