### ISSUE TITLE
CameraX

### ISSUE THREAD

**Issue by tehilaschechter** [hdodenhof/CircleImageView#344]
Is there any way to integrate this with CameraX? To have a circleImageViewer? I would want to use a circle imageImageView instead of the textureView that is generally used.

**Comment by hdodenhof** [comment]
Unfortunately that's not possible as the inner workings of a TextureView are completely different from an ImageView which this library is based upon.

**Comment by tehilaschechter** [comment]
So is it possible to call the circleView, reference it, and set the resource image resource programatically?

**Comment by hdodenhof** [comment]
Yes. It's a drop-in replacement for a regular ImageView and offers the same API.
