### ISSUE TITLE
not works on Android 6.0 or Android 6.0.1，version 3.0.1

### ISSUE THREAD

**Issue by loquitowen** [hdodenhof/CircleImageView#345]
my xml is below 

```
<?xml version="1.0" encoding="utf-8"?>
<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:background="@drawable/bg_login">
    <de.hdodenhof.circleimageview.CircleImageView
        android:id="@+id/avatar"
        android:layout_height="100dp"
        android:layout_width="100dp"
        android:layout_marginTop="250dp"
        android:layout_centerHorizontal="true"
        android:src="@drawable/final_logo"
        android:layout_marginRight="16dp"/>
    </RelativeLayout>
```

the error is below

Error inflating class de.hdodenhof.circleimageview.CircleImageView

**Comment by hdodenhof** [comment]
Please post the full stack trace of the error - it's impossible to tell what's causing this without it. Thanks!

**Comment by loquitowen** [comment]
full xml 
<?xml version="1.0" encoding="utf-8"?>
<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:background="@drawable/bg_login">
    <de.hdodenhof.circleimageview.CircleImageView
        android:id="@+id/avatar"
        android:layout_height="100dp"
        android:layout_width="100dp"
        android:layout_marginTop="250dp"
        android:layout_centerHorizontal="true"
        android:src="@drawable/final_logo"
        android:layout_marginRight="16dp"/>
    <RelativeLayout
        android:layout_width="fill_parent"
        android:layout_height="wrap_content"
        android:layout_alignParentBottom="true"
        android:layout_marginBottom="100dp">
        <TextView
            android:id="@+id/title"
            style="@style/deail_title_text_style"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_centerHorizontal="true"
            android:text="AAAAAAA"
            android:textColor="@color/white"
            android:textSize="24sp"
            android:textStyle="bold"
            android:layout_marginLeft="10dp"
            android:layout_marginRight="10dp"
            android:singleLine="true"
            />
        <TextView
            android:id="@+id/title2"
            style="@style/deail_title_text_style"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_centerHorizontal="true"
            android:text="BBBBBB"
            android:layout_below="@+id/title"
            android:textColor="@color/white"
            android:textSize="24sp"
            android:textStyle="bold"
            android:layout_marginLeft="10dp"
            android:layout_marginRight="10dp"
            android:singleLine="true"

            />
    </RelativeLayout>
</RelativeLayout>

full error09-25 17:41:46.327 11213-11213/com.gxdlr.hczhjg E/FileLogger: /storage/emulated/0/frtech/gooffice is not a writable 09-25 17:41:46.817 11213-11213/com.gxdlr.hczhjg E/AndroidRuntime: FATAL EXCEPTION: main     Process: com.gxdlr.hczhjg, PID: 11213     java.lang.RuntimeException: Unable to start activity ComponentInfo{com.gxdlr.hczhjg/com.gxdlr.hczhjg.ui.SplashActivity}: android.view.InflateException: Binary XML file line #6: Binary XML file line #6: Error inflating class de.hdodenhof.circleimageview.CircleImageView         at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2416)         at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)         at android.app.ActivityThread.-wrap11(ActivityThread.java)         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)         at android.os.Handler.dispatchMessage(Handler.java:102)         at android.os.Looper.loop(Looper.java:148)         at android.app.ActivityThread.main(ActivityThread.java:5422)         at java.lang.reflect.Method.invoke(Native Method)         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)         at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:107)      Caused by: android.view.InflateException: Binary XML file line #6: Binary XML file line #6: Error inflating class de.hdodenhof.circleimageview.CircleImageView         at android.view.LayoutInflater.inflate(LayoutInflater.java:539)         at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)         at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:360)         at android.view.LayoutInflater.inflate(<Xposed>)         at android.view.LayoutInflater.inflate(LayoutInflater.java:423)         at android.view.LayoutInflater.inflate(LayoutInflater.java:374)         at com.android.internal.policy.PhoneWindow.setContentView(PhoneWindow.java:393)         at android.app.Activity.setContentView(Activity.java:2172)         at com.gxdlr.hczhjg.ui.SplashActivity.onCreate(SplashActivity.java:54)         at android.app.Activity.performCreate(Activity.java:6251)         at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)         at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369)         at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)          at android.app.ActivityThread.-wrap11(ActivityThread.java)          at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)          at android.os.Handler.dispatchMessage(Handler.java:102)          at android.os.Looper.loop(Looper.java:148)          at android.app.ActivityThread.main(ActivityThread.java:5422)          at java.lang.reflect.Method.invoke(Native Method)          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)          at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:107)       Caused by: android.view.InflateException: Binary XML file line #6: Error inflating class de.hdodenhof.circleimageview.CircleImageView         at android.view.LayoutInflater.createView(LayoutInflater.java:645)         at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:764)         at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:704)         at android.view.LayoutInflater.rInflate(LayoutInflater.java:835)         at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798)         at android.view.LayoutInflater.inflate(LayoutInflater.java:515)         at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)          at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:360)          at android.view.LayoutInflater.inflate(<Xposed>)          at android.view.LayoutInflater.inflate(LayoutInflater.java:423)          at android.view.LayoutInflater.inflate(LayoutInflater.java:374)          at com.android.internal.policy.PhoneWindow.setContentView(PhoneWindow.java:393)          at android.app.Activity.setContentView(Activity.java:2172)          at com.gxdlr.hczhjg.ui.SplashActivity.onCreate(SplashActivity.java:54)          at android.app.Activity.performCreate(Activity.java:6251)          at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)          at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369)          at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)          at android.app.ActivityThread.-wrap11(ActivityThread.java)          at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)          at android.os.Handler.dispatchMessage(Handler.java:102)          at android.os.Looper.loop(Looper.java:148)          at android.app.ActivityThread.main(ActivityThread.java:5422)          at java.lang.reflect.Method.invoke(Native Method)          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)          at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:107)       Caused by: java.lang.reflect.InvocationTargetException         at java.lang.reflect.Constructor.newInstance(Native Method)         at android.view.LayoutInflater.createView(LayoutInflater.java:619)         at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:764)          at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:704)          at android.view.LayoutInflater.rInflate(LayoutInflater.java:835)          at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798)          at android.view.LayoutInflater.inflate(LayoutInflater.java:515)          at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)          at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:360)          at android.view.LayoutInflater.inflate(<Xposed>)          at android.view.LayoutInflater.inflate(LayoutInflater.java:423)          at android.view.LayoutInflater.inflate(LayoutInflater.java:374)          at com.android.internal.policy.PhoneWindow.setContentView(PhoneWindow.java:393)          at android.app.Activity.setContentView(Activity.java:2172)          at com.gxdlr.hczhjg.ui.SplashActivity.onCreate(SplashActivity.java:54)          at android.app.Activity.performCreate(Activity.java:6251)          at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)          at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369)          at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)          at android.app.ActivityThread.-wrap11(ActivityThread.java)          at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)          at android.os.Handler.dispatchMessage(Handler.java:102)          at android.os.Looper.loop(Looper.java:148)          at android.app.ActivityThread.main(ActivityThread.java:5422)          at java.lang.reflect.Method.invoke(Native Method)          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)          at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:107)       Caused by: java.lang.OutOfMemoryError: Failed to allocate a 252407244 byte allocation with 16777216 free bytes and 128MB until OOM         at dalvik.system.VMRuntime.newNonMovableArray(Native Method)         at android.graphics.BitmapFactory.nativeDecodeAsset(Native Method)         at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:609)         at android.graphics.BitmapFactory.decodeResourceStream(BitmapFactory.java:444)         at android.graphics.drawable.Drawable.createFromResourceStream(Drawable.java:1080)         at android.content.res.Resources.loadDrawableForCookie(Resources.java:2598)         at android.content.res.Resources.loadDrawable(Resources.java:2503)         at android.content.res.TypedArray.getDrawable(TypedArray.java:870)         at android.content.res.XResources$XTypedArray.getDrawable(XResources.java:1363)         at android.widget.ImageView.<init>(ImageView.java:152)         at android.widget.ImageView.<init>(ImageView.java:140)         at de.hdodenhof.circleimageview.CircleImageView.<init>(CircleImageView.java:98)         at de.hdodenhof.circleimageview.CircleImageView.<init>(CircleImageView.java:94)         at java.lang.reflect.Constructor.newInstance(Native Method)          at android.view.LayoutInflater.createView(LayoutInflater.java:619)          at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:764)          at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:704)          at android.view.LayoutInflater.rInflate(LayoutInflater.java:835)          at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798)          at android.view.LayoutInflater.inflate(LayoutInflater.java:515)          at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)          at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:360)          at android.view.LayoutInflater.inflate(<Xposed>)          at android.view.LayoutInflater.inflate(LayoutInflater.java:423)          at android.view.LayoutInflater.inflate(LayoutInflater.java:374)          at com.android.internal.policy.PhoneWindow.setContentView(PhoneWindow.java:393)          at android.app.Activity.setContentView(Activity.java:2172)          at com.gxdlr.hczhjg.ui.SplashActivity.onCreate(SplashActivity.java:54)          at android.app.Activity.performCreate(Activity.java:6251)          at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)          at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369)          at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)          at android.app.ActivityThread.-wrap11(ActivityThread.java)          at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)          at android.os.Handler.dispatchMessage(Handler.java:102)          at android.os.Looper.loop(Looper.java:148)          at android.app.ActivityThread.main(ActivityThread.java:5422)          at java.lang.reflect.Method.invoke(Native Method)          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)          at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:107)  




------------------ 原始邮件 ------------------
发件人: "Henning Dodenhof"<notifications@github.com>;
发送时间: 2019年9月25日(星期三) 下午5:38
收件人: "hdodenhof/CircleImageView"<CircleImageView@noreply.github.com>;
抄送: "Loquito"<mosquito.ix@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [hdodenhof/CircleImageView] not works on Android 6.0 or Android 6.0.1，version 3.0.1 (#345)




Please post the full stack trace of the error - it's impossible to tell what's causing this without it. Thanks!

**Comment by hdodenhof** [comment]
The root cause is an `OutOfMemoryError`:
```
java.lang.OutOfMemoryError: Failed to allocate a 252407244 byte allocation with 16777216 free bytes and 128MB until OOM
```

You are trying to load a huge image with an in-memory size of about 250MB. Resizing `@drawable/final_logo` should fix this.

**Comment by loquitowen** [comment]
its only 613KB,does the resolution matter it？
------------------ 原始邮件 ------------------
发件人: "Henning Dodenhof"<notifications@github.com>;
发送时间: 2019年9月25日(星期三) 下午5:54
收件人: "hdodenhof/CircleImageView"<CircleImageView@noreply.github.com>;
抄送: "Loquito"<mosquito.ix@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [hdodenhof/CircleImageView] not works on Android 6.0 or Android 6.0.1，version 3.0.1 (#345)




The root cause is an OutOfMemoryError:
 java.lang.OutOfMemoryError: Failed to allocate a 252407244 byte allocation with 16777216 free bytes and 128MB until OOM  
You are trying to load a huge image with an in-memory size of about 250MB. Resizing @drawable/final_logo should fix this.

**Comment by hdodenhof** [comment]
Yes, the resolution matters. When loaded into memory, each individual pixel requires a fixed amount of space, independent of the size of the original file.

**Comment by loquitowen** [comment]
ok,thanks

**Comment by loquitowen** [comment]
i put the png in the drawble...that's wrong,move it to the other 3 is ok
