### ISSUE TITLE
API 'variant.getExternalNativeBuildTasks()' is obsolete and has been replaced with 'variant.getExternalNativeBuildProviders()'.

### ISSUE THREAD

**Issue by lazarberbakov** [hdodenhof/CircleImageView#354]
Dear,
I find the following warning when I build the app , and it points me to your library.
Could you suggest how to solve this issue?

Thank you in advance!

INFO: API 'variant.getExternalNativeBuildTasks()' is obsolete and has been replaced with 'variant.getExternalNativeBuildProviders()'.
It will be removed at the end of 2019.
For more information, see https://d.android.com/r/tools/task-configuration-avoidance.
To determine what is calling variant.getExternalNativeBuildTasks(), use -Pandroid.debug.obsoleteApi=true on the command line to display more information.
Affected Modules: app

**Comment by hdodenhof** [comment]
I can't imagine that it's caused by this library. What is it that points you in this direction?

**Comment by lazarberbakov** [comment]
Sorry, it was my mistake. It is working now.
