### ISSUE TITLE
implementation 'de.hdodenhof:circleimageview:3.0.1'

### ISSUE THREAD

**Issue by AlamPixel** [hdodenhof/CircleImageView#355]
I am having a issue where I try to use CircleImage ver. 3.0.1 but when I try to sync my project it gives me the following error:
Gradle DSL method not found: 'implementation()'
Possible causes:
The project 'LoveMessenger' may be using a version of the Android Gradle plug-in that does not contain the method (e.g. 'testCompile' was added in 1.1.0).
Upgrade plugin to version 3.5.3 and sync project

The project 'LoveMessenger' may be using a version of Gradle that does not contain the method.
Open Gradle wrapper file

The build file may be missing a Gradle plugin.
Apply Gradle plugin

I have no clue what is wrong since I am updated to gradle-5.4.1-all.zip and Android plugin to 3.5.3
Help is appreciated.

**Comment by willigro** [comment]
You can share your gradle?

**Comment by AlamPixel** [comment]
buildscript {
    ext.kotlin_version = '1.3.41'
    repositories {
        google()
        jcenter()
        
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.5.3'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
        classpath 'com.google.gms:google-services:4.3.2'
    }
}

allprojects {
//      version = VERSION_NAME
  //      group = GROUP
        repositories {
            google()
            jcenter()
        }
    }

task clean(type: Delete) {
    delete rootProject.buildDir
}
~~~~~~~~~
apply plugin: 'com.android.application'

apply plugin: 'kotlin-android'

apply plugin: 'kotlin-android-extensions'

android {
    compileSdkVersion 29
    buildToolsVersion "29.0.2"
    defaultConfig {
        applicationId "com.example.lovemessenger"
        minSdkVersion 17
        targetSdkVersion 29
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation"org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
    implementation 'androidx.appcompat:appcompat:1.0.2'
    implementation 'androidx.core:core-ktx:1.0.2'
    implementation 'androidx.constraintlayout:constraintlayout:1.1.3'
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'androidx.test:runner:1.1.1'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.1.1'

    implementation 'com.google.firebase:firebase-analytics:17.2.1'
    implementation 'com.google.firebase:firebase-auth:19.2.0'
    implementation 'com.google.firebase:firebase-storage:19.1.0'
    implementation 'com.google.firebase:firebase-database:19.2.0'}

   //implementation 'de.hdodenhof:circleimageview:2.2.0'

apply plugin: 'com.google.gms.google-services'
~~~~~~~~~~~~~~~
distributionBase=GRADLE_USER_HOME
distributionPath=wrapper/dists
zipStoreBase=GRADLE_USER_HOME
zipStorePath=wrapper/dists
distributionUrl=https\://services.gradle.org/distributions/gradle-5.4.1-all.zip

**Comment by hdodenhof** [comment]
You placed `implementation 'de.hdodenhof:circleimageview:2.2.0'` outside of the `dependencies` block.

**Comment by AlamPixel** [comment]
Thank you so much for this @hdodenhof
