### ISSUE TITLE
The image gets slightly distorted on pixel perfect images

### ISSUE THREAD

**Issue by rocboronat** [hdodenhof/CircleImageView#356]
Hi everyone! Here's a very picky image distortion bug.

I have a 56dp widget with an 8dp padding. On the other side, I have pixel-perfect images made at 40dp (it's 56dp - 8dp * 2 sides).

If I apply those images to an `ImageView`, the result is pixel-perfect. But if I replace that `ImageView` with a `CircleImageView`, the result is not pixel-perfect anymore.

Thinking about it, I think that `CircleImageView` is getting the 40dp image, then resizing it to 56dp, and then applying the padding and resizing the image again to 40dp.

Here are some screenshots. First a comparison, and then a screenshot of every case:

Comparing side by side:
![Comparison](https://user-images.githubusercontent.com/456499/71582867-3f4f8780-2b0c-11ea-962d-2001d546cf72.png)

Using the plain `ImageView`:
![ImageView](https://user-images.githubusercontent.com/456499/71582878-4aa2b300-2b0c-11ea-8b6d-4f375b036a21.jpg)

Using `CircleImageView`:
![CicleImageView](https://user-images.githubusercontent.com/456499/71582887-55f5de80-2b0c-11ea-95c9-5d33cd39e952.jpg)

By the way, I'm using a local .png file. No network or strange things there.

Thanks again for your work! And happy New Year 😃 🎆 🎆 🎆

**Comment by rocboronat** [comment]
I've thought that having a common 40dp without padding (that I used to have a bigger touchable area) would fix the issue... but nope. A 40dp `CircleImageView` with a 40dp image still has the issue.

![Comparison](https://user-images.githubusercontent.com/456499/71583204-b6395000-2b0d-11ea-9140-be587abf8ab1.png)

There are this widgets:

```xml
<de.hdodenhof.circleimageview.CircleImageView
    style="@style/fast_share_button"
    android:src="@drawable/ic_share_default" />

<de.hdodenhof.circleimageview.CircleImageView
    style="@style/fast_share_button"
    android:src="@drawable/ic_share_default"
    android:rotation="@integer/rtl_rotation"/>

<ImageView
    style="@style/fast_share_button"
    android:src="@drawable/ic_share_default"
    android:rotation="@integer/rtl_rotation"/>
```

And the style is:
```xml
<style name="fast_share_button">
    <item name="android:layout_width">@dimen/icon_fast_share</item>
    <item name="android:layout_height">@dimen/icon_fast_share</item>
    <item name="android:layout_margin">@dimen/padding_medium</item>
    <item name="android:foreground">@drawable/ripple_on_transparent_round</item>
</style>
```

**Comment by hdodenhof** [comment]
Hi @rocboronat,

thanks for the detailed report! I just tried to reproduce your issue but wasn't successful so far. Using a 40dp image with 40dp widgets this is what I get:
![image](https://user-images.githubusercontent.com/1824223/71617657-5352c200-2bbc-11ea-8a66-9f33194bae92.png)

I'm currently a little lost as to what might be causing the issue for you. Does this happen on all devices? Does this only happen with the share icon or any pixel-perfect icon of that size? Can you reproduce the issue dropping the image in question into the sample app?

**Comment by hdodenhof** [comment]
I just pushed a small change to `feature/bitmap-filtering` ([diff](https://github.com/hdodenhof/CircleImageView/compare/feature/bitmap-filtering?expand=1)) - could you try and see if that changes anything?

You can switch to the feature branch by adding the jitpack repository to your build file and replacing the `CircleImageView` dependency:

```
repositories {
    ...
    maven { url 'https://jitpack.io' }
}

dependencies {
    ...
    implementation 'com.github.hdodenhof:CircleImageView:feature~bitmap-filtering-SNAPSHOT'
}
```

Thanks!

**Comment by rocboronat** [comment]
Of course I will, @hdodenhof! Thanks for getting dirt in your hands today 😄

**Comment by hdodenhof** [comment]
@rocboronat Have you had a chance to try out the tweak yet?

**Comment by rocboronat** [comment]
Nope, I've been focused in marketing things and didn't have space to try it. But I have it on mind. Thanks for the patience! :·)

**Comment by hdodenhof** [comment]
:ok_hand:

**Comment by rocboronat** [comment]
Good morning @hdodenhof ! 🌞

Here's a comparison between master and your patch branch:
![Comparison](https://user-images.githubusercontent.com/456499/73131222-7039b400-4007-11ea-8ecc-e686e5d5cd84.png)

You fixed it! 👏🙇 

If you want to see the issue by yourself, before we update the app, download [QuitNow!](https://play.google.com/store/apps/details?id=com.EAGINsoftware.dejaloYa) and check the flags in the top right corner.

I'm so glad I opened this issue. I think it happened for years... I always had it in my "I will investigate this slight issue someday" because I thought that the issue was related to the image itself... and well, you fixed it with a line of code. Hell yeah! 🎉

Thanks a lot and congrats for the good work 😃

**Comment by hdodenhof** [comment]
Hi @rocboronat,

that's great to hear! I'll try to prepare a new release today or tomorrow at latest so you don't need to rely on a temporary feature branch.

What's a little strange though is that the change should only have an effect if scaling is involved - which shouldn't be the case for pixel perfect images... :thinking:  I'll try to get to the bottom of this when I find some time.

I'll update this once the new release is ready.

Cheers!

**Comment by rocboronat** [comment]
Thanks a lot! 🚀

**Comment by hdodenhof** [comment]
`v3.1.0` with the change is released and should be available on MavenCentral and jCenter.

**Comment by rocboronat** [comment]
Awesome! Thanks for that quick release, @hdodenhof 

Releasing to production in 3, 2, 1... 😄
