### ISSUE TITLE
Drawable with colorFilter

### ISSUE THREAD

**Issue by radon** [hdodenhof/CircleImageView#36]
Hi man, 
thanks for sharing your work with us.
Working with your library I discover a problem with drawable and color filter.
If i write something like:
`Drawable drawable =  getResources().getDrawable(R.drawable.generic_image);
drawable.setColorFilter(COLOR.RED, PorterDuff.Mode.SRC_IN);
circleImageView.setImageDrawable(drawable);`

The drawable will be load correctly but without the color filter.
Using the same code with a normal ImageView the drawable will be rendered correctly.
This problem can be generated with every image (advice: use a gray image the color filter will be more effective).
I'm here if you need more info.
Thanks again.

**Comment by hdodenhof** [comment]
This has actually been fixed just three days ago, see #29 for reference. I still need to push a new version to Maven Central though. Leaving this issue open until that's done - shouldn't be to long.

For the `ColorFilter` to work you have to apply it to the `View`, e.g. `circleImageView.setColorFilter(new PorterDuffColorFilter(COLOR.RED, PorterDuff.Mode.SRC_IN)`.

**Comment by radon** [comment]
There is a chance in near future you add this compatibility for drawable too? In my case it will be really useful because i can use with picasso a drawable with its colorfilter for placeholder and then load from network the image i need without clear the color filter from the view. Thank you in any case for the help.

**Comment by traninho** [comment]
Hi, thanks for the lib. When we can expect a release with the issue fixed?

**Comment by hdodenhof** [comment]
I'm sorry for the delay, v1.2.2 with ColorFilter support is now on it's way to MavenCentral.
