### ISSUE TITLE
Problem with background color

### ISSUE THREAD

**Issue by franquicidad** [hdodenhof/CircleImageView#361]
Hello i am retreiving a value from a database for a background color with the reference for example #FAFAFA how can i set the background with this color. Thank you for this library by the way, im using java.

**Comment by hdodenhof** [comment]
You need to use `Color.parseColor(String colorString)` to parse the color string and pass the resulting color-int to `setCircleBackgroundColor(int circleBackgroundColor)`:

```
CircleImageView civ = [...];

String colorString = "#FAFAFA";
int color = Color.parseColor(colorString);
civ.setCircleBackgroundColor(color);
```

**Comment by franquicidad** [comment]
Hello!
![Captura de pantalla 2020-01-22 a la(s) 10 05 01 p m](https://user-images.githubusercontent.com/28768991/72953523-698b1280-3d63-11ea-9c3c-a3bc7eac8e91.png)

i am receiving a number format exception with what you suggested.

**Comment by hdodenhof** [comment]
Your `refColor` seems to end with a linebreak - you need to remove that.

**Comment by franquicidad** [comment]
Hello i solved the crash issue and was indeed what you said thank you for that. After this is still no setting the background color.Do you need some kind of debugging info let me know. thank you.

**Comment by hdodenhof** [comment]
The `circleBackgroundColor` will only be used if you also set an image. The general idea is that the background color is only visible if the provided image contains some transparent areas. What is it you want to achieve? If you just want to show a circle with a specific color you could use a `ColorDrawable`:

```
CircleImageView civ = [...];

String colorString = "#FAFAFA";
int color = Color.parseColor(colorString);
ColorDrawable cd = new ColorDrawable(color);
civ.setImageDrawable(cd);
```

**Comment by hdodenhof** [comment]
Closing for now. Feel free to reopen if you need any more help.
