### ISSUE TITLE
Polygonal shape with active "elevation" and vector drawable

### ISSUE THREAD

**Issue by gmikhail** [hdodenhof/CircleImageView#365]
```
<de.hdodenhof.circleimageview.CircleImageView
        android:id="@+id/select"
        android:layout_width="56dp"
        android:layout_height="56dp"
        android:layout_gravity="center"
        android:src="@drawable/ic_check_circle_24dp"
        android:elevation="8dp"/>
```

![Screenshot_1581230105](https://user-images.githubusercontent.com/4838367/74097646-460fe800-4b17-11ea-9285-15836be948a0.png)

When elevation 0 or image not vector - shape is round.

**Comment by hdodenhof** [comment]
As stated in the [FAQ](https://github.com/hdodenhof/CircleImageView#faq) vector drawables shouldn't be used with `CircleImageView` - it's a bit of a surprise it works at all. Not sure where the octagon come from though, but if it works with a non-vector drawable, it's out-of-scope of this library.

**Comment by gmikhail** [comment]
@hdodenhof It works with a non-vector drawable. It is a pity that vector images are not officially supported. I had no performance issues when using vector icons with `CircleImageView `.
