### ISSUE TITLE
How can I set Background color programatically? It's becoming Square shaped if I do so

### ISSUE THREAD

**Issue by NeerajaGandla** [hdodenhof/CircleImageView#366]
I have an ImageView. It should be filled with a color dynamically. When I set Background color, it's appearing as a normal ImageView with square shape. How can we achieve this in circular shape?

**Comment by hdodenhof** [comment]
Please have a look at [this comment](https://github.com/hdodenhof/CircleImageView/issues/361#issuecomment-577784544) - does that work for you?

**Comment by NeerajaGandla** [comment]
It worked. Thanks
