### ISSUE TITLE
ERROR: Could not get unknown property 'GROUP' for object of type org.gradle.api.publication.maven.internal.deployer.DefaultGroovyMavenDeployer.

### ISSUE THREAD

**Issue by dgimenezrodriguezm8** [hdodenhof/CircleImageView#368]
Hello. Can you help me please? I download your project, descompress, import, put dependences into file app from gradle... but  I see this line of error:
ERROR: Could not get unknown property 'GROUP' for object of type org.gradle.api.publication.maven.internal.deployer.DefaultGroovyMavenDeployer.
Please new put you big library in mi project for create circle images. Thanks! It's great. :)

**Comment by hdodenhof** [comment]
If you just want to use `CircleImageView` in your project, you don't need to download/extract/import anything - just add a new entry to the dependencies block in your build file, please have a look at the [README](https://github.com/hdodenhof/CircleImageView#gradle) for details.
