### ISSUE TITLE
civ_circle_background_color not working

### ISSUE THREAD

**Issue by mehdico** [hdodenhof/CircleImageView#371]
Hi,
civ_circle_background_color in xml And setCircleBackgroundColor in java are not working on Android 9.
Also, I've tested setCircleBackgroundColorResource and it's not working.

**Comment by hdodenhof** [comment]
The `circleBackgroundColor` is currently only used if you also set an image. The general idea so far was that the background color is only visible if the provided image contains some transparent areas. This is going to change in the future though. For now you could just use a `ColorDrawable` as image if you want to show a circle with a specific color .

**Comment by mehdico** [comment]
Thank you. its works on API 16 so maybe may confuse some users.

**Comment by hdodenhof** [comment]
Unfortunately I cannot reproduce a difference in behavior between Android 9 and other API levels. Can you provide more details about what you are doing (i.e. code samples) and what the different behaviors are? Thanks!
