### ISSUE TITLE
Request new feature (circular ripple)

### ISSUE THREAD

**Issue by flashiran1** [hdodenhof/CircleImageView#372]
Hi, please click on the CircleImageView to add a circular ripple option tanks

**Comment by hdodenhof** [comment]
Please have a look at https://github.com/hdodenhof/CircleImageView/issues/153#issuecomment-249692049 - is that an option in your case?

**Comment by flashiran1** [comment]
Yes that's what I want But please add the default in the library No we need to create xml separately

**Comment by hdodenhof** [comment]
I won't add this to the library itself as it would need lots of configurations options to fit the different needs of different projects. Using the XML variant is the right way to do it.
