### ISSUE TITLE
Edges getting cut if we use elevation.

### ISSUE THREAD

**Issue by nareshkatta99** [hdodenhof/CircleImageView#374]
When we use elevation,
The edges are getting cut.

![CircleImageView](https://user-images.githubusercontent.com/7877291/77047503-daa91800-69ea-11ea-9b31-78c27891acc4.png)

Code I'm using:

                <FrameLayout
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    android:layout_gravity="center">

                    <de.hdodenhof.circleimageview.CircleImageView
                        android:id="@+id/profilePic"
                        android:layout_width="40dp"
                        android:layout_height="40dp"
                        android:layout_gravity="center"
                        android:layout_marginTop="2dp"
                        android:elevation="3dp"
                        android:src="@drawable/ic_user_profile" />

                    <ImageView
                        android:id="@+id/tick"
                        android:layout_width="16dp"
                        android:layout_height="16dp"
                        android:layout_gravity="end"
                        android:elevation="3dp"
                        android:outlineProvider="none"
                        android:src="@drawable/tick" />
                </FrameLayout>

**Comment by hdodenhof** [comment]
You need to add `android:clipChildren="false"` to the `FrameLayout` and, depending on your view hierarchy, to even more parent view groups.

**Comment by nareshkatta99** [comment]
Not working if the parent main parent is card view
Hierarchy is

    <androidx.cardview.widget.CardView
        <LinearLayout android:orientation="vertical"
            <LinearLayout android:orientation="horizontal"
                <FrameLayout
                    <de.hdodenhof.circleimageview.CircleImageView

**Comment by hdodenhof** [comment]
Unfortunately I cannot reproduce your issue. If I set `clipChildren="false"` on all view groups up to and including `CardView`, it works as expected.

**Comment by hdodenhof** [comment]
You might also have to set `clipToPadding="false"` on view groups with padding.

**Comment by nareshkatta99** [comment]
Here is the code of the hierarchy

    <androidx.cardview.widget.CardView xmlns:android="http://schemas.android.com/apk/res/android"
        xmlns:card_view="http://schemas.android.com/apk/res-auto"
        xmlns:tools="http://schemas.android.com/tools"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:clipChildren="false"
        android:clipToPadding="false"
        card_view:cardBackgroundColor="@color/white"
        card_view:cardCornerRadius="10dp"
        card_view:cardElevation="2dp"
        card_view:cardPreventCornerOverlap="false"
        card_view:cardUseCompatPadding="true"
        card_view:contentPaddingBottom="5dp"
        card_view:contentPaddingTop="5dp">
        <LinearLayout
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:clipChildren="false"
            android:orientation="vertical">

            <LinearLayout
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:clipChildren="false"
                android:orientation="horizontal"
                android:padding="3dp">
                <FrameLayout
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    android:clipChildren="false"
                    android:paddingLeft="10dp"
                    android:paddingRight="10dp">
                    <de.hdodenhof.circleimageview.CircleImageView
                        android:id="@+id/profilePic"
                        android:layout_width="40dp"
                        android:layout_height="40dp"
                        android:layout_gravity="center"
                        android:layout_marginTop="2dp"
                        android:elevation="3dp"
                        android:src="@drawable/ic_user_profile" />

**Comment by nareshkatta99** [comment]
If you are not able to reproduce,
You can close the issue.
I found a workaround for now.
Adding extra padding of same as elevation fixed my issue.

**Comment by hdodenhof** [comment]
Have you seen my second comment?
> You might also have to set `clipToPadding="false"` on view groups with padding.

Adding that option to the `FrameLayout` and `LinearLayout` with padding should do the trick.

**Comment by nareshkatta99** [comment]
This one also helped me.
Thank you.
