### ISSUE TITLE
Inefficient API is used

### ISSUE THREAD

**Issue by cataloque** [hdodenhof/CircleImageView#381]
Dear developers,
I found an API, setImageURI(), is used in CircleImageView . For setImageURI(), Google says this: " This does Bitmap reading and decoding on the UI thread, which can cause a latency hiccup. ”
In addition, using this method to create a picture cannot handle the picture size. If the loaded picture is too large, it may cause OOM.
If that's a concern, consider using setImageDrawable(android.graphics.drawable.Drawable) or setImageBitmap(android.graphics.Bitmap) and BitmapFactory instead.

Thanks.

**Comment by hdodenhof** [comment]
`CircleImageView` mimics the API of a regular `ImageView` - that's by design.
