### ISSUE TITLE
getting issue while adding dependencies

### ISSUE THREAD

**Issue by ronan2242** [hdodenhof/CircleImageView#382]
I have just started working with android studio and i got a error while adding the dependencies to my gradle file. 
ERROR: Unable to resolve dependency for ':app@debugUnitTest/compileClasspath': Could not resolve com.mikhaellopez:circularimageview:4.2.0.
Disable offline mode and sync project
Show Details
Affected Modules: app
please help me

**Comment by hdodenhof** [comment]
`com.mikhaellopez:circularimageview:4.2.0` is not this library.
