### ISSUE TITLE
"feature~transition-drawable-support-SNAPSHOT" not found

### ISSUE THREAD

**Issue by littledot** [hdodenhof/CircleImageView#388]
Got an error today syaing that `com.github.hdodenhof:CircleImageView:feature~transition-drawable-support-SNAPSHOT` cannot be found.

Anyone else seeing this?

**Comment by hdodenhof** [comment]
The `feature-transition-drawable-support` branch has been deleted after it was merged into `master`.
You can use `com.github.hdodenhof:CircleImageView:master-SNAPSHOT` instead.

**Comment by littledot** [comment]
Appreciate the quick reply!
