### ISSUE TITLE
Image stretch

### ISSUE THREAD

**Issue by billy9222** [hdodenhof/CircleImageView#391]
If I take image from camer and set it, It stretches the image. Any Idea why ?

**Comment by hdodenhof** [comment]
As `CircleImageView` always uses `SCALE_TYPE.CENTER_CROP`, it doesn't do any stretching. Might be something that happens before you set the image on the `CircleImageView`.

**Comment by billy9222** [comment]
Images taken from Gallery are working fine but not with camera

**Comment by hdodenhof** [comment]
Well, that's a clear sign that the cause is outside of `CircleImageView`, as it doesn't know where the images come from. You might need to verify how you handle the images you get from the camera - maybe head over to StackOverflow for support. Closing this as it's not an issue with this library.
