### ISSUE TITLE
The picture still shows the original square

### ISSUE THREAD

**Issue by byman577** [hdodenhof/CircleImageView#398]
I tried many kinds of custom imageviews, but none of them can display the circle. Now I tried yours but also failed. This is too bad.,I do not know whehe is wrong What should I do?

**Comment by mohaka1386** [comment]
hi!
I am not sure this is your problem or not but
don't trust to the android graphic assistant!
just run your app and it will be fine.
excuse me if there is any typic problem.

**Comment by byman577** [comment]
Yes i should not trust to the android graphic assistant!
Thanks very much !

**Comment by mohaka1386** [comment]
you're welcome.
I am really happy that I could help you
