### ISSUE TITLE
Shadow effect

### ISSUE THREAD

**Issue by akohout** [hdodenhof/CircleImageView#4]
Will it be possible to add shadows to the CircleImageView? Or is it already possible and I just don't know why? :-)

**Comment by LyndonChin** [comment]
I have just submitted a Pull Request, before the author accept it, you could find the source here 
https://github.com/LyndonChin/CircleImageView

**Comment by hafiz013** [comment]
https://github.com/hdodenhof/CircleImageView/issues/4#issuecomment-74015363. <--- this link died
