### ISSUE TITLE
Background drawable does not draw to circle

### ISSUE THREAD

**Issue by mayur-mi** [hdodenhof/CircleImageView#41]
I am having issues when i set the background of the circular image view. The resource specified in the background dows not draw to circle.
Basically, I am having a trapsparent background image, If I do not set the background, the view in the back of circular image view gets displated in the remaining space. But when i try to set the background resource (Basically a color), it is being drawn to full layout (REMAINING SPACE OUTSIDE THE CIRCLE {AS CircleImageView is basically a rectangular canvas, with a circular image on top of it.})

**Comment by hdodenhof** [comment]
Duplicate of #26.
