### ISSUE TITLE
I encountered a problem when using Glide to load pictures, the pictures do not display

### ISSUE THREAD

**Issue by Mashiro2019** [hdodenhof/CircleImageView#410]
```kt
Glide.with(this)
                .load(objects.meDataResponse.avatar)
                .into(binding.navigationView.findViewById<CircleImageView>(R.id.profileImage))
```

The profileImage view cannot display the corresponding picture

**Comment by hdodenhof** [comment]
Does it work when you replace the `CircleImageView` in your layout with a regular `imageView`?

**Comment by Mashiro2019** [comment]
Thank you very much for your reply, I have found the problem, it seems that my link cannot be loaded normally because my link starts with http.I modified the link as follows
```kt
val avatarUrl:String = objects.meDataResponse.avatar.replace("http://", "https://")
Glide.with(ApplicationUtils.context)
                .load(avatarUrl).into(binding.navigationView.findViewById<CircleImageView>(R.id.profileImage))
```
So it can run normally
Thank you again for your reply, I wish you a happy life and happy every day

**Comment by hdodenhof** [comment]
That's great to hear.
Thanks, you too!
