### ISSUE TITLE
What to do : Into the Sunset on May 1st: Bintray, JCenter, GoCenter, and ChartCenter

### ISSUE THREAD

**Issue by aslamhossin** [hdodenhof/CircleImageView#411]
UPDATE: To better support the community in this migration, JFrog has extended the JCenter new package versions submission deadline through March 31st, 2021.

To clarify, the JCenter repository will keep serving packages for 12 months until February 1st 2022. Only the JCenter REST API and UI will be sunsetted on May 1st, 2021.

**Comment by hdodenhof** [comment]
This doesn't concern `CircleImageView` as it is hosted on Maven Central.
