### ISSUE TITLE
can I pass a letter and showed as Image ?

### ISSUE THREAD

**Issue by Abdelsattar** [hdodenhof/CircleImageView#414]
is there any way that I can pass a letter in case of error to be shown inside the image view?

**Comment by deepak-prajapatii** [comment]
Actually, I also want this type of functionality. Like in the phone application when we save the contact without a photo then the app automatically saved the first letter of the contact name with some background color.

**Comment by hdodenhof** [comment]
There's no support for this built into the library as it focuses on working with images/bitmap and creating a bitmap of a letter in front of a colored background just to get a circle shape would be very inefficient. If you still want to go down that route, you can use a simple `TextView` with a a background color and then create a `Bitmap` from it, [this Stackoverflow question](https://stackoverflow.com/questions/2801116/converting-a-view-to-bitmap-without-displaying-it-in-android) might be a good starting point. The created `Bitmap` can then be used as source for your `CircleImageView`.
