### ISSUE TITLE
Set three circle image view in same activity

### ISSUE THREAD

**Issue by stekendak01** [hdodenhof/CircleImageView#416]
Hi,
This isn't about an issue but a newbie looking for help.

I have an "setting Activity" with a circle image view for the profile picture, but also 3 others smaller circle image view to show images relatives to the user; for now just the profile picture is stored on firebase but i'm willing to store all images on firebase.

Once the user set all image (with croping activity), he can save with the button save.

How should i modify the OnActivityResult to succeed?
 protected void onActivityResult(int requestCode, int resultCode, Intent data)
    {
        super.onActivityResult(requestCode, resultCode, data);

        if (requestCode == CropImage.CROP_IMAGE_ACTIVITY_REQUEST_CODE  &&  resultCode==RESULT_OK  &&  data!=null)
        {
            CropImage.ActivityResult result = CropImage.getActivityResult(data);
            imageUri = result.getUri();

            profileImageView.setImageURI(imageUri);
        }
        else

**Comment by hdodenhof** [comment]
Closing this as it's certainly obsolete by now - sorry, was quite inactive here for a while.
