### ISSUE TITLE
CicleImageView doesn't work with FrameLayout

### ISSUE THREAD

**Issue by LucaNicosia** [hdodenhof/CircleImageView#417]
Hi,
I'm trying to do something like this
![image](https://user-images.githubusercontent.com/66721906/119266305-8c913500-bbea-11eb-8903-2997c6de8c2f.png)
using this code
` <FrameLayout
                    android:id="@+id/imageFrameLayout"
                    android:layout_width="match_parent"
                    android:layout_height="wrap_content"
                    app:layout_constraintEnd_toEndOf="parent"
                    app:layout_constraintStart_toStartOf="parent"
                    app:layout_constraintTop_toTopOf="parent"
                    app:layout_constraintBottom_toTopOf="@id/recyclerViewDetails">

                    <ImageView
                        android:id="@+id/vehiclePicture"
                        android:layout_width="match_parent"
                        android:layout_height="wrap_content"
                        android:layout_marginBottom="@dimen/margin_dim"
                        android:scaleType="centerCrop"
                        app:layout_constraintBottom_toTopOf="@id/recyclerViewDetails"
                        app:layout_constraintEnd_toEndOf="parent"
                        app:layout_constraintStart_toStartOf="parent"
                        app:layout_constraintTop_toTopOf="parent"
                        tools:srcCompat="@tools:sample/avatars" />

                    <de.hdodenhof.circleimageview.CircleImageView
                        android:id="@+id/ownerImage"
                        android:layout_width="120dp"
                        android:layout_height="120dp"
                        app:srcCompat="@drawable/example_female" />
<FrameLayout/> `
but the CircleImageView is not displayed
Is it my fault or a limitation of CircleImageView?

Luca

**Comment by hdodenhof** [comment]
Try to use `android:src` instead of `app:srcCompat` for the `CircleImageView`.

**Comment by LucaNicosia** [comment]
This was the mistake. Thanks a lot
