### ISSUE TITLE
Circular image View destroy image px.

### ISSUE THREAD

**Issue by mubeenoo1** [hdodenhof/CircleImageView#424]
i'm try to load image from xml but circular image view destroying px of the image any solution ?

**Comment by mubeenoo1** [comment]
<de.hdodenhof.circleimageview.CircleImageView
            android:id="@+id/iv_media"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:src="@drawable/ic_audio_placeholder"
            app:civ_circle_background_color="@color/colorAlbumBackground" />

**Comment by hdodenhof** [comment]
Closing this as it's certainly obsolete by now - sorry, was quite inactive here for a while.
