### ISSUE TITLE
CircleImageView OutOfMemoryError 

### ISSUE THREAD

**Issue by billdizl** [hdodenhof/CircleImageView#429]
Caused by java.lang.OutOfMemoryError
Failed to allocate a 252016 byte allocation with 137008 free bytes and 133KB until OOM
dalvik.system.VMRuntime.newNonMovableArray (VMRuntime.java)

android.widget.ImageView.<init> (ImageView.java:145)
de.hdodenhof.circleimageview.CircleImageView.<init> (CircleImageView.java:89)
de.hdodenhof.circleimageview.CircleImageView.<init> (CircleImageView.java:85)

**Comment by HarinG10** [comment]
use `android:hardwareAccelerated="false"` , `android:largeHeap="true"` in your android manifest file. 

This is image shape library not image loading so you should use this library with any image loader library like glide, picasso, coil, universal image loader etc.. to load big images.

**Comment by hdodenhof** [comment]
@HarinG10|s answer is on point!
