### ISSUE TITLE
Image is cropped more from corners in Moto G5s Plus

### ISSUE THREAD

**Issue by VIkash2601** [hdodenhof/CircleImageView#435]
@hdodenhof I have developed an app and used this library for Circle ImageView for Profile Pictures. The Library is working perfectly on all the devices except Moto G5s Plus (Screen Size 5.5") where the image is cropped more (Screenshot attached). Please help me to figure out this issue.
![circle_imageview_issue_motog5s_plus](https://user-images.githubusercontent.com/38423769/215255379-7afc0dc9-7ce1-4a3e-8e3a-769c1e01b14f.jpg)

**Comment by hdodenhof** [comment]
Can you reproduce the issue in an emulator with the same Android version as on the G5s?

**Comment by VIkash2601** [comment]
Hi @hdodenhof, I have tried the same with Emulator Nexus S (Screen width: 480 and Android Version 7.1.1) and it shows the same error. 
![Screenshot 2023-01-30 145257](https://user-images.githubusercontent.com/38423769/215437660-01aaeea0-f7df-401d-8458-67cf89995458.png)

**Comment by hdodenhof** [comment]
Interesting. I just installed the sample app on an emulator with the same configuration and it works just fine. Can you post your layout file?

**Comment by VIkash2601** [comment]
Hey @hdodenhof sorry for the inconvenience, I kept my CircleImageView inside a CardView and applied cardCornerRadius. That was the main culprit 😁😁.

Thanks for your help and Have a great time ahead.

**Comment by hdodenhof** [comment]
Great! Happy to help and thanks for your feedback on the root cause.
