### ISSUE TITLE
Memory inefficiency

### ISSUE THREAD

**Issue by AlexBlokh** [hdodenhof/CircleImageView#44]
You are creating a bitmap for a color drawable instead of drawing color right into canvas
![screen shot 2015-02-24 at 11 11 15 am](https://cloud.githubusercontent.com/assets/4045375/6343180/6059c7fc-bc16-11e4-924e-f686a4195f8f.png)

**Comment by AlexBlokh** [comment]
Oh, now I see, that you create a bitmap of 2x2 size...

**Comment by hdodenhof** [comment]
I would even choose 1x1 if that would work on L (#23).
