### ISSUE TITLE
Circleimageview seems to define the height of the parent cardview.

### ISSUE THREAD

**Issue by Murtaza0xFF** [hdodenhof/CircleImageView#47]
On using CircleImageView as a child of cardview, whatever the `layout_height` of the cardview may be, it takes the height of CircleImageView. 

To put it in a different way - the cardview's height somehow becomes wrap content, and becomes just large enough to fit the CircleImageCiew.

**Comment by hdodenhof** [comment]
`CircleImageView` is based on the default `ImageView` and works in the same way so it's unlikely, that this is a problem with this library. Please provide XML / code samples for getting a better understanding of the issue.

**Comment by hdodenhof** [comment]
Closing as stale.
