### ISSUE TITLE
Transition

### ISSUE THREAD

**Issue by AlexBlokh** [hdodenhof/CircleImageView#48]
In order to support **Transition animation** you have to implement a **RoundedDrawable** and round all the layers of **LayerDrawable** inside **TransitionDrawable**
I've implemented this in my project, so I can contribute 
This is very memory efficient

**Comment by vinc3m1** [comment]
You mean like [this](https://github.com/vinc3m1/RoundedImageView/blob/master/roundedimageview/src/main/java/com/makeramen/roundedimageview/RoundedDrawable.java#L97)?

**Comment by AlexBlokh** [comment]
yeap

**Comment by hdodenhof** [comment]
AlexBlokh, thanks for your input and contribution offer! I do actually want to keep this library plain and simple and would therefore leave this out for now. Thanks.
