### ISSUE TITLE
Shadow

### ISSUE THREAD

**Issue by crysan** [hdodenhof/CircleImageView#50]
please create app:shadow="2dp"

**Comment by Rainer-Lang** [comment]
+1
please add shadow

**Comment by Corey76** [comment]
+1
for the shadow

Please ;)

**Comment by hdodenhof** [comment]
There's a PR to address this: #42.

The problem with this approach is that `LAYER_TYPE_SOFTWARE` slows down drawing dramatically and I really want to avoid that.

I'm open for any ideas on how to address this in another way though.

**Comment by MiralDesai** [comment]
To be fair isn't that how Android expects you to add a shadow? I would say it's an issue with android rather than your implementation.

One thing I was trying to do was add a drawable shape around the CircleImageView, but it was wrapping to the full view which is a square, maybe if you change that we can add a shape drawable around the image to fake a shadow?

**Comment by pixis** [comment]
Any update on this?

**Comment by kevinvanzyl** [comment]
I have a chain of circular images that increase in size from outside to the middle, they overlap slightly and the elevation increases as well. It just looks strange to have it all flat. I would be very happy if this was added.

**Comment by Mardaklysm** [comment]
This would be an awesome feature to this already great API !

**Comment by NathanaelA** [comment]
You might try this technique: http://stackoverflow.com/questions/27092711/achieve-setshadowlayer-effect-during-drawcircle-or-drawroundrect-without-turni?noredirect=1&lq=1

**Comment by NyanRex52** [comment]
I committed a branch that fix this issue but I don't know if the head dev will commit it to the master branch.   instead of applying a shadow, I made the the view accept elevation for devices >= Lollipop

**Comment by hdodenhof** [comment]
Just a quick heads up: support for elevation is on its way: https://github.com/hdodenhof/CircleImageView/tree/feature/outline-provider.

**Comment by NyanRex52** [comment]
@hdodenhof I already added it, look at my branch :)

**Comment by hdodenhof** [comment]
@NyanRex52 great, I somehow missed that. Making the `OutlineProvider` an inner class of `CircleImageView` you can actually optimize its code by accessing the calculated dimensions - have a look: https://github.com/hdodenhof/CircleImageView/commit/4fdd9db52648d0df1a7f19e0f41a25deed989bb0#diff-a2b6e34c868bc3478e513ae62c44e9b6R449.

**Comment by NyanRex52** [comment]
@hdodenhof That even looks more beautiful than what I did and less calculations. May I ask for two things:
- May I be part in the credit for this part?
- I added Ripple effect by difficult as foreground, would that be an interest feature to be added in this project?

**Comment by KingWu** [comment]
@hdodenhof is it required to set a black background?  Just use the circle image view with outline.  No shadow is shown

**Comment by hdodenhof** [comment]
Version 2.2.0 includes support for elevation, thanks @NyanRex52 for the initial idea. This should satisfy the original requirement for a shadow property, hence closing this issue.

**Comment by NyanRex52** [comment]
@hdodenhof  .... That really didn't answer anyone my questions X'D

**Comment by jemshit** [comment]
@hdodenhof is it for only api>=21?

**Comment by iciakky** [comment]
Should I use `app:shadow="2dp"` or `android:elevation="2dp"` ?
The former give me an error `error: attribute 'path.to.my.package:shadow' not found.`
and the latter seems produce no shadow on my CircleImageView

using version 2.2.0
and running on android 5.0.2

**Comment by longxuewei** [comment]
> Should I use `app:shadow="2dp"` or `android:elevation="2dp"` ? The former give me an error `error: attribute 'path.to.my.package:shadow' not found.` and the latter seems produce no shadow on my CircleImageView
> 
> using version 2.2.0 and running on android 5.0.2
> 
> EDIT: looks like `android:elevation="2dp"` is the answer, as my shadow shows right after I swipe the RecyclerView containing (indirectly) these CircleImageView, still don't know why they're hiding before swiping
> 
> EDIT2: It seems to me that the cause is: I'm using Glide loading image from url into CircleImageView, which must be done asynchronously, thus CircleImageView decided not to cast any shadow for there is no image (yet). Base on this, I solve this problem with placeholder. e.g. `Glide.with(context).load(imageUrl).placeholder(R.color.lighter_gray).dontAnimate().into(my_circle_image_view)` hope this is helping :)

oh god you saved me.
