### ISSUE TITLE
Loading Internet Images with Glide

### ISSUE THREAD

**Issue by jaydeep17** [hdodenhof/CircleImageView#57]
Till now I used to use Picasso for loading images. Right now I'm moving to Glide and there's an issue with that.

When loading images from the internet for the first time, it doesn't show up in the CircleImageView (Glide isn't able to replace the placeholder image).

Setup:
-------

I have an activity with just a CircleImageView. I use the below code to load image  using glide

```Java
Glide.with(this)
    .load("https://s3.amazonaws.com/xyz.png")
    .placeholder(R.drawable.abc)
    .into(imgView);
```

Steps to Reproduce:
--------------

1) Fresh install and open the app
2) The placeholder shows up, while the image is getting downloaded
3) The placeholder is never replaced by the actual image, even though the image has been downloaded and cached
4) Go back
5) Re-open the app
6) The image appears

Note: I have tried replacing the CircleImageView with a regular ImageView and it works perfectly.

**Comment by hdodenhof** [comment]
I haven't used Glide myself, but I'm pretty sure this is the same issue as #20, #5 and #3.

You might be able to work around this limitation using a custom target:
```
Glide.with(this)
    .load("https://s3.amazonaws.com/xyz.png")
    .placeholder(R.drawable.abc)
    .into(new SimpleTarget<Bitmap>(width, height) {
        @Override
        public void onResourceReady(Bitmap bitmap, GlideAnimation anim) {
            // setImageBitmap(bitmap) on CircleImageView
        }
    };
```

**Comment by thewbb** [comment]
ok，you can disable this fade by this way.
Glide.with(this).load("http://www.google.com/logo108.png").placeholder(R.mipmap.ic_launcher).dontAnimate().into(circleImageView);

**Comment by hdodenhof** [comment]
Closing this as solved.
