### ISSUE TITLE
Hides default view(color) of ImageView

### ISSUE THREAD

**Issue by meet2011** [hdodenhof/CircleImageView#61]
Hello,

I am trying to display circle image on profile screen as soon as onActivityResult call is reached, it initially disappears the current view i.e White color of imageview and then it loads. Why it doesn't stay to white until it gets loaded?

` <com.kickzexchange.custom.CircleImageView
                android:id="@+id/ivProfileImage"
                android:layout_width="100dp"
                android:layout_height="100dp"
                android:layout_marginTop="10dp"
                android:src="@color/White"
                app:border_color="@color/Maroon"
                app:border_width="2dp">
`

	@Override
	public void onActivityResult(int requestCode, int resultCode, Intent data) {
		// TODO Auto-generated method stub
		super.onActivityResult(requestCode, resultCode, data);

		if (requestCode == SELECT_IMAGE_RQ_CODE) {

			if (resultCode == Activity.RESULT_OK) {

				ivProfileImage.setImageResource(mActivity.getResources()
						.getColor(R.color.White));
				ivProfileImage.setBorderWidth(2);
				ivProfileImage.setBorderColor(getResources().getColor(
						R.color.Maroon));

				Uri selectedImageUri = data.getData();

				Picasso.with(this).load(selectedImageUri)
						.into(ivProfileImage);
			}
		}
}

**Comment by hdodenhof** [comment]
This is not an issue with this library but the default behaviour of `Picasso`: calling `into()` on the `RequestCreator` clears any existing `Drawable` of the `ImageView`, in your case the white color.

Two possible solutions:

1. call `noPlaceholder()` on the `Picasso` `RequestCreator` to explicitly not clear the drawable
2. call `setPlaceholder()` on the `Picasso` `RequestCreator` with a white `ColorDrawable` to let `Picasso` handle the placeholder. You could then get rid of `setImageResource(mActivity.getResources().getColor(R.color.White));`
