### ISSUE TITLE
Attribute "border_color" has already been defined

### ISSUE THREAD

**Issue by jonasborggren** [hdodenhof/CircleImageView#62]
Dependency

> compile 'de.hdodenhof:circleimageview:1.3.0'

Getting error when building:

> Error:(2) Attribute "border_color" has already been defined
> Error:(2) Attribute "border_width" has already been defined

I don't have these values in my values/colors.xml or anywhere else.
This problem occured when adding this library to my gradle file.

**Comment by hdodenhof** [comment]
This will be fixed after merging #58. You could build that branch yourself until I'll upload a new build to maven central.

**Comment by jonasborggren** [comment]
Ok thats great! Thanks.

**Comment by alec-castellanos** [comment]
I got the same problem. The source was the fact that I also had in my Gradle file the library Pkmmte/CircularImageView. I guess Pkmmte also defined those values

**Comment by hdodenhof** [comment]
Fixed in master: 8e1e781.

**Comment by stjom** [comment]
Hi, first off, thanks for this great library! May I ask when will this be pushed to the maven central?

**Comment by hdodenhof** [comment]
I just pushed v2.0.0 with this fixed.
