### ISSUE TITLE
How to set background color for the Circle View?

### ISSUE THREAD

**Issue by JSafaiyeh** [hdodenhof/CircleImageView#64]
Setting the background color, colors the whole image view. How do I only color the circle view?
![11642035_994392247268422_962917052_o](https://cloud.githubusercontent.com/assets/8675043/8318382/c3dcc0b8-19b8-11e5-9ed9-5d9ccdda336b.jpg)

**Comment by hdodenhof** [comment]
There's an incomplete PR for this: #45 - I still need to find some time to cleanup and merge that one.

**Comment by hdodenhof** [comment]
Quick workaround:
```
CircleImageView imageView = ...

Drawable color = new ColorDrawable(getResources().getColor(R.color.foo));
Drawable image = getResources().getDrawable(R.drawable.bar);

LayerDrawable ld = new LayerDrawable(new Drawable[]{color, image});
imageView.setImageDrawable(ld);
```

**Comment by JSafaiyeh** [comment]
Thanks, the workaround worked great.

**Comment by Shreyas-R** [comment]
Still if you use xml way of setting background, it applies to whole rectangular button view. It wont apply only to circle view.

**Comment by hdodenhof** [comment]
@Shreyas-R in XML you can now use the `civ_fill_color` attribute.

**Comment by Shreyas-R** [comment]
Like android:civ_fill_color=..... ??

**Comment by hdodenhof** [comment]
`app:civ_fill_color`

**Comment by Shreyas-R** [comment]
Using app: gives no Resource identifier error

**Comment by mrgren** [comment]
imageView.setFillColor(R.color.yourcolor)

**Comment by CusProjects** [comment]
It appears out of the bounds as a square, help please.

**Comment by hdodenhof** [comment]
@CusProjects: you are in the wrong place, this is for `de.hdodenhof.CircleImageView`.

**Comment by madhavkate** [comment]
How to set Image from Url ..... Please tell me

**Comment by madhavkate** [comment]
How to set Image from Url ..... Please tell me

**Comment by madhavkate** [comment]
How to set Image from Url ..... Please tell me

**Comment by CusProjects** [comment]
@madhavkate You can use an external library like Picasso.

**Comment by madhavkate** [comment]
Thank You Sir,,
 I have use Picasso like this  

Picasso.with(activity).load"my image Url here").noFade().into(profile_photo1);

but App going to crash i.e. Unfortunately stop and when remove above code and add image from drawable folder  then working fine... But now how to set image by  Url

**Comment by madhavkate** [comment]
Thank You Sir,,
I have use Picasso like this

Picasso.with(activity).load("my image Url here").noFade().into(profile_photo1);

but App going to crash i.e. Unfortunately stop and when remove above code and add image from drawable folder then working fine... But now how to set image by Url

**Comment by Ananthusubramanian** [comment]
@madhavkate 
Picasso example for loading the image from url :
Picasso.with(context).load(image_link).placeholder(R.drawable.pic).into(ImageView);

**Comment by franquicidad** [comment]
Hello i am retreiving a value from a database for a background color with the reference for example #FAFAFA how can i set the background with this color. Thank you for this library by the way, im using java.

**Comment by iamsb1896** [comment]
Try this:
`app:civ_circle_background_color="@color/gray"`
