### ISSUE TITLE
Set minSdkVersion to 8

### ISSUE THREAD

**Issue by daniele-athome** [hdodenhof/CircleImageView#67]
Are there any issues setting minSdkVersion to 8? Or even a lower value?
At least building with min API 8 works.

**Comment by hdodenhof** [comment]
No reason, I just don't consider Froyo relevant anymore. Anyways, I changed `minSdkVersion` to 8 in master (1f5c50c) - wouldn't be comfortable setting in any lower though.

**Comment by daniele-athome** [comment]
Thanks!
