### ISSUE TITLE
when  the CircleImageView use on android 5.0

### ISSUE THREAD

**Issue by lilang** [hdodenhof/CircleImageView#68]
when  the CircleImageView use on android 5.0 , Have a gray square, can be seen when click disappeared, what reason is this?

**Comment by LittlePanpc** [comment]
Yes, it seems that I had the same problem. Take a look at the screenshot below:

![2015-07-06 14 57 53](https://cloud.githubusercontent.com/assets/4122407/8517104/727f2ac6-23ef-11e5-9436-175e40772732.png)

**Comment by yolapop** [comment]
I get this too

**Comment by jiuwu0905** [comment]
this is work on 4.x ,but 5.0 fail,

<xx.CircleImageView
                android:layout_width="15dp"
                android:layout_height="15dp"
                android:layout_gravity="center"
                android:src="#59cae9" />

**Comment by testride2013** [comment]
@LittlePanpc : Just Try following thing It solve your issue. 

First thing : private static final ScaleType SCALE_TYPE = ScaleType.CENTER_CROP;

Second : Set image following way if you are selecting image form gallery or camera.
Do not use any library to set image or display image. use native way to display image.
Like image_profile.setImageURI(Uri.fromFile(new File("<Your image local file path>")));




@jiuwu0905 remove android:src="#59cae9"

**Comment by hdodenhof** [comment]
Please provide are more detailed description / code samples / images - I'm not sure what the issue is here.

**Comment by sakurabird** [comment]
@LittlePanpc You should try.
android:src="@drawable/header"
instead android:src="@mipmap/header"

**Comment by LittlePanpc** [comment]
@sakurabird What's the difference? Both are Drawable but not at the same directory.

**Comment by NooooWorries** [comment]
add this:
 android:layout_gravity="center_horizontal"
