### ISSUE TITLE
getDrawingCache return null

### ISSUE THREAD

**Issue by jmmt** [hdodenhof/CircleImageView#71]
I'm trying to get a Bitmap from CircleImageView using getDrawingCache and always get null. I do this...

        CircleImageView civProfilePic = new CircleImageView(this);
        civProfilePic.setBorderWidth(5);
        civProfilePic.setImageBitmap(BitmapFactory.decodeResource(getResources(), R.drawable.user2));
        Bitmap roundImage = civProfilePic.getDrawingCache();

and roundImage == null

**Comment by hdodenhof** [comment]
This library doesn't interfere with the drawing cache so I guess you would have the same issue with the default `ImageView`. Try this:

```
    CircleImageView civProfilePic = new CircleImageView(this);
    civProfilePic.setBorderWidth(5);
    civProfilePic.setImageBitmap(BitmapFactory.decodeResource(getResources(), R.drawable.user2));
    civProfilePic.measure(MeasureSpec.makeMeasureSpec(0, MeasureSpec.UNSPECIFIED), MeasureSpec.makeMeasureSpec(0, MeasureSpec.UNSPECIFIED));
    civProfilePic.layout(0, 0, civ.getMeasuredWidth(), civ.getMeasuredHeight());
    civProfilePic.setDrawingCacheEnabled(true);
    Bitmap roundImage = civProfilePic.getDrawingCache();
```
