### ISSUE TITLE
Crash when setImageDrawable using TextDrawable

### ISSUE THREAD

**Issue by antercepter** [hdodenhof/CircleImageView#72]
Hi!

I have a problem, when try to set drawable using this library https://github.com/amulyakhare/TextDrawable

It works normal when I use standard ImageView, when I use your widget, I got an exception

java.lang.IllegalArgumentException: width and height must be > 0
08-05 16:57:52.307  28689-28689/com.iwant2.android W/System.err﹕ at android.graphics.Bitmap.createBitmap(Bitmap.java:810)
08-05 16:57:52.307  28689-28689/com.iwant2.android W/System.err﹕ at android.graphics.Bitmap.createBitmap(Bitmap.java:789)
08-05 16:57:52.307  28689-28689/com.iwant2.android W/System.err﹕ at android.graphics.Bitmap.createBitmap(Bitmap.java:756)
08-05 16:57:52.307  28689-28689/com.iwant2.android W/System.err﹕ at de.hdodenhof.circleimageview.CircleImageView.getBitmapFromDrawable(CircleImageView.java:227)
08-05 16:57:52.307  28689-28689/com.iwant2.android W/System.err﹕ at de.hdodenhof.circleimageview.CircleImageView.setImageDrawable(CircleImageView.java:183)

**Comment by hdodenhof** [comment]
TextDrawable has native support for displaying a circle, just use that combined with a standard ImageView.

**Comment by kelvinkoko** [comment]
I have the same issue when using both library. 
My use case is i need to use "TextDrawable" as fall back if avatar not given (Avatar is not circular)

To use TextDrawable in CircularImageView, you can specific TextDrawable explicitly before setImageDrawable
<pre><code>
      TextDrawable drawable = TextDrawable.builder()
                    .beginConfig()
                    .width(100)
                    .height(100)
                    .endConfig()
                    .buildRect("A", Color.RED);
            mView.setImageDrawable(drawable);
</code></pre>
