### ISSUE TITLE
java.lang.IllegalArgumentException: width and height must be > 0

### ISSUE THREAD

**Issue by xiaomeixw** [hdodenhof/CircleImageView#78]
java.lang.IllegalArgumentException: width and height must be > 0
	at android.graphics.Bitmap.createBitmap(Bitmap.java:810)
       CircleImageView.getBitmapFromDrawable(CircleImageView.java:227)
       CircleImageView.setImageDrawable(CircleImageView.java:183)
       at com.nostra13.universalimageloader.core.imageaware.ImageViewAware.setImageDrawable(ImageViewAware.java:171)
......

**Comment by xiaomeixw** [comment]
use   universalimageloader   
                                 the mothod  
                                                    drawable.getIntrinsicWidth()   return     -1;

**Comment by 3c** [comment]
I have the same problem 
have you found a solution ?

**Comment by act262** [comment]
you neet to mesure your view before use it,otherwise get height and widht both 0.

**Comment by hdodenhof** [comment]
It seems you are trying to use an incompatible drawable - or UniversalImageLoader does. This won't crash in current master (90f6250).

**Comment by myanimal** [comment]
@hdodenhof is there an ETA on this getting released? Or a snapshot version to test?
Thanks.

**Comment by hdodenhof** [comment]
A snapshot is available in the Sonatype OSS snapshot repo:
```
repositories {
    ...
    maven { url 'https://oss.sonatype.org/content/repositories/snapshots/' }
}
```

```
compile 'de.hdodenhof:circleimageview:2.0.0-SNAPSHOT'
```

I'll try to get this released by the weekend.

**Comment by myanimal** [comment]
Excellent, thanks! Tested and everything appears to be working well.

**Comment by hdodenhof** [comment]
@myanimal v2.0.0 final has just been released.
