### ISSUE TITLE
Black background 

### ISSUE THREAD

**Issue by prashanthd** [hdodenhof/CircleImageView#79]
Some times Black background  in rectangle shape is coming around circle image. It is happening in lollipop. I tried a lot but failed to find the solution.

**Comment by hdodenhof** [comment]
I can't do much without a little more details, i.e. an image showing this behaviour.

**Comment by prashanthd** [comment]
![screenshot_2015-09-15-14-52-19](https://cloud.githubusercontent.com/assets/11071084/9872877/c1802100-5bb9-11e5-9086-41f1c7d61628.png)
![screenshot_2015-09-15-14-52-25](https://cloud.githubusercontent.com/assets/11071084/9872878/c187fbdc-5bb9-11e5-873b-95991f8273d7.png)
![screenshot_2015-09-15-14-52-49](https://cloud.githubusercontent.com/assets/11071084/9872879/c1952bb8-5bb9-11e5-9304-b580e86cac21.png)

**Comment by prashanthd** [comment]
In most of the screens its working fine. I made your circularimageview to extend NetworkImageView(Volley) to easily download the image. Is this problem because of that?

**Comment by hdodenhof** [comment]
Thanks! I've never used NetworkImageView myself, so I can't really say. Could you just try with an unmodified version of CircleImageView?

**Comment by prashanthd** [comment]
For fetching images I replaced volley with Picasso. Now this problem is not coming.

**Comment by hdodenhof** [comment]
Alright, thanks for the update! I'm closing this then.
