### ISSUE TITLE
Sometimes Border larger than the CircleImageView size!

### ISSUE THREAD

**Issue by start141** [hdodenhof/CircleImageView#81]
When the min of CircleImageView's width and height is odd, sometimes the image showed like:

![2e493250-4e63-404e-adb7-370a166f694b](https://cloud.githubusercontent.com/assets/6055764/9812671/65ee1df2-58b1-11e5-99d0-00e3928620e8.png)

**Comment by hdodenhof** [comment]
Should be fixed by #60 which I just merged. Please retest with current master branch. Thanks!

**Comment by start141** [comment]
Thanks!
