### ISSUE TITLE
cannot resolve dependency

### ISSUE THREAD

**Issue by balvirjha** [hdodenhof/CircleImageView#85]
Error:(24, 13) Failed to resolve: de.hdodenhof:circleimageview:2.0.0

**Comment by hdodenhof** [comment]
Please verify your setup, the artifact is definitely available in Maven Central: http://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22de.hdodenhof%22%20AND%20a%3A%22circleimageview%22.

**Comment by enriqif** [comment]
I had the same error.. could you resolve this?
