### ISSUE TITLE
Show place holder till image loads

### ISSUE THREAD

**Issue by prashanthd** [hdodenhof/CircleImageView#86]
I want to show a place holder image( as a background or any other way) till main image downloads. I am using picasso lib to load images. I tried to use app:civ_fill_color but didn't work. is there any way to achieve it?

**Comment by prashanthd** [comment]
Specially CircleImageView in listview.

**Comment by hdodenhof** [comment]
`Picasso.with(context).load("http://...").placeholder(R.drawable.foobar).noFade().into(imageView)`

**Comment by prashanthd** [comment]
I didn't used noFade() method. as of know its working good.

**Comment by hdodenhof** [comment]
Just be aware that there might be some issues with fading as described here: #3, #5.
