### ISSUE TITLE
Add shadow to CircleImageView

### ISSUE THREAD

**Issue by anticafe** [hdodenhof/CircleImageView#89]
I see there is [a topic in StackOverflow](http://stackoverflow.com/questions/17655264/how-to-add-a-shadow-and-a-border-on-circular-imageview-android) discuss about add shadow to CircularImageView. Could you implement such feature?

**Comment by MiralDesai** [comment]
+1 would love this.

**Comment by hdodenhof** [comment]
Duplicate of #50.
