### ISSUE TITLE
Forcing to create a new Bitmap will lose drawable callbacks

### ISSUE THREAD

**Issue by qezt** [hdodenhof/CircleImageView#91]
As the consequence:

* If I use a TransitionDrawable, it will not animate
* setImageAlpha won't work

It seems like the drawback of using BitmapShader, it has to be converted to a Bitmap object in advance.

**Comment by yuanjize** [comment]
thanks,I will correct it.

**Comment by hdodenhof** [comment]
This is unfortunately a limitation of the current implementation.
