### ISSUE TITLE
CircleImageView don't support the  Drawable, it has problem with Glide

### ISSUE THREAD

**Issue by qinjuning** [hdodenhof/CircleImageView#94]
Hi hdodenhof :
    I find out that CircleImageView don't work well with  Glide, the thread is <a href="https://github.com/bumptech/glide/issues/757"> Issuse </a> . Will you add the Drawable in ```getBitmapFromDrawable``` method ?  Because of so many project take their own custom Drawable.

**Comment by hdodenhof** [comment]
Duplicate of #57. Use `.dontAnimate()` when using Glide, I'll add this to the known limitations.
