### ISSUE TITLE
Support CENTER image?

### ISSUE THREAD

**Issue by KennyGoers** [hdodenhof/CircleImageView#95]
I'll look at the code myself, but it would be helpful to support just CENTER and not resize the image for times when no image is available and you want a solid color with a transparent background image.

**Comment by hdodenhof** [comment]
I'm not completely sure what you are trying to achieve but I currently don't plan on adding support for other scale types, as I don't see any real use case for that with a circled view.

If you need more flexibility you might want to have look at [RoundedImageView from Vince Mi](https://github.com/vinc3m1/RoundedImageView). It supports different scale types and also got support for circles a while back.
