### ISSUE TITLE
Error: android.view.InflateException: Binary XML file line #28: Error inflating class de.hdodenhof.circleimageview.CircleImageView

### ISSUE THREAD

**Issue by Prographer** [hdodenhof/CircleImageView#96]
Hi, 
Thank you for your project ^^;

I found an crash.
I just add [compile 'com.google.android.gms:play-services-analytics:8.3.0'] in my gradle, and add code in my main activity.
however, if I delete that code my app is ok.

this is my build.gradle
```
apply plugin: 'com.android.application'
apply plugin: 'com.google.gms.google-services'


android {
    compileSdkVersion 23
    buildToolsVersion "23.0.1"



    defaultConfig {
        applicationId "com.xxx.xxx"
        minSdkVersion 15
        targetSdkVersion 23
        versionCode 152
        versionName "4.4.1"
        multiDexEnabled true
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
    packagingOptions {
        exclude 'META-INF/LICENSE'
        exclude 'META-INF/NOTICE'
        exclude 'META-INF/LICENSE.txt'
        exclude 'META-INF/NOTICE.txt'
    }
    /*productFlavors {
        dev {
            minSdkVersion 15
        }
        prod {
            minSdkVersion 15
        }
    }*/
}



dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    compile 'com.android.support:appcompat-v7:23.1.0'           //Support Library
    compile 'com.android.support:cardview-v7:23.1.0'            //CardView Library
    compile 'com.android.support:gridlayout-v7:23.1.0'          //GridLayout Library
    compile 'com.android.support:recyclerview-v7:23.1.0'
    compile 'com.android.support:palette-v7:23.1.0'
    compile 'com.android.support:design:23.1.0'                 //Design Support Library

    compile 'com.github.rey5137:material:1.2.1'                 //Material Design Support/ https://github.com/rey5137/material

    compile 'com.squareup.retrofit:retrofit:1.9.0'              //Network Library
    compile 'com.squareup.okhttp:okhttp-urlconnection:2.4.0'
    compile 'com.github.bumptech.glide:glide:3.6.1'             //Network Image Library/    https://github.com/bumptech/glide
    compile 'com.github.bumptech.glide:okhttp-integration:1.3.1'
    compile 'com.squareup.okhttp:okhttp:2.5.0'                  //Network Client/           http://square.github.io/okhttp/

    compile 'de.hdodenhof:circleimageview:2.0.0'                //Circle Image             https://github.com/hdodenhof/CircleImageView

    compile 'com.facebook.android:facebook-android-sdk:4.1.0'   //facebook sdk

    compile 'com.google.android.gms:play-services-analytics:8.3.0'
}

```

and my Application.java 

```
 private Tracker tracker;

    synchronized public Tracker getDefaultTracker() {
        if (tracker == null) {
            GoogleAnalytics analytics = GoogleAnalytics.getInstance(this);
            tracker = analytics.newTracker(R.xml.global_tracker);
        }

        return tracker;
    }
```

and my MainActivity.java
```
Application application = (Application) getApplication();
        Tracker tracker = application.getDefaultTracker();
        tracker.setScreenName(MainActivity.class.getName());
        tracker.send(new HitBuilders.ScreenViewBuilder().build());
```

and than Exception message
```
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.xxx.xxx/com.xxx.xxx.activity.MainActivity}: android.view.InflateException: Binary XML file line #28: Error inflating class de.hdodenhof.circleimageview.CircleImageView
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2067)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2092)
	at android.app.ActivityThread.access$600(ActivityThread.java:138)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1203)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:137)
	at android.app.ActivityThread.main(ActivityThread.java:4874)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:511)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:556)
	at dalvik.system.NativeStart.main(Native Method)
Caused by: android.view.InflateException: Binary XML file line #28: Error inflating class de.hdodenhof.circleimageview.CircleImageView
	at android.view.LayoutInflater.createView(LayoutInflater.java:613)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:687)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:746)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:749)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:749)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:749)
	at android.view.LayoutInflater.parseInclude(LayoutInflater.java:830)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:736)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:749)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:489)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:396)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:352)
	at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:256)
	at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:109)
	at com.xxx.xxx.activity.MainActivity.onCreate(MainActivity.java:96)
	at android.app.Activity.performCreate(Activity.java:5008)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1079)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2031)
	... 11 more
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Constructor.constructNative(Native Method)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:417)
	at android.view.LayoutInflater.createView(LayoutInflater.java:587)
	... 28 more
Caused by: java.lang.NoClassDefFoundError: de.hdodenhof.circleimageview.R$styleable
	at de.hdodenhof.circleimageview.CircleImageView.<init>(CircleImageView.java:71)
	at de.hdodenhof.circleimageview.CircleImageView.<init>(CircleImageView.java:65)
	... 31 more
```

thank you,

**Comment by Prographer** [comment]
ah,lollipop is ok.

Test Android Verison
- 4.1.2: Fail
- 4.4.2: Fail
- 5.0.1: OK
- 5.1.1: OK

**Comment by mdimello** [comment]
The error is probably caused by an incorrect implementation of multidex in your application. Read Android's documentation regarding multidex. There you'll find an explanation about the subject and a tutorial for implementing multidex support to android versions prior to 5.0.

http://developer.android.com/intl/pt-br/tools/building/multidex.html

**Comment by shahrukhamd** [comment]
I have the same issue and don't even have **multidex** enabled

**Comment by rahulfhp** [comment]
Same here !, Any Fix ?

**Comment by meilers** [comment]
Here too, same problem

**Comment by WOSHICAIXIANFENG** [comment]
Hello, man  @Prographer   Any Fix ??

**Comment by ydfebri** [comment]
i think it's not google play-services-analytics but it's facebook sdk fault, i have some problem can anyone help for this ?? @Prographer any clue or sugestion about this???

**Comment by ydfebri** [comment]
I have some way to fix this problem. Why this problem is coming.
1. [problem](http://www.akexorcist.com/2016/02/dex-with-over-65k-and-multidex-on-android-en.html). This article explain we have method more than 65k.
2. [how to fix](http://stackoverflow.com/questions/32110859/fatal-exception-java-lang-noclassdeffounderror-android-support-v7-appcompat-r).
3. [how to fix if we use google analytic](http://stackoverflow.com/questions/34094808/how-to-use-google-analytics-in-android-app-with-over-65k-methods).
I hope this realy helpful. sorry for my bad english.

**Comment by Sjalistra** [comment]
It's been almost half a year and it's still an issue

**Comment by hdodenhof** [comment]
The original author's issue is most likely related to an incorrect implementation of multidex and should be solved by following http://developer.android.com/intl/pt-br/tools/building/multidex.html and http://developer.android.com/intl/pt-br/tools/support-library/features.html#multidex.

If you are having this issue without using multidex, please provide a full stack trace and more details about your setup.

**Comment by Sjalistra** [comment]
I've sent you an email regarding all the information about the subject

**Comment by Prographer** [comment]
I tried to upgrade google analytics library. (8.3.0 --> 8.4.0, It works fine.)

`compile 'com.google.android.gms:play-services-analytics:8.4.0'`

thank you

**Comment by Sjalistra** [comment]
I'm not even using it but I think I found what was wrong in my project

**Comment by shihabmi7** [comment]
The issue is solved by following http://stackoverflow.com/questions/32110859/fatal-exception-java-lang-noclassdeffounderror-android-support-v7-appcompat-r this post answer.

**Comment by singhania1408** [comment]
i have enable MultiDex but still in below lollipop Error is showing.

**Comment by iamerrorist** [comment]
In my case it was just wrong placing an icon image! when I pasted it to drawable, I didn't notice ".../drawable-v21" in the confirm dialog. AndroidStudio was just keep repeating "Error inflating class de.hdodenhof.circleimageview.CircleImageView". It takes about 2 hours for me to find it! Anyway...

**Comment by gomez1104** [comment]
Same for me. 
My solution was to move my shapes (xml background) from drawable-v21 to drawable.

**Comment by alpaltunel** [comment]
defaultConfig {
        applicationId "xxxx"
        minSdkVersion 16
        targetSdkVersion 23
        versionCode 17
        versionName '1.9.0'
        // Enabling multidex support.
        multiDexEnabled true
    }

app class:
public class MyApp extends MultiDexApplication

and add at the end of MyApp.java

    @Override
    protected void attachBaseContext(Context base)
    {
        super.attachBaseContext(base);
        MultiDex.install(this);
    }

gradle dependencies:
    compile 'com.android.support:multidex:1.0.1'

**Comment by sshahidaslamm** [comment]
For Android Studio 3.0.1

I have got the same issue and I have resolved finally Opening the `gradle.properties` and added following line:

`android.enableAapt2=false`

**Comment by leesandy** [comment]
Thank you to give advice to me i love find it and send to you after

Vào 13 thg 2, 2018 2:50 CH, "Shahid Aslam" <notifications@github.com> đã
viết:

**Comment by varotariyavm** [comment]
I just remove android:scaleType="fitCenter" from imageview xml and its working fine now.

**Comment by Prof-Rodrigo-Silva** [comment]
> I just remove android:scaleType="fitCenter" from imageview xml and its working fine now.

I can't explain why, but when I removed `android:scaleType="centerInside"` the error was over ...

**Comment by mzaruna** [comment]
i fixed the issue ,project change to andoridx its Coming
change the multidex support to dependencies
implementation 'androidx.multidex:multidex:2.0.1'
 defaultConfig {
   multiDexEnabled = true
}
i hope its useful to all
