### ISSUE TITLE
java.lang.IllegalStateException Immutable bitmap passed to Canvas constructor

### ISSUE THREAD

**Issue by ruijun** [hdodenhof/CircleImageView#99]
When I use CircleImageView,  is crash in Android 5.1,level 22

The crash message:

java.lang.IllegalStateException
Immutable bitmap passed to Canvas constructor
android.graphics.Canvas.<init>(Canvas.java:150)
com.jiahe.qixin.ui.widget.CircleImageView.getBitmapFromDrawable(CircleImageView.java:323)
com.jiahe.qixin.ui.widget.CircleImageView.setImageDrawable(CircleImageView.java:268)

**Comment by hdodenhof** [comment]
How are you creating the `Drawable` you are passing to `setImageDrawable`?
